// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// APIResponse defines model for APIResponse.
type APIResponse struct {
	Data    interface{} `json:",omitempty"`
	Message string      `json:"message"`
}

// AddClaimRequest defines model for AddClaimRequest.
type AddClaimRequest struct {
	// ClaimTopic The topic of the claim (e.g., 7 for KYC)
	ClaimTopic int `json:"claimTopic"`
	UserId     int `json:"userId"`
}

// AddClaimResponse defines model for AddClaimResponse.
type AddClaimResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// BurnTokenRequest defines model for BurnTokenRequest.
type BurnTokenRequest struct {
	// Amount The amount of tokens to burn, in human format (not wei)
	Amount float64 `json:"amount"`

	// To The address to burn the tokens to
	To string `json:"to"`

	// TokenContractAddress The address of the token contract
	TokenContractAddress string `json:"tokenContractAddress"`
}

// BurnTokenResponse defines model for BurnTokenResponse.
type BurnTokenResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// ConfigureAuthorityResponse defines model for ConfigureAuthorityResponse.
type ConfigureAuthorityResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// ContractDetails defines model for ContractDetails.
type ContractDetails struct {
	// Address The address of the contract
	Address string `json:"address"`

	// ExplorerUrl Direct link to the contract on Etherscan
	ExplorerUrl *string `json:"explorerUrl,omitempty"`

	// Name The name/type of the contract
	Name string `json:"name"`
}

// CreateIdentityRequest defines model for CreateIdentityRequest.
type CreateIdentityRequest struct {
	// CountryCode The country code of the investor
	CountryCode int `json:"countryCode"`

	// UserId The user ID of the investor
	UserId int `json:"userId"`
}

// CreateIdentityResponse defines model for CreateIdentityResponse.
type CreateIdentityResponse struct {
	Data    *IdentityInfos `json:"data,omitempty"`
	Message string         `json:"message"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	// NbDecimal Number of decimals
	NbDecimal int `json:"nbDecimal"`

	// TokenName Name of the token
	TokenName string `json:"tokenName"`
}

// CreateTokenResponse defines model for CreateTokenResponse.
type CreateTokenResponse struct {
	Data    *TokenInfos `json:"data,omitempty"`
	Message string      `json:"message"`
}

// IdentityInfos defines model for IdentityInfos.
type IdentityInfos struct {
	// CountryCode The country code of the investor
	CountryCode int `json:"countryCode"`

	// IdentityAddress The address of the created identity
	IdentityAddress string `json:"identityAddress"`

	// TransactionHash The hash of the transaction
	TransactionHash string `json:"transactionHash"`

	// UserId The user ID of the investor
	UserId int `json:"userId"`

	// WalletAddress The wallet address of the investor
	WalletAddress string `json:"walletAddress"`
}

// InitializeIdentityFactoryResponse defines model for InitializeIdentityFactoryResponse.
type InitializeIdentityFactoryResponse struct {
	Data    *ContractDetails `json:"data,omitempty"`
	Message string           `json:"message"`
}

// JwtToken defines model for JwtToken.
type JwtToken struct {
	ExpiresAt    time.Time `json:"expiresAt"`
	RefreshToken string    `json:"refreshToken"`
	Token        string    `json:"token"`
	User         User      `json:"user"`
}

// MintTokenRequest defines model for MintTokenRequest.
type MintTokenRequest struct {
	// Amount The amount of tokens to mint, in human format (not wei)
	Amount float64 `json:"amount"`

	// To The address to mint the tokens to
	To string `json:"to"`

	// TokenContractAddress The address of the token contract
	TokenContractAddress string `json:"tokenContractAddress"`
}

// MintTokenResponse defines model for MintTokenResponse.
type MintTokenResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignInResponse defines model for SignInResponse.
type SignInResponse struct {
	Data    *JwtToken `json:"data,omitempty"`
	Message string    `json:"message"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Password string              `json:"password"`
}

// SignUpResponse defines model for SignUpResponse.
type SignUpResponse struct {
	Data    *JwtToken `json:"data,omitempty"`
	Message string    `json:"message"`
}

// TokenDetails defines model for TokenDetails.
type TokenDetails struct {
	// Address The address of the token contract
	Address string `json:"address"`

	// Decimals The number of decimals for the token
	Decimals int `json:"decimals"`

	// ExplorerUrl Direct link to the token on Etherscan
	ExplorerUrl string `json:"explorerUrl"`

	// Name The name of the token
	Name string `json:"name"`

	// Symbol The symbol of the token
	Symbol string `json:"symbol"`

	// TotalSupply The total supply of tokens (in wei format)
	TotalSupply string `json:"totalSupply"`
}

// TokenInfos defines model for TokenInfos.
type TokenInfos struct {
	// OnbehalfTransactions A list of transactions performed on behalf of the identity
	OnbehalfTransactions *[]TxHashName `json:"OnbehalfTransactions,omitempty"`

	// Address Address of the token contract
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`

	// ModularComplianceAddr Address of the modularCompliance contract
	ModularComplianceAddr *string `json:"modularComplianceAddr,omitempty"`
	NbDecimal             int64   `json:"nbDecimal"`

	// Symbol Symbol of token
	Symbol string `json:"symbol"`

	// TokenName Name of token
	TokenName string `json:"token_name"`
}

// TrexSuiteInfos defines model for TrexSuiteInfos.
type TrexSuiteInfos struct {
	ClaimTopicsRegistry     ContractDetails `json:"claimTopicsRegistry"`
	IdentityRegistry        ContractDetails `json:"identityRegistry"`
	IdentityRegistryStorage ContractDetails `json:"identityRegistryStorage"`
	ModularCompliance       ContractDetails `json:"modularCompliance"`

	// Salt The salt used for the TREX Suite deployment
	Salt                   string          `json:"salt"`
	Token                  TokenDetails    `json:"token"`
	TrexFactory            ContractDetails `json:"trexFactory"`
	TrustedIssuersRegistry ContractDetails `json:"trustedIssuersRegistry"`
}

// TxHashName defines model for TxHashName.
type TxHashName struct {
	// OperationName The name of the operation performed
	OperationName string `json:"operationName"`

	// TransactionHash The hash of the transaction that performed the operation
	TransactionHash string `json:"transactionHash"`
}

// User defines model for User.
type User struct {
	// CreatedAt Date de création du compte
	CreatedAt time.Time `json:"created_at"`

	// Email Email de l'utilisateur
	Email openapi_types.Email `json:"email"`

	// FullName Nom complet de l'utilisateur
	FullName string `json:"full_name"`

	// Id ID unique de l'utilisateur
	Id int `json:"id"`

	// LastConnexion Date de la dernière connexion
	LastConnexion *time.Time `json:"last_connexion"`

	// UpdatedAt Date de dernière mise à jour
	UpdatedAt time.Time `json:"updated_at"`
}

// GetTrexSuiteInfosParams defines parameters for GetTrexSuiteInfos.
type GetTrexSuiteInfosParams struct {
	// Salt Salt used for the TREX Suite deployment (optional, uses default if not provided)
	Salt *string `form:"salt,omitempty" json:"salt,omitempty"`
}

// PostAuthSignInJSONRequestBody defines body for PostAuthSignIn for application/json ContentType.
type PostAuthSignInJSONRequestBody = SignInRequest

// PostAuthSignUpJSONRequestBody defines body for PostAuthSignUp for application/json ContentType.
type PostAuthSignUpJSONRequestBody = SignUpRequest

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody = CreateIdentityRequest

// AddClaimToIdentityJSONRequestBody defines body for AddClaimToIdentity for application/json ContentType.
type AddClaimToIdentityJSONRequestBody = AddClaimRequest

// CreateTokenContractJSONRequestBody defines body for CreateTokenContract for application/json ContentType.
type CreateTokenContractJSONRequestBody = CreateTokenRequest

// BurnTokenAsyncJSONRequestBody defines body for BurnTokenAsync for application/json ContentType.
type BurnTokenAsyncJSONRequestBody = BurnTokenRequest

// MintTokenAsyncJSONRequestBody defines body for MintTokenAsync for application/json ContentType.
type MintTokenAsyncJSONRequestBody = MintTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Auth existing user and return a JWT
	// (POST /auth/sign-in)
	PostAuthSignIn(c *gin.Context)
	// Create a new user and return a JWT
	// (POST /auth/sign-up)
	PostAuthSignUp(c *gin.Context)
	// Create new Identity contract and add it to the registry
	// (POST /contract/identity)
	CreateIdentity(c *gin.Context)
	// Add a claim to an identity
	// (POST /contract/identity/claims/add)
	AddClaimToIdentity(c *gin.Context)
	// Create a new Token
	// (POST /contract/token)
	CreateTokenContract(c *gin.Context)
	// Withdraw the given amount for the userId in the sharetoken
	// (POST /contract/token/burn)
	BurnTokenAsync(c *gin.Context)
	// Register the given amount for the userId in the sharetoken
	// (POST /contract/token/mint)
	MintTokenAsync(c *gin.Context)
	// Get informations from contract Token
	// (GET /contract/token/{tokenAddress}/infos)
	GetTokenInfos(c *gin.Context, tokenAddress string)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Add a payment
	// (POST /payments/add)
	PaymentAdd(c *gin.Context)
	// Configure the Authority contract with the implementations addresses
	// (POST /trex/init/authority/configure)
	ConfigureAuthority(c *gin.Context)
	// Deploy identity factory
	// (POST /trex/init/contract/factory/identity)
	DeployIdentityFactory(c *gin.Context)
	// Deploy TREX factory
	// (POST /trex/init/contract/factory/trexFactory)
	DeployAndInitTrexFactoryAsync(c *gin.Context)
	// Deploy all contracts implementations
	// (POST /trex/init/implementations)
	DeployAllImplementationsAsync(c *gin.Context)
	// Deploy the TREX Suite contracts
	// (POST /trex/init/suite/deploy)
	DeployTrexSuiteAsync(c *gin.Context)
	// Get deployed TREX Suite information
	// (GET /trex/suite)
	GetTrexSuiteInfos(c *gin.Context, params GetTrexSuiteInfosParams)
	// GetUserById
	// (GET /user/{userId})
	GetUserById(c *gin.Context, userId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthSignIn operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthSignIn(c)
}

// PostAuthSignUp operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthSignUp(c)
}

// CreateIdentity operation middleware
func (siw *ServerInterfaceWrapper) CreateIdentity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIdentity(c)
}

// AddClaimToIdentity operation middleware
func (siw *ServerInterfaceWrapper) AddClaimToIdentity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddClaimToIdentity(c)
}

// CreateTokenContract operation middleware
func (siw *ServerInterfaceWrapper) CreateTokenContract(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTokenContract(c)
}

// BurnTokenAsync operation middleware
func (siw *ServerInterfaceWrapper) BurnTokenAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BurnTokenAsync(c)
}

// MintTokenAsync operation middleware
func (siw *ServerInterfaceWrapper) MintTokenAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MintTokenAsync(c)
}

// GetTokenInfos operation middleware
func (siw *ServerInterfaceWrapper) GetTokenInfos(c *gin.Context) {

	var err error

	// ------------- Path parameter "tokenAddress" -------------
	var tokenAddress string

	err = runtime.BindStyledParameterWithOptions("simple", "tokenAddress", c.Param("tokenAddress"), &tokenAddress, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tokenAddress: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTokenInfos(c, tokenAddress)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// PaymentAdd operation middleware
func (siw *ServerInterfaceWrapper) PaymentAdd(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PaymentAdd(c)
}

// ConfigureAuthority operation middleware
func (siw *ServerInterfaceWrapper) ConfigureAuthority(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfigureAuthority(c)
}

// DeployIdentityFactory operation middleware
func (siw *ServerInterfaceWrapper) DeployIdentityFactory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployIdentityFactory(c)
}

// DeployAndInitTrexFactoryAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployAndInitTrexFactoryAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployAndInitTrexFactoryAsync(c)
}

// DeployAllImplementationsAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployAllImplementationsAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployAllImplementationsAsync(c)
}

// DeployTrexSuiteAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployTrexSuiteAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployTrexSuiteAsync(c)
}

// GetTrexSuiteInfos operation middleware
func (siw *ServerInterfaceWrapper) GetTrexSuiteInfos(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrexSuiteInfosParams

	// ------------- Optional query parameter "salt" -------------

	err = runtime.BindQueryParameter("form", true, false, "salt", c.Request.URL.Query(), &params.Salt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter salt: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTrexSuiteInfos(c, params)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserById(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/sign-in", wrapper.PostAuthSignIn)
	router.POST(options.BaseURL+"/auth/sign-up", wrapper.PostAuthSignUp)
	router.POST(options.BaseURL+"/contract/identity", wrapper.CreateIdentity)
	router.POST(options.BaseURL+"/contract/identity/claims/add", wrapper.AddClaimToIdentity)
	router.POST(options.BaseURL+"/contract/token", wrapper.CreateTokenContract)
	router.POST(options.BaseURL+"/contract/token/burn", wrapper.BurnTokenAsync)
	router.POST(options.BaseURL+"/contract/token/mint", wrapper.MintTokenAsync)
	router.GET(options.BaseURL+"/contract/token/:tokenAddress/infos", wrapper.GetTokenInfos)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/payments/add", wrapper.PaymentAdd)
	router.POST(options.BaseURL+"/trex/init/authority/configure", wrapper.ConfigureAuthority)
	router.POST(options.BaseURL+"/trex/init/contract/factory/identity", wrapper.DeployIdentityFactory)
	router.POST(options.BaseURL+"/trex/init/contract/factory/trexFactory", wrapper.DeployAndInitTrexFactoryAsync)
	router.POST(options.BaseURL+"/trex/init/implementations", wrapper.DeployAllImplementationsAsync)
	router.POST(options.BaseURL+"/trex/init/suite/deploy", wrapper.DeployTrexSuiteAsync)
	router.GET(options.BaseURL+"/trex/suite", wrapper.GetTrexSuiteInfos)
	router.GET(options.BaseURL+"/user/:userId", wrapper.GetUserById)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb/XLbuBF/FQzameZmaIvyt/VXFTt38d0ll4ntubY3mRuYXIlIQIABQNtqRu/SP6/P",
	"kRfrAOCnBFLyhxx32vyRhCKAXexvd7Ef4BcciTQTHLhWePQFqyiBlNj/jt+dvQeVCa7APGZSZCA1Bfsy",
	"JpqYf3nOGLligEda5hDg2y1BMroViRimwLfgVkuypcnUTvqoBMcjHIiUakgzPcPzeYBTUIpMLQ09ywCP",
	"sNKS8ql9KeFzTiXEePRbNfBDUA4UVx8h0nge4HEcnzBC0/fwOQellxmOzNsLkdHIsg8qkjTT1DJ0kQDS",
	"5hUSE6QTQHYwegHb0+0AHaKJkOinv598hwMMtyTNzHYPKyYo1zAFabjIFciz2BCoxg1D82d58MLeiplB",
	"k8/+fdbIEMZ+meDRb1/wnyVM8Aj/aVCDOigQHTThnAddePatcHH7mqjkLUnBsr/A24d5gF/mkl+IT8A7",
	"YSCpyLn2Q+DeWQzMGgppga5yyQNEOUrylHCDREo0esGFRjdAW4gYSW8fHQbYDcIjHIvcqGbFKs/TKweU",
	"Fh0sxLEEVVG2ylAx0ySGw9vhzu7e/sHh0XFIrqIYJl3PNf1Srw39T8BPBNeSRHrsiPZzVGimnYiiYuaj",
	"cbSgjV72rNSCEkGfcjbgf47aeSL4hE5zCeNcJ0JSPXu2fFrBn4ImlCmPEd1BYR5dVcw6GRMS5KVkyyyc",
	"UgmRRozyT8aKmiwgwdErnYBUEeEtfhKtMzUaDBRkglGyDeWobSoGxYYGD2OaG4F7BWbeDMz4XpGdxcA1",
	"1bOVtkMqc7EkfXZyIoFoKFfsPrKMocnZiYg7OC8GIHPalsxTfg1KC9lkfm9vp/+0Wl7avENnp32rOmmv",
	"PNmau6horiOVpzfNkvYZnwjVaZ2Wzf5Tjl+dQkRT4rGPt/YMMnKN3RDVkumRDyjrjt96Fdj82jobWkp7",
	"eR7uHh7t7g7DcH89p2+pBI0NdCP17Ty9IdyLURvIJzcsWpC/y8EeWZnGiNZ+pumvnYNb/bc32JCEKxIZ",
	"2ubo8bOTEJVUilRPWDw29uFof4/sQgg7w73jHTjePRrCcTjZI7t70cH+8cHxwUG8O5lAHEUHO9HwEIZw",
	"GB7uDMPh8XB47GNvQ24owDeEMeiPrtyQRSx8ZB4zvFrUj0VWgwWnuQhgrxs941RTwug/K1f6PYm0kN/E",
	"oy6GMh32+uONtka9bKpwm1EJamydbB3YEw1bmqbg0ycJEwkqqRb0B9/eN0asq7Z0qTyHXOl6W7SL9YLG",
	"JnyAvaFcP27SlFKuv03SZCj/P2m6U9LUgP85JiPndMrPulUTUkJZq+CBCdfir8XjdiRS3FAuN9yDbUaU",
	"uhGyXTvBKs9AKogk6OYq1eBVkJTkqgk+AModPr30K7fXI/vLbOOyn+SMldFlvdSYa8Fn6GeYfP3jWsLT",
	"gVaxE6yPn5HS88PPvnyULH5DHizAVRLiT42XkhVbC/UmG/7U5a61ArfR+xUK7NyNlgm6M603M3QOUS6p",
	"nqHy9F9aXM3SK8H8y7t3PQTOL/xnoibsPM8yNuuqa2vCkLIjGlHCC8pNLFDEBq2QALuStefPXWsf1Y4b",
	"etZmua0gPutuJHtLFvQLv4KEsMlFHR97FHmMGFUuQmqMQxlIs3mIjba5dar4v87BqIZU3eUUrbZApCQz",
	"89xp5+MnsvEitbxLDE3jRnzcMOdUxDkj8kSkGaOER2D2sHJnS7M2sctWzaXaJeX6YA/7PFOXMZ7XhlgY",
	"YUpufwY+1YlJNrvi0t95f31myaBf0il6LXIFKyksZY84aFhag7oHn6YN1hJq6oTX6CTcnudUQ1cBpWpS",
	"qfcwpUrL2Z0zwbpM8ohLnGshi17iHVdaltzd11CEdWRp5g3KFcTV+Xnx/tXfkJUxiiFjYpYCb5tDOrO+",
	"75wwPdzZ7UyI1qqWNZjUEm6LisA9tqhlrjTEZ0rlIO8P/oJKW8EFVRa9pBjdQHdyFHiV1G8hTZF4zaH2",
	"70umYP5PDNJv14ocquH1+dMC3ZVWzxMiXX3VpPFUd0YUDyntIZ0Q3TgGW+zd0zEfr86Sl2pZbQn65H9Z",
	"lGUWnJBzYb8Tj82dEmtXKJJf/+3EHefIKKaG1s52wp2DrXC4FQ4vhjujMByF4T+aSUvvIVnlX23ar8zP",
	"hjj7S64po4poyNu1xHunaV2njEjt7hjofsJrJHXUU4o9O0U5p59z6F196DtmGVH690hwDrd2rS6kGEEx",
	"SE6//iFteFCM94E1DC+G+6PdXrAW76Usl/qyeKX21AylVAH6+i/0USwI9AEK5DvWa4zr5Leh5y22ly3F",
	"HEFFEnJuPK+zkysgEuQ410n99H3J34+/mrTC+mmzkntb82ryLTw3C1M+8ZT/3lBuAgo0fneGbqhOUAKE",
	"6QRFCUSfzDJUu2CHiehTlBDK0RsaSaFAXtMIzDwc4GuQyq033A63QwOPyICTjOIR3t0Ot3dtDUAndj8D",
	"kutkoOiUb1FXMRauOlI5krMYj/A7obTZtCvvYCdsUPqliGeuCcQ1uKoqyTJGIzt14O4olRehVh1s7erY",
	"vI2p0Tz7gysyWOZ3wuGjEy9rGHObzzfhMY6z6iypPIpAKaNiNi/ZC0OPpfNrwmiMZLklM+64y8kRJoHE",
	"MwS3VGl3rKs8TYmJCLARvntD+dR1cgg3K+tcckSQUz13N+w3bEDFH8wKDXzzbD18L7MN4ltX4L4Bvo3C",
	"1nPD14UqiCAON3eBt8z9BlWa3Ylx+0rAhjD238ZYC+twY0x0Y/7LT34cDArl/PrKjYGExDGiuqywyToW",
	"LsGpvbNtPVapeQVQB3ADG2KrAYnjbgzLG4sXYsM4Ll4BfWIEl25mroPdOI4RKa6baoEIb9ae7gtPlRb2",
	"GdVFs1u1Uctq9Taf2IX6bqp4cLEDijwcYuMU9/3OU4PkhCETvoBEIKWQfV6xyttWIOkQ88E4uMplD5bV",
	"jcuxmvFoQzAu3epdC8Sdx7OsZqOmC7zU5BxN6B57690MrKMWv1KdxJLcWBc8pdfAy859WRByVzoQdZeO",
	"VUIk6IerjxFLt/pUvedNqs/S/Yb/HfVZ7u3fU31cAQvkU6vPF/tPUc6fD2hZDp6CR5t+AN3o1piMTZIU",
	"NEhle7EmWbNZXNkeGuHm6nhRJ4KGkBdT5w8bPMhb1wtXH+E/gEZGLiahto2libTVmCIAu88R4JLoPjm/",
	"diP8UljB8Otmim7pZcRWn1cEcu/cqHEcr0W3GG6izwceqS5IKphsiLKgoAqpaQm3A8qptgmkvd9v1Nld",
	"+e8Jh5a+CsCbjPO7v0HoULbH9UgrnGEFx7mD45Uvwim3YD1NtY9a5W0hyPZR04yBgaiwjKJpBarLHmh1",
	"d3EJ08oxTVyhfo3s8dTGcwu3IDcJ7uqrl/8tGDvRVckImlTCezBuC/2nPujGPDYivahn1HHKtwkWihAG",
	"KUPIKzLb17u/uBZMZqWEGDtrz3j+EiKMVb5CLfqIe4hM5VTDwCVvq+RVNbafv5gWmsSVxNaQkOtoblnB",
	"NMXlfugL39p9/6UQbuGmxHpNbfRC2BmEBWa0QjFMSM40ohPEhUaZFNc0hvg7uwk8wp9zsLZTBIlFc/gb",
	"BYNtifjyh3rPjTAQSdCSwrW3Lrvn6dPWqxiZTETOa7G6gN/K4SFx1A+2O+hqHMjPtle50BZa0ieTbgy+",
	"uKRj3qdSlwrky5n9tLlXmS7dlx6lDrTzhOrr6O4MYeWNn42qSfFRgL9Ab8FcvyK/iFlDgiU29ruCD3PX",
	"8DN4+yR6CtfARGZN0I3CAc4lK9p6o8GAiYiwRCg9OgqPQnsJdiGGlyLOy++A6qlqNBiQjG5rYZKW7Yk0",
	"T4PrITYyLnj8UmLnRBNUz7YR2XhuOLHGrxeSxK5TW/1UhfvzD/P/BAAA///zSP1kt0AAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
