// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// APIResponse defines model for APIResponse.
type APIResponse struct {
	Data    interface{} `json:",omitempty"`
	Message string      `json:"message"`
}

// AddClaimRequest defines model for AddClaimRequest.
type AddClaimRequest struct {
	// ClaimTopic The topic of the claim (e.g., 7 for KYC)
	ClaimTopic int `json:"claimTopic"`
	UserId     int `json:"userId"`
}

// AddClaimResponse defines model for AddClaimResponse.
type AddClaimResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// BurnTokenRequest defines model for BurnTokenRequest.
type BurnTokenRequest struct {
	// Amount The amount of tokens to burn, in human format (not wei). The request is refused rather than approximated when the amount cannot be converted exactly: it must carry at most 15 significant digits, stay below 9007199254740992, and have no more decimals than the token declares. The result is written to an immutable ledger, so an amount that merely resembles the one requested is worse than a rejection.
	Amount float64 `json:"amount"`

	// To The address to burn the tokens to
	To string `json:"to"`

	// TokenContractAddress The address of the token contract
	TokenContractAddress string `json:"tokenContractAddress"`
}

// BurnTokenResponse defines model for BurnTokenResponse.
type BurnTokenResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// ConfigureAuthorityResponse defines model for ConfigureAuthorityResponse.
type ConfigureAuthorityResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// ContractDetails defines model for ContractDetails.
type ContractDetails struct {
	// Address The address of the contract
	Address string `json:"address"`

	// ExplorerUrl Direct link to the contract on Etherscan
	ExplorerUrl *string `json:"explorerUrl,omitempty"`

	// Name The name/type of the contract
	Name string `json:"name"`
}

// CreateIdentityRequest defines model for CreateIdentityRequest.
type CreateIdentityRequest struct {
	// CountryCode The country code of the investor
	CountryCode int `json:"countryCode"`

	// UserId The user ID of the investor
	UserId int `json:"userId"`
}

// CreateIdentityResponse defines model for CreateIdentityResponse.
type CreateIdentityResponse struct {
	Data    *IdentityInfos `json:"data,omitempty"`
	Message string         `json:"message"`
}

// CreateIssuanceOrderRequest defines model for CreateIssuanceOrderRequest.
type CreateIssuanceOrderRequest struct {
	Quantity     int `json:"quantity"`
	RealEstateId int `json:"realEstateId"`
}

// CreateIssuanceOrderResponse defines model for CreateIssuanceOrderResponse.
type CreateIssuanceOrderResponse struct {
	Data    *IssuanceOrder `json:"data,omitempty"`
	Message string         `json:"message"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	// NbDecimal Number of decimals
	NbDecimal int `json:"nbDecimal"`

	// Symbol On-chain token symbol (max 50 characters)
	Symbol string `json:"symbol"`

	// TokenName Name of the token
	TokenName string `json:"tokenName"`
}

// CreateTokenResponse defines model for CreateTokenResponse.
type CreateTokenResponse struct {
	Data    *TokenInfos `json:"data,omitempty"`
	Message string      `json:"message"`
}

// IdentityInfos defines model for IdentityInfos.
type IdentityInfos struct {
	// CountryCode The country code of the investor
	CountryCode int `json:"countryCode"`

	// IdentityAddress The address of the created identity
	IdentityAddress string `json:"identityAddress"`

	// TransactionHash The hash of the transaction
	TransactionHash string `json:"transactionHash"`

	// UserId The user ID of the investor
	UserId int `json:"userId"`

	// WalletAddress The wallet address of the investor
	WalletAddress string `json:"walletAddress"`
}

// InitializeIdentityFactoryResponse defines model for InitializeIdentityFactoryResponse.
type InitializeIdentityFactoryResponse struct {
	Data    *ContractDetails `json:"data,omitempty"`
	Message string           `json:"message"`
}

// IssuanceOrder defines model for IssuanceOrder.
type IssuanceOrder struct {
	CreatedAt     time.Time  `json:"createdAt"`
	CreatedBy     int        `json:"createdBy"`
	Id            *int       `json:"id,omitempty"`
	OrderRef      string     `json:"orderRef"`
	RealEstateId  int        `json:"realEstateId"`
	StatusCode    *string    `json:"statusCode,omitempty"`
	StatusId      *int       `json:"statusId,omitempty"`
	StatusIfFinal *bool      `json:"statusIfFinal,omitempty"`
	StatusLabel   *string    `json:"statusLabel,omitempty"`
	TokenQuantity int        `json:"tokenQuantity"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
	UserId        int        `json:"userId"`
}

// JwtToken defines model for JwtToken.
type JwtToken struct {
	ExpiresAt    time.Time `json:"expiresAt"`
	RefreshToken string    `json:"refreshToken"`
	Token        string    `json:"token"`
	User         User      `json:"user"`
}

// MintTokenRequest defines model for MintTokenRequest.
type MintTokenRequest struct {
	// Amount The amount of tokens to mint, in human format (not wei). The request is refused rather than approximated when the amount cannot be converted exactly: it must carry at most 15 significant digits, stay below 9007199254740992, and have no more decimals than the token declares. The result is written to an immutable ledger, so an amount that merely resembles the one requested is worse than a rejection.
	Amount float64 `json:"amount"`

	// To The address to mint the tokens to
	To string `json:"to"`

	// TokenContractAddress The address of the token contract
	TokenContractAddress string `json:"tokenContractAddress"`
}

// MintTokenResponse defines model for MintTokenResponse.
type MintTokenResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// RealEstate defines model for RealEstate.
type RealEstate struct {
	// Active is estate active
	Active *bool `json:"active,omitempty"`

	// Address Full postal address. Served only to a MANAGER or an ADMIN; the public answer carries RealEstateLocation instead.
	Address *RealEstateAddress `json:"address,omitempty"`

	// Configuration Amounts and share counts are carried as decimal strings. JSON has a single numeric type, which most parsers read as a binary double: 199.99 comes back as 199.99001, and any integer above 2^53 is silently rounded. The string is a transport format, not the type of the data.
	Configuration *RealEstateConfiguration `json:"configuration,omitempty"`

	// ContractAddress Address of estate on blockchain (token)
	ContractAddress *string    `json:"contract_address,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	Description     *string    `json:"description,omitempty"`
	EstateType      *string    `json:"estate_type,omitempty"`
	EstateTypeId    *int       `json:"estate_type_id,omitempty"`
	Id              int        `json:"id"`
	Imageurl        *string    `json:"imageurl,omitempty"`

	// Issuer The legal vehicle issuing the shares.
	Issuer *RealEstateIssuer `json:"issuer,omitempty"`

	// Location Coarse location, safe to expose publicly. The street, the postal code and the coordinates are held back: they pinpoint a tokenized asset.
	Location      *RealEstateLocation      `json:"location,omitempty"`
	Media         *[]RealEstateMedia       `json:"media,omitempty"`
	Progression   *RealEstateProgression   `json:"progression,omitempty"`
	PublishedAt   *time.Time               `json:"published_at,omitempty"`
	Specification *RealEstateSpecification `json:"specification,omitempty"`

	// Status Lifecycle status code (draft, in_review, published, fundraising, funded, closed, cancelled)
	Status   *string `json:"status,omitempty"`
	StatusId *int    `json:"status_id,omitempty"`
	Title    *string `json:"title,omitempty"`

	// Token The ERC-3643 contract of the asset. Absent means not tokenized yet.
	Token     *RealEstateToken `json:"token,omitempty"`
	UpdatedAt *time.Time       `json:"updated_at,omitempty"`
}

// RealEstateAddress Full postal address. Served only to a MANAGER or an ADMIN; the public answer carries RealEstateLocation instead.
type RealEstateAddress struct {
	City string `json:"city"`

	// CountryCode ISO 3166-1 alpha-2
	CountryCode string `json:"country_code"`

	// Latitude Exact decimal, NUMERIC(9,6). Set together with longitude or not at all.
	Latitude *string `json:"latitude,omitempty"`

	// Longitude Exact decimal, NUMERIC(9,6). Set together with latitude or not at all.
	Longitude        *string `json:"longitude,omitempty"`
	PostalCode       string  `json:"postal_code"`
	Region           *string `json:"region,omitempty"`
	Street           string  `json:"street"`
	StreetComplement *string `json:"street_complement,omitempty"`
}

// RealEstateAddressPatch Address fields to change. Same fields as RealEstateAddress, none required: what is not sent keeps its current value.
type RealEstateAddressPatch struct {
	City *string `json:"city,omitempty"`

	// CountryCode ISO 3166-1 alpha-2
	CountryCode      *string `json:"country_code,omitempty"`
	Latitude         *string `json:"latitude,omitempty"`
	Longitude        *string `json:"longitude,omitempty"`
	PostalCode       *string `json:"postal_code,omitempty"`
	Region           *string `json:"region,omitempty"`
	Street           *string `json:"street,omitempty"`
	StreetComplement *string `json:"street_complement,omitempty"`
}

// RealEstateConfiguration Amounts and share counts are carried as decimal strings. JSON has a single numeric type, which most parsers read as a binary double: 199.99 comes back as 199.99001, and any integer above 2^53 is silently rounded. The string is a transport format, not the type of the data.
type RealEstateConfiguration struct {
	// CurrencyCode ISO 4217
	CurrencyCode           *string `json:"currency_code,omitempty"`
	PaymentFrequency       *int    `json:"payment_frequency,omitempty"`
	PaymentFrequencyType   *string `json:"payment_frequency_type,omitempty"`
	PaymentFrequencyTypeId *int    `json:"payment_frequency_type_id,omitempty"`

	// PricePerShare Exact decimal amount, NUMERIC(20,8)
	PricePerShare *string `json:"price_per_share,omitempty"`

	// TotalShares Exact integer count, NUMERIC(20,0)
	TotalShares *string `json:"total_shares,omitempty"`

	// TotalValuation total_shares x price_per_share, computed by the database
	TotalValuation *string  `json:"total_valuation,omitempty"`
	Yield          *float32 `json:"yield,omitempty"`
}

// RealEstateConfigurationInput Share configuration. total_valuation is absent on purpose: the database computes it from total_shares x price_per_share and refuses any write, which is what keeps the three values from ever disagreeing.
type RealEstateConfigurationInput struct {
	// CompartmentRef Luxembourg compartment reference, unique across assets
	CompartmentRef *string `json:"compartment_ref,omitempty"`

	// CurrencyCode ISO 4217, defaults to EUR
	CurrencyCode *string `json:"currency_code,omitempty"`

	// EntryFeeRate Percentage between 0 and 100
	EntryFeeRate *string `json:"entry_fee_rate,omitempty"`

	// ExitFeeRate Percentage between 0 and 100
	ExitFeeRate   *string `json:"exit_fee_rate,omitempty"`
	MaxInvestment *string `json:"max_investment,omitempty"`

	// MgmtFeeRate Percentage between 0 and 100
	MgmtFeeRate            *string `json:"mgmt_fee_rate,omitempty"`
	MinInvestment          *string `json:"min_investment,omitempty"`
	PaymentFrequency       *int    `json:"payment_frequency,omitempty"`
	PaymentFrequencyTypeId *int    `json:"payment_frequency_type_id,omitempty"`

	// PricePerShare Exact positive decimal, NUMERIC(20,8)
	PricePerShare string `json:"price_per_share"`

	// TotalShares Exact positive integer, NUMERIC(20,0)
	TotalShares string `json:"total_shares"`

	// Yield Annual yield in percent
	Yield *string `json:"yield,omitempty"`
}

// RealEstateConfigurationPatch Share configuration fields to change. total_shares and price_per_share are optional here, unlike on a create, because they already have a value to keep.
type RealEstateConfigurationPatch struct {
	CompartmentRef         *string `json:"compartment_ref,omitempty"`
	CurrencyCode           *string `json:"currency_code,omitempty"`
	EntryFeeRate           *string `json:"entry_fee_rate,omitempty"`
	ExitFeeRate            *string `json:"exit_fee_rate,omitempty"`
	MaxInvestment          *string `json:"max_investment,omitempty"`
	MgmtFeeRate            *string `json:"mgmt_fee_rate,omitempty"`
	MinInvestment          *string `json:"min_investment,omitempty"`
	PaymentFrequency       *int    `json:"payment_frequency,omitempty"`
	PaymentFrequencyTypeId *int    `json:"payment_frequency_type_id,omitempty"`
	PricePerShare          *string `json:"price_per_share,omitempty"`
	TotalShares            *string `json:"total_shares,omitempty"`
	Yield                  *string `json:"yield,omitempty"`
}

// RealEstateIssuer The legal vehicle issuing the shares.
type RealEstateIssuer struct {
	// CountryCode ISO 3166-1 alpha-2
	CountryCode *string `json:"country_code,omitempty"`
	Id          *int    `json:"id,omitempty"`
	LegalForm   *string `json:"legal_form,omitempty"`
	Name        *string `json:"name,omitempty"`
	Status      *string `json:"status,omitempty"`
}

// RealEstateLocation Coarse location, safe to expose publicly. The street, the postal code and the coordinates are held back: they pinpoint a tokenized asset.
type RealEstateLocation struct {
	City *string `json:"city,omitempty"`

	// CountryCode ISO 3166-1 alpha-2
	CountryCode *string `json:"country_code,omitempty"`
}

// RealEstateMedia defines model for RealEstateMedia.
type RealEstateMedia struct {
	AltText *string `json:"alt_text,omitempty"`
	Id      *int    `json:"id,omitempty"`
	IsCover *bool   `json:"is_cover,omitempty"`

	// MediaType image, video, floorplan or virtual_tour
	MediaType *string `json:"media_type,omitempty"`
	Position  *int    `json:"position,omitempty"`
	Url       *string `json:"url,omitempty"`
}

// RealEstateMediaInput defines model for RealEstateMediaInput.
type RealEstateMediaInput struct {
	AltText *string `json:"alt_text,omitempty"`

	// IsCover At most one media per asset may be the cover.
	IsCover *bool `json:"is_cover,omitempty"`

	// MediaType image, video, floorplan or virtual_tour. Defaults to image.
	MediaType *string `json:"media_type,omitempty"`
	Position  *int    `json:"position,omitempty"`
	Url       string  `json:"url"`
}

// RealEstatePatchRequest Partial update. Every field is optional and an omitted one is left untouched; the sections are merged field by field, except media which is replaced as a whole.
type RealEstatePatchRequest struct {
	// Address Address fields to change. Same fields as RealEstateAddress, none required: what is not sent keeps its current value.
	Address *RealEstateAddressPatch `json:"address,omitempty"`

	// Configuration Share configuration fields to change. total_shares and price_per_share are optional here, unlike on a create, because they already have a value to keep.
	Configuration *RealEstateConfigurationPatch `json:"configuration,omitempty"`
	Description   *string                       `json:"description,omitempty"`
	EstateTypeId  *int                          `json:"estate_type_id,omitempty"`
	Imageurl      *string                       `json:"imageurl,omitempty"`
	IssuerId      *int                          `json:"issuer_id,omitempty"`

	// Media Replaces the whole gallery. Send an empty array to clear it.
	Media *[]RealEstateMediaInput `json:"media,omitempty"`

	// Specification Physical description. Measures travel as decimal strings for the same reason as amounts: a surface stored as NUMERIC must not come back rounded by a JSON parser.
	Specification *RealEstateSpecificationInput `json:"specification,omitempty"`
	Title         *string                       `json:"title,omitempty"`
}

// RealEstateProgression defines model for RealEstateProgression.
type RealEstateProgression struct {
	// TokensSold Shares held by non-cancelled issuance orders. An integer, because an order quantity is an integer; only total_shares needs a string.
	TokensSold     *int     `json:"tokens_sold,omitempty"`
	TokensSoldPctg *float32 `json:"tokens_sold_pctg,omitempty"`
}

// RealEstateSpecification defines model for RealEstateSpecification.
type RealEstateSpecification struct {
	BathroomNumber *int `json:"bathroom_number,omitempty"`
	BedroomNumber  *int `json:"bedroom_number,omitempty"`
	BuildYear      *int `json:"build_year,omitempty"`

	// EnergyClass Energy performance class, A to G
	EnergyClass *string `json:"energy_class,omitempty"`

	// GesClass Greenhouse gas class, A to G
	GesClass    *string  `json:"ges_class,omitempty"`
	LotSize     *float32 `json:"lot_size,omitempty"`
	PoolSize    *float32 `json:"pool_size,omitempty"`
	SurfaceArea *float32 `json:"surface_area,omitempty"`
	TerraceSize *float32 `json:"terrace_size,omitempty"`
}

// RealEstateSpecificationInput Physical description. Measures travel as decimal strings for the same reason as amounts: a surface stored as NUMERIC must not come back rounded by a JSON parser.
type RealEstateSpecificationInput struct {
	BathroomNumber *int `json:"bathroom_number,omitempty"`
	BedroomNumber  *int `json:"bedroom_number,omitempty"`
	BuildYear      *int `json:"build_year,omitempty"`

	// EnergyClass A to G
	EnergyClass *string `json:"energy_class,omitempty"`

	// GesClass A to G
	GesClass    *string `json:"ges_class,omitempty"`
	LotSize     *string `json:"lot_size,omitempty"`
	PoolSize    *string `json:"pool_size,omitempty"`
	SurfaceArea *string `json:"surface_area,omitempty"`
	TerraceSize *string `json:"terrace_size,omitempty"`
}

// RealEstateSummary Real estate as served by the list endpoint. Deliberately excludes the street address, the media gallery, the issuer and the token: a public list must expose the strict minimum.
type RealEstateSummary struct {
	// Active is estate active
	Active *bool `json:"active,omitempty"`

	// Configuration Amounts and share counts are carried as decimal strings. JSON has a single numeric type, which most parsers read as a binary double: 199.99 comes back as 199.99001, and any integer above 2^53 is silently rounded. The string is a transport format, not the type of the data.
	Configuration *RealEstateConfiguration `json:"configuration,omitempty"`

	// ContractAddress Address of estate on blockchain (token)
	ContractAddress *string    `json:"contract_address,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	Description     *string    `json:"description,omitempty"`
	EstateType      *string    `json:"estate_type,omitempty"`
	EstateTypeId    *int       `json:"estate_type_id,omitempty"`
	Id              int        `json:"id"`
	Imageurl        *string    `json:"imageurl,omitempty"`

	// Location Coarse location, safe to expose publicly. The street, the postal code and the coordinates are held back: they pinpoint a tokenized asset.
	Location      *RealEstateLocation      `json:"location,omitempty"`
	Progression   *RealEstateProgression   `json:"progression,omitempty"`
	Specification *RealEstateSpecification `json:"specification,omitempty"`

	// Status Lifecycle status code (draft, in_review, published, fundraising, funded, closed, cancelled)
	Status   *string `json:"status,omitempty"`
	StatusId *int    `json:"status_id,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// RealEstateToken The ERC-3643 contract of the asset. Absent means not tokenized yet.
type RealEstateToken struct {
	Address   *string `json:"address,omitempty"`
	Id        *int    `json:"id,omitempty"`
	NbDecimal *int    `json:"nb_decimal,omitempty"`
	Symbol    *string `json:"symbol,omitempty"`
	TokenName *string `json:"token_name,omitempty"`
}

// RealEstateWriteRequest Whole asset in one payload. The sections are written in a single transaction, so the request either creates a complete asset or changes nothing at all.
type RealEstateWriteRequest struct {
	// Address Full postal address. Served only to a MANAGER or an ADMIN; the public answer carries RealEstateLocation instead.
	Address RealEstateAddress `json:"address"`

	// Configuration Share configuration. total_valuation is absent on purpose: the database computes it from total_shares x price_per_share and refuses any write, which is what keeps the three values from ever disagreeing.
	Configuration *RealEstateConfigurationInput `json:"configuration,omitempty"`
	Description   *string                       `json:"description,omitempty"`

	// EstateTypeId Identifier from ass.real_estate_type
	EstateTypeId *int    `json:"estate_type_id,omitempty"`
	Imageurl     *string `json:"imageurl,omitempty"`

	// IssuerId Identifier from ass.issuer, the legal vehicle issuing the shares
	IssuerId *int                    `json:"issuer_id,omitempty"`
	Media    *[]RealEstateMediaInput `json:"media,omitempty"`

	// Specification Physical description. Measures travel as decimal strings for the same reason as amounts: a surface stored as NUMERIC must not come back rounded by a JSON parser.
	Specification *RealEstateSpecificationInput `json:"specification,omitempty"`
	Title         string                        `json:"title"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignInResponse defines model for SignInResponse.
type SignInResponse struct {
	Data    *JwtToken `json:"data,omitempty"`
	Message string    `json:"message"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Password string              `json:"password"`
}

// SignUpResponse defines model for SignUpResponse.
type SignUpResponse struct {
	Data    *JwtToken `json:"data,omitempty"`
	Message string    `json:"message"`
}

// TokenDetails defines model for TokenDetails.
type TokenDetails struct {
	// Address The address of the token contract
	Address string `json:"address"`

	// Decimals The number of decimals for the token
	Decimals int `json:"decimals"`

	// ExplorerUrl Direct link to the token on Etherscan
	ExplorerUrl string `json:"explorerUrl"`

	// Name The name of the token
	Name string `json:"name"`

	// Symbol The symbol of the token
	Symbol string `json:"symbol"`

	// TotalSupply The total supply of tokens (in wei format)
	TotalSupply string `json:"totalSupply"`
}

// TokenInfos defines model for TokenInfos.
type TokenInfos struct {
	// OnbehalfTransactions A list of transactions performed on behalf of the identity
	OnbehalfTransactions *[]TxHashName `json:"OnbehalfTransactions,omitempty"`

	// Address Address of the token contract
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`

	// ModularComplianceAddr Address of the modularCompliance contract
	ModularComplianceAddr *string `json:"modularComplianceAddr,omitempty"`
	NbDecimal             int64   `json:"nbDecimal"`

	// Symbol Symbol of token
	Symbol string `json:"symbol"`

	// TokenName Name of token
	TokenName string `json:"token_name"`
}

// TrexSuiteInfos defines model for TrexSuiteInfos.
type TrexSuiteInfos struct {
	ClaimTopicsRegistry     ContractDetails `json:"claimTopicsRegistry"`
	IdentityRegistry        ContractDetails `json:"identityRegistry"`
	IdentityRegistryStorage ContractDetails `json:"identityRegistryStorage"`
	ModularCompliance       ContractDetails `json:"modularCompliance"`

	// Salt The salt used for the TREX Suite deployment
	Salt                   string          `json:"salt"`
	Token                  TokenDetails    `json:"token"`
	TrexFactory            ContractDetails `json:"trexFactory"`
	TrustedIssuersRegistry ContractDetails `json:"trustedIssuersRegistry"`
}

// TxHashName defines model for TxHashName.
type TxHashName struct {
	// OperationName The name of the operation performed
	OperationName string `json:"operationName"`

	// TransactionHash The hash of the transaction that performed the operation
	TransactionHash string `json:"transactionHash"`
}

// User defines model for User.
type User struct {
	// CreatedAt Date de création du compte
	CreatedAt time.Time `json:"created_at"`

	// Email Email de l'utilisateur
	Email openapi_types.Email `json:"email"`

	// FullName Nom complet de l'utilisateur
	FullName string `json:"full_name"`

	// Id ID unique de l'utilisateur
	Id int `json:"id"`

	// LastConnexion Date de la dernière connexion
	LastConnexion *time.Time `json:"last_connexion"`

	// UpdatedAt Date de dernière mise à jour
	UpdatedAt time.Time `json:"updated_at"`
}

// GetTrexSuiteInfosParams defines parameters for GetTrexSuiteInfos.
type GetTrexSuiteInfosParams struct {
	// Salt Salt used for the TREX Suite deployment (optional, uses default if not provided)
	Salt *string `form:"salt,omitempty" json:"salt,omitempty"`
}

// CreateIssuanceOrderJSONRequestBody defines body for CreateIssuanceOrder for application/json ContentType.
type CreateIssuanceOrderJSONRequestBody = CreateIssuanceOrderRequest

// CreateRealEstateJSONRequestBody defines body for CreateRealEstate for application/json ContentType.
type CreateRealEstateJSONRequestBody = RealEstateWriteRequest

// PatchRealEstateJSONRequestBody defines body for PatchRealEstate for application/json ContentType.
type PatchRealEstateJSONRequestBody = RealEstatePatchRequest

// PostAuthSignInJSONRequestBody defines body for PostAuthSignIn for application/json ContentType.
type PostAuthSignInJSONRequestBody = SignInRequest

// PostAuthSignUpJSONRequestBody defines body for PostAuthSignUp for application/json ContentType.
type PostAuthSignUpJSONRequestBody = SignUpRequest

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody = CreateIdentityRequest

// AddClaimToIdentityJSONRequestBody defines body for AddClaimToIdentity for application/json ContentType.
type AddClaimToIdentityJSONRequestBody = AddClaimRequest

// CreateTokenContractJSONRequestBody defines body for CreateTokenContract for application/json ContentType.
type CreateTokenContractJSONRequestBody = CreateTokenRequest

// BurnTokenAsyncJSONRequestBody defines body for BurnTokenAsync for application/json ContentType.
type BurnTokenAsyncJSONRequestBody = BurnTokenRequest

// MintTokenAsyncJSONRequestBody defines body for MintTokenAsync for application/json ContentType.
type MintTokenAsyncJSONRequestBody = MintTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new order in primary market
	// (POST /assets/real-estate/issuance/orders)
	CreateIssuanceOrder(c *gin.Context)
	// Fetch a order in primary market
	// (GET /assets/real-estate/issuance/orders/{orderRef})
	FetchIssuanceOrder(c *gin.Context, orderRef string)
	// Create a real estate
	// (POST /assets/real-estates)
	CreateRealEstate(c *gin.Context)
	// Get all real estates
	// (GET /assets/real-estates/active)
	GetActiveRealEstates(c *gin.Context)
	// Delete a real estate
	// (DELETE /assets/real-estates/{id})
	DeleteRealEstate(c *gin.Context, id int)
	// Get one real estate
	// (GET /assets/real-estates/{id})
	GetRealEstateById(c *gin.Context, id int)
	// Update a real estate
	// (PATCH /assets/real-estates/{id})
	PatchRealEstate(c *gin.Context, id int)
	// Auth existing user and return a JWT
	// (POST /auth/sign-in)
	PostAuthSignIn(c *gin.Context)
	// Create a new user and return a JWT
	// (POST /auth/sign-up)
	PostAuthSignUp(c *gin.Context)
	// Create new Identity contract and add it to the registry
	// (POST /contract/identity)
	CreateIdentity(c *gin.Context)
	// Add a claim to an identity
	// (POST /contract/identity/claims/add)
	AddClaimToIdentity(c *gin.Context)
	// Create a new Token
	// (POST /contract/token)
	CreateTokenContract(c *gin.Context)
	// Withdraw the given amount for the userId in the sharetoken
	// (POST /contract/token/burn)
	BurnTokenAsync(c *gin.Context)
	// Register the given amount for the userId in the sharetoken
	// (POST /contract/token/mint)
	MintTokenAsync(c *gin.Context)
	// Get informations from contract Token
	// (GET /contract/token/{tokenAddress}/infos)
	GetTokenInfos(c *gin.Context, tokenAddress string)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Add a payment
	// (POST /payments/add)
	PaymentAdd(c *gin.Context)
	// Configure the Authority contract with the implementations addresses
	// (POST /trex/init/authority/configure)
	ConfigureAuthority(c *gin.Context)
	// Deploy identity factory
	// (POST /trex/init/contract/factory/identity)
	DeployIdentityFactory(c *gin.Context)
	// Deploy TREX factory
	// (POST /trex/init/contract/factory/trexFactory)
	DeployAndInitTrexFactoryAsync(c *gin.Context)
	// Deploy all contracts implementations
	// (POST /trex/init/implementations)
	DeployAllImplementationsAsync(c *gin.Context)
	// Deploy the TREX Suite contracts
	// (POST /trex/init/suite/deploy)
	DeployTrexSuiteAsync(c *gin.Context)
	// Get deployed TREX Suite information
	// (GET /trex/suite)
	GetTrexSuiteInfos(c *gin.Context, params GetTrexSuiteInfosParams)
	// GetUserById
	// (GET /user/{userId})
	GetUserById(c *gin.Context, userId int64)
	// Save a real estate in favoris for one user
	// (DELETE /users/{userId}/favorites/real-estates/{realEstateId})
	RemoveFavoritesRealEstateForUser(c *gin.Context, userId int, realEstateId int)
	// Save a real estate in favoris for one user
	// (POST /users/{userId}/favorites/real-estates/{realEstateId})
	AddFavoritesRealEstateForUser(c *gin.Context, userId int, realEstateId int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateIssuanceOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateIssuanceOrder(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIssuanceOrder(c)
}

// FetchIssuanceOrder operation middleware
func (siw *ServerInterfaceWrapper) FetchIssuanceOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderRef" -------------
	var orderRef string

	err = runtime.BindStyledParameterWithOptions("simple", "orderRef", c.Param("orderRef"), &orderRef, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderRef: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FetchIssuanceOrder(c, orderRef)
}

// CreateRealEstate operation middleware
func (siw *ServerInterfaceWrapper) CreateRealEstate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRealEstate(c)
}

// GetActiveRealEstates operation middleware
func (siw *ServerInterfaceWrapper) GetActiveRealEstates(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActiveRealEstates(c)
}

// DeleteRealEstate operation middleware
func (siw *ServerInterfaceWrapper) DeleteRealEstate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRealEstate(c, id)
}

// GetRealEstateById operation middleware
func (siw *ServerInterfaceWrapper) GetRealEstateById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRealEstateById(c, id)
}

// PatchRealEstate operation middleware
func (siw *ServerInterfaceWrapper) PatchRealEstate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchRealEstate(c, id)
}

// PostAuthSignIn operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthSignIn(c)
}

// PostAuthSignUp operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthSignUp(c)
}

// CreateIdentity operation middleware
func (siw *ServerInterfaceWrapper) CreateIdentity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIdentity(c)
}

// AddClaimToIdentity operation middleware
func (siw *ServerInterfaceWrapper) AddClaimToIdentity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddClaimToIdentity(c)
}

// CreateTokenContract operation middleware
func (siw *ServerInterfaceWrapper) CreateTokenContract(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTokenContract(c)
}

// BurnTokenAsync operation middleware
func (siw *ServerInterfaceWrapper) BurnTokenAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BurnTokenAsync(c)
}

// MintTokenAsync operation middleware
func (siw *ServerInterfaceWrapper) MintTokenAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MintTokenAsync(c)
}

// GetTokenInfos operation middleware
func (siw *ServerInterfaceWrapper) GetTokenInfos(c *gin.Context) {

	var err error

	// ------------- Path parameter "tokenAddress" -------------
	var tokenAddress string

	err = runtime.BindStyledParameterWithOptions("simple", "tokenAddress", c.Param("tokenAddress"), &tokenAddress, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tokenAddress: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTokenInfos(c, tokenAddress)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// PaymentAdd operation middleware
func (siw *ServerInterfaceWrapper) PaymentAdd(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PaymentAdd(c)
}

// ConfigureAuthority operation middleware
func (siw *ServerInterfaceWrapper) ConfigureAuthority(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfigureAuthority(c)
}

// DeployIdentityFactory operation middleware
func (siw *ServerInterfaceWrapper) DeployIdentityFactory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployIdentityFactory(c)
}

// DeployAndInitTrexFactoryAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployAndInitTrexFactoryAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployAndInitTrexFactoryAsync(c)
}

// DeployAllImplementationsAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployAllImplementationsAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployAllImplementationsAsync(c)
}

// DeployTrexSuiteAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployTrexSuiteAsync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployTrexSuiteAsync(c)
}

// GetTrexSuiteInfos operation middleware
func (siw *ServerInterfaceWrapper) GetTrexSuiteInfos(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrexSuiteInfosParams

	// ------------- Optional query parameter "salt" -------------

	err = runtime.BindQueryParameter("form", true, false, "salt", c.Request.URL.Query(), &params.Salt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter salt: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTrexSuiteInfos(c, params)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserById(c, userId)
}

// RemoveFavoritesRealEstateForUser operation middleware
func (siw *ServerInterfaceWrapper) RemoveFavoritesRealEstateForUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "realEstateId" -------------
	var realEstateId int

	err = runtime.BindStyledParameterWithOptions("simple", "realEstateId", c.Param("realEstateId"), &realEstateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter realEstateId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveFavoritesRealEstateForUser(c, userId, realEstateId)
}

// AddFavoritesRealEstateForUser operation middleware
func (siw *ServerInterfaceWrapper) AddFavoritesRealEstateForUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "realEstateId" -------------
	var realEstateId int

	err = runtime.BindStyledParameterWithOptions("simple", "realEstateId", c.Param("realEstateId"), &realEstateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter realEstateId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddFavoritesRealEstateForUser(c, userId, realEstateId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/assets/real-estate/issuance/orders", wrapper.CreateIssuanceOrder)
	router.GET(options.BaseURL+"/assets/real-estate/issuance/orders/:orderRef", wrapper.FetchIssuanceOrder)
	router.POST(options.BaseURL+"/assets/real-estates", wrapper.CreateRealEstate)
	router.GET(options.BaseURL+"/assets/real-estates/active", wrapper.GetActiveRealEstates)
	router.DELETE(options.BaseURL+"/assets/real-estates/:id", wrapper.DeleteRealEstate)
	router.GET(options.BaseURL+"/assets/real-estates/:id", wrapper.GetRealEstateById)
	router.PATCH(options.BaseURL+"/assets/real-estates/:id", wrapper.PatchRealEstate)
	router.POST(options.BaseURL+"/auth/sign-in", wrapper.PostAuthSignIn)
	router.POST(options.BaseURL+"/auth/sign-up", wrapper.PostAuthSignUp)
	router.POST(options.BaseURL+"/contract/identity", wrapper.CreateIdentity)
	router.POST(options.BaseURL+"/contract/identity/claims/add", wrapper.AddClaimToIdentity)
	router.POST(options.BaseURL+"/contract/token", wrapper.CreateTokenContract)
	router.POST(options.BaseURL+"/contract/token/burn", wrapper.BurnTokenAsync)
	router.POST(options.BaseURL+"/contract/token/mint", wrapper.MintTokenAsync)
	router.GET(options.BaseURL+"/contract/token/:tokenAddress/infos", wrapper.GetTokenInfos)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/payments/add", wrapper.PaymentAdd)
	router.POST(options.BaseURL+"/trex/init/authority/configure", wrapper.ConfigureAuthority)
	router.POST(options.BaseURL+"/trex/init/contract/factory/identity", wrapper.DeployIdentityFactory)
	router.POST(options.BaseURL+"/trex/init/contract/factory/trexFactory", wrapper.DeployAndInitTrexFactoryAsync)
	router.POST(options.BaseURL+"/trex/init/implementations", wrapper.DeployAllImplementationsAsync)
	router.POST(options.BaseURL+"/trex/init/suite/deploy", wrapper.DeployTrexSuiteAsync)
	router.GET(options.BaseURL+"/trex/suite", wrapper.GetTrexSuiteInfos)
	router.GET(options.BaseURL+"/user/:userId", wrapper.GetUserById)
	router.DELETE(options.BaseURL+"/users/:userId/favorites/real-estates/:realEstateId", wrapper.RemoveFavoritesRealEstateForUser)
	router.POST(options.BaseURL+"/users/:userId/favorites/real-estates/:realEstateId", wrapper.AddFavoritesRealEstateForUser)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x96XIct9bYq6A6qYpc1ZyFiyTO/RNam3mvtUSkykkshYXpPjMDCw20ATTJuSpW5SHy",
	"APl58xx+kzzJVzhAr4OehSIpua79w9R0o7Gc/RycA3yJEpnlUoAwOpp8iXSygIziP0/enb4HnUuhwf7M",
	"lcxBGQb4MqWG2r+i4JxOOUQTowqIo+s9SXO2l8gU5iD24NooumfoHD/6TUsRTaJYZsxAlptldHMTRxlo",
	"Tec4hlnmEE0ibRQTc3yp4PeCKUijya9Vw09x2VBOf4PERDdxdJKmzzhl2Xv4vQBtViec2LfnMmcJTh90",
	"olhuGE7ofAHE2FdEzohZAMHG5BEM5oOYPCEzqcg//sezH6I4gmua5Xa5T6pJMGFgDsrOotCgTlM7QNVu",
	"PLL/rTburM1/GTfnuX6dNWYo529n0eTXL9F/VjCLJtF/GtZIHXqMDpvovIn78Lmuh/Prn6hevKEZ4PQ7",
	"c/t0E0c/Fkqcy88getFAM1kIE0aBe4c4sH1oYiSZFkrEhAmyKDIqLCYyasgjIQ25AvbDgNgPlRuNME0U",
	"zAoNKVHULEARs6CC0DxX8ppl1EBKrhYgEMd+tIQK29kUSCLFJSjbBq5pYvhyQpghWaFtI6WWhBqSSW3I",
	"+IhoNhdsxhIqDEnZnBkdE23okkyByytyPBo9GR8f7x8dPjkcHR/vx4SKlCzoJRAhSSYVkBQSllGu3RQN",
	"UuBnEPY5pwp0uTJdcFzYlWLG2KlLQgVhWVYYy3eEQzoHFRONz/2izMLOFRTwpe0CsikHjYNIUYELUuxX",
	"Kg0eTkSBxSWTYtAkdUvCg6dP4shBP5pEqSwsz8dRRq9ZVmTRpLPicRxlTLhXNfGLIps6RjGyhwTSVIGu",
	"MF/DxT5qzikaXY/3Dw6PHj95ejyi0ySFWd/vKO7KFTv+ZxDPpDCKJubEDbp+Rl4yOCQl/ss7m1FHGgSn",
	"h1CLSw4KCYcG+32P0uGZFDM2LxScFGYhFTPL73aeCPjnYCjjOiDEdiCYOycV20/OpQL1QfHVKTxnChJD",
	"OBOfLRc1p0CkIC+sWNQJFa35LIzJ9WQ41JBLzugAylYDJod+QcOvm7SwAA8CzL4Z2vZrQXaagjDMLDfy",
	"Dq3YBYcM8ckzBdRA2WO/yWAZTS2fybRn5r4BsdZOOXkmLkEbqZqTPzzcX28trHZt35HT5+t6ddDeaFk0",
	"V1GNuQ1UHp41y7FPxUzqXu5009S6oCKBtyoF1YvB3wvqiKa2LRvwV0D5C21w0aEWHUC2msd132tg2Z7k",
	"NwBocwLrAbrebBPT585eWaXWN6jULaGWJk2LSJ+GKF8vs6kM9PVW7CULyoRXs64ZeZTRa3I0IsmCWrEA",
	"Srcs8ej87dt/9Cr5N0G5Y5+2VHqrww9no4MnTw8OxqPR0Xa6Gkep1hU34NVPHd9OU9uB1/JYmxEfXDAy",
	"P/wuhlmCME0Jq/VEU986BbX5/0E6UlRoinaxNR3C01lQvagoqv6gq/aP4OnRIT2AEeyPD4/34fjg6RiO",
	"R7NDenCYPD46fnz8+HF6MJtBmiSP95PxExjDk9GT/fFofDweH4emd09qJI6uKOew3jp2Tbq4CA1zl+Zx",
	"lz66U407Sq+LwLVq8FQwwyhn/6xU4UuaGKm+iUbsmqJ9/NqS86v86njjBAV77cRRA3uGoeBaISr/yY89",
	"qpOl4efSabpZIJizWd/GkX1Z6FKurHTgXq//+HT2kgmnp3yTqZQcqKib/EynwIMDoCz/b2uNhiJPd4Vl",
	"zaDbBoEqMHanFHetkBq1TZyF6PrvVwYF/yp5wHXOFOhdlqRgpkAvqg7DkAy+sYvcRPYfdAA6pZ5uje37",
	"ixuLCC3+NRPmbgNTGRPmr8DUv2NgymL+r8DUToGpBvt9jwGf95VM3X5e9TdnRZZRtQzMrhEn2q6rEqJW",
	"w2pdbBaU9aenrj3up6QMgcIMZDsM/hq/qyFElaJ2VVFeTDnTC0gv6A4qotIA243uxHmtYHcYK4DUuMMw",
	"LwvOiVWdBHA0oiCRKiUa1CWkZLpEHkrRyiIg0lwyYZyk00ZBw8RlmkjBl2TGOIcUt4YoeX3y5uTVi/fE",
	"/hDk5Pnr0zcTfAWXoJZWtAFHYQZkxoCjfKNTDVaFTCGhhQZCSa4gYbrm7JwJnIcm1LE3+yekhGoNZvAR",
	"YbVKOSuiAleeS20oLzsekDO3bFyIlduhBfwNp4u4TwgV+goUqhsGmtTj/iwTakciTGgDNLUTi7vmZ9uY",
	"ahiZzkq/SIKO5OnZW3Iwfvx4b0wozxd0b78l1X7+EKI6Tg0zRai7F1Z3ltotJm8+vH7x/vTZo+P48Q8W",
	"IIYYOce4J7liZkG4FHPsycLEKmJqCOW8pX+iw+PB4/H48f5+cCplD18/F7+odVN5PBgfjI8PjkIzceiv",
	"wByw5uY4r6DJbal/zasLy9UcMhBm8w6u7609o9gRSIccQmpkhdzfUZME/HH/1vEa6uxkQcUcBuSMZlA+",
	"pk069p/ERJSGiJ3zhFxZg4VpBLvlV/IZINeEGU2SQin75JLyAu6b7tcS+nrS+77IYQ1Sy/0havzwHayi",
	"faHRYtULqnyYSRP8J0omKx1LtiJuUD0gfz97+4YsqBWjmok5ByKKDBRLiJ1MTK4WLFk4CzqnSoOy1jrF",
	"viiZMkHVkjjDckLGx8eD42OSyAw0mdLks23lHo5GY2dOU7Ek3sUjdCovgez/r6MDS0WacRDG2r6yECmk",
	"lYZhYo46wYWOcqmM9yhipDw08Bo7JNbsCVIckmSyjrIO98dPWoLjxYf3QZlBlxaJFzM0ykXS4w6vNLtw",
	"bb5s0SM2vegLJeSKJXCRg7pAZG8Qot7BqGXp/ih+2g4TOyyFTRXLDziM7hunRGiyMsyoM8zRaNQ/iBUW",
	"PfTdnAW5Jp31x5bm8sI0rBVq6JRqaI2+f3x8/DSoBJZW6rVMqhmX1EQrTtAOTHoq8iLgM5957my0HJDO",
	"+msTiEhB8kLlUsOktbByxVbckpmSGVkPImQ+52drZELrmlb8bV1KK8ydAEeOWigAJ76169+aayRlms4V",
	"ABPzII/JLKfKICkrF+lqr/7n4hqyqSzUnDTa2omBZU6ISSHY7wUQmiiptTPodDAItx07xySFGS24QVXn",
	"+HkjfwNqoBnAhfJ+T7vzd6ASEIbOgUzBXAEIMkIAj8PkDdfM3GF3Gb2+cGHkHlUSR9k8u9MRmdg0YlAm",
	"VuGEcby1fPxaoZdLzQy7hFUT8q7FXjWSn+RtJF8leTr6XIiCcrJ0DpEguUNY28Ae7G+zA9dYxyoMP20v",
	"z3rsyYA8C9iWLeFkCW1FPCkgEvuknCxAoSTg7DNYCUj9DlbtEJoFLAnl1hRZuhAddcLKDmql2JbSabNY",
	"2UI4bOb3O2HhO+PK++DEjQzUT/k72cGnVehnNerHYU45uYQFSzgQpnVhTUerzdw0BgGK+Hpnow9IOJsL",
	"a1AEl1/m/PRs5OwMmDLYsLqMZ9Ia7oT7BjHRdIZ8AtfWrvBhDL5shnRiF+BwoRHcqbZM6xKQpEqZoNb0",
	"sEy7sBLKGvsTx5RlYCYcl/l24Y/10HtdxgU7QUpuLgxch3mrD/FMXyTy0hHp6jYbRiArR6C9LJbROcTk",
	"kqUgYzLjUqqcU0GkIpdMmYLyCyML1RPGYKbtmTY35hTfmaAQJJURuwtcGuvvaDW/FyMFEISD1WuOOEiG",
	"+zCexC5BDepV3i30BuR5wyLEj9rRIny0CcaBjZJt4N3a0VR8g/5FldvYlesYcVQZRjlxQeEBeXEJalnH",
	"UCtt6txuIjNmDAY2rWwkHGaGFMLIIllA6gKa2u0jOcbOQM0h9f1NfccxgesEcuPRV3kPCnJOE/BxgauF",
	"5MGoz22D/s72QLHQCYNs103AkLnphMFDahy/Xa8KkVjC6C73KXq/rTYj2nh972Dp/DAEJZlTzkEtB+QM",
	"HDKxQoTgLgSaWRyoIsxYQr7NzoZj88D2hs4hwS3T3eB91vys7pwZjnyb0eufQczNIprsHx2hIVP+Hu8o",
	"uN8pObcU4qfXJje3CXmhZcjEPnPG6MKTt5BiL6EiAdy6YD5phGC2gR6QE1Fb+dWuhHCvSZnuiH571fBv",
	"5R5Cw/QVACnG2nBxjkVWCaMx74s8MfOvj0ycdfHYBtSUmoWSMrvwvQXJdQrp5jYF4+nFEmjPexCg5suL",
	"hNPQfswLfGuVAq7Wwh9bxuTEUvmrlph+FhLRc9B9nb9SAGIhLeLmVK/p+Hl4w8JcaPZP2AYVVlNIvkNz",
	"XagZTeCCKqDbfWFAKfvFtmPsQB09cat3i6VmCeWk8XhAXgPVhSVso+gl8ECIGbf6ULnQDIgCqq1Dp31M",
	"Uk8sM7jlE22kcirE+9Euj0NIgzFlF1L20WHLstRFr11cOqRuAmS9Xm+vkviG9i1yr6Mdwaq2TdR/BzR+",
	"G2puBBSORmGzp0HMq+5Kh3YbIY/9p4Nwj13q3UnilykFAb1Zb2FT3dm+5kybxub1c+BsCtaz5ktr0vAi",
	"9Qq3vaXt/CBn7Hgl7B451V55RSixLS37PWEcDqnXO1m+a5YY4skkaB8lhl2GTFtdLcy1CNnGd2Eb+X4w",
	"heWit5TnpE6v8dOSgky5TD67DPVHCI4f1uRO7pQtsYOddns77jb2HZe7GkaVl45RlJbpsl0HTXvnjuyz",
	"dtChE69nM0iWCbfEa1u4WMCjVNEZZvhdKLhkcBWTKg8mJrNCpIoyzcTc/bAPEy41/i1NrCB1uEF6kVQZ",
	"kJtSoDf4VVVq5moM6cX7Z3sHjw8PGoVhblvRhTDIiduWyYAKt/FdBzmWYAbrPJ6tAwhiepHWFSXrKkTC",
	"iUUXPbGl9XL1F8UM9Dqbv6Af4lx1JtCJzOmSS1ru0zZdxzLtkYl6W7mRZ455j6aRAgoM8zmcbLDmsdso",
	"N+WAUvlAMoJ8wcS8TPO4Qx/zrkRo5e7s7l52glyYYj9joNwGHNV6oIDyi6a8i7/KJ908oGvudN6m+Gpw",
	"Ml+Vcfed+6WtjRbsJK7ILySBzthcnPanWUNGGW/bUFQY+V/9z0Eis6iRz+uaB9MTtL6Sqn3WQqSLHJSG",
	"RGGSUdVL1XjTAsvhqg/WrfDhM1mrFP6ePFY7sw/5vcN+VnBeltXVXZ0II8WS/AyzP/51qeDhkFZNJ94e",
	"fxZK3x/+8OWdVJ3fUza4Ffi+xjNcyr1SC1q5xitVluHK0F1r291Cb1fYjt/ea1l7f4np6yU5g6RQzCxJ",
	"Wcmyair2lMmiMeJqY/sHODvv3fM/K/KcL/vOwTGUE40tGhUvj5ggV8B8Vlpn33/U89+utfqNAtpGLXFz",
	"ym0CCXF3o7h1hYPeiiksKJ+d13ZaMMCAnq1de6NdGbHD3QXi+qnqHeua060sgGZFwqre38YlvVcev0W5",
	"YG/4X6YFp+qZtXWZdYvsGjaubOWr+1hlq6S9WiUT5vFhtEvN+lnNiJ4JGybWeD/e5MD0FKavMPSPbE5+",
	"koWGjSOsuopxg9MaowfwEy5ib9JEkOkUXJ8VzEBfwXh1qJV+D3OmjYtt7VT5WpeF32EXZ0Yqf/bYjj2t",
	"Qm73PjTlPRWH9g3BesFSf56/f/HfCcKYpJBzicksLQLJlij7zig34/2DW5fktIwQrH6Ha18BfYslGlVo",
	"A6lLabk98rt1BBZwcVURukIY/YjunVEcJNIwhzRBEmSHWr6vsIL9N7pmb7ayHKrmtf5pR8+RL3GfDxEX",
	"EyaY6bUovuYoA1e8WavB1vRuKZiPNyf3rdTutyEYgv8HvaYK3odlO5YlRb4iifrj/zlwpwVGaEwnvXq0",
	"/3hvNN4bjc/H+5PRaDIa/c+m07JWSVb+V2dH0D62g/P/UhjGmaYGivbZCbd20/q0jMzK+NP6gbdw6oJR",
	"ludljvO63oMJs5xqc5FIIeA6mOlVYopTkoIS7I9/udRM3z6ErPHofHw0OViLrO45lqtl662yxPCc6gll",
	"TAP54/+S32QHoF9BQCG1XuO4dn4bdN6a9iqnWBXknZAzK3n9jiJQBeqkMIv618tyfn//xboVKKdxawbf",
	"1nO1/lZ0YztmYhYopX7NBG6cnrw7daVtC6DcLEiygORzVIWpoh/rjZbXLFFSg7pkCdjvoji6BOV2FKLx",
	"YDQY4cETOQias2gSHQxGgwOMAZgFrmfoEuyHCijfc3HFYZn7MHS5DygspIuZVOLlNK3ka/t8DYcH0OZH",
	"mS5diqUwPjuV5jn3sbehO+60PFN1o87rP9fqpo17S6H4wAUjcPb7o/H9zqQMfNx0o77RWTGtflbH8Ogi",
	"SUBrS5/o1ByORgExIS4pZ2kZI28RJIZjmqT466ebT3Gky51RjxlCiYArn6PCBMkVs+9JRtVnjCe5s2d/",
	"jU7KKotyXdEnO9wWxDH8Uh7HcWOXMIcAmbwEkyy6VJJTRTMwSF+/fomYwKiWWZTu7qR5zkcbvXEDVV0x",
	"8GkF9aM7Q333wLAVZL/9h8Xm0R0O2QqrrQ54KgwoQbmrWVbkhVJS7UYpiBxCtyCSjbTRkhSdFGS/s1Nt",
	"pOHGORaAEylgz8g9KapNpL59owkeloGfW/koC4O1plV4T+FPHShIuJIFT8nUcsSC8tleyYm+0h2NNyGx",
	"stGVsfHUehiDj+K8mjHTFQM3NjvNAhTMpAJyyTTDMkhKMioo1sNxlnxmYk4+esXzMSJwnUPick81gN8G",
	"w/NCpDtRRGNdFpYyE9xnJUJOZbokVH92Po/b9QrJ4sZhDfcjiHu2Cx9YCDeWGeAKB4q0IVkfhhedvPa7",
	"om708UONbpnbOnX+wIEKFTiLg4eaxXvwSTdGVqcmWEbHMxP+fLKx0qKNwzFWtWavOBzW2TxeL3Yy6upU",
	"ISbmA3LSPGkCQUZyBdqiVczLcgpCuUbJ0RCm2gkwK/as2KikE1mCqfbaMXlOzmbWUkyl20nHdFQraiGR",
	"Vh6X6VEB+fIKzAkup+Y9HX2lst1xR7g+S6YTFv7TaOKbeD3BvQLMamjSm96F4L6w9MbRGYdQ2eeZnFmf",
	"loPTpqal26rcZ8ux6BjFRGDRr4JMXkI6IGj5+Po9VzGm69Jdwowv8SczJqhIGLUrccEiR6EJFYRLDUTJ",
	"K904xIsWKTOQDj6Kk27RUKOVW1XqUz8mqOwdT8A100ZbBercIjuL8pxFTRaSp4SZATkrrKkjCDV4w4I/",
	"uEWTw9FxiOSf43gtlbrZakXPc6O9Wh9yt2qwHgZ8aLfyv3RKSKccOog9zFwoJ44YyBtpyEtZCA+P4wfD",
	"SsmwDUYR6Sqb/PnUraPyzeo2XqtO3TlVW2vTNGWuTAoP3UuAXQbzgEsY+8NPSjfENE7AaandvxEq6rOt",
	"5lZHH44OrYTSpRCyHVTaOQMFToyhKJWzyvj3vadMuxTKHuVci6kfl3j45UOIqtEDWfROnX8PjP6nNCnc",
	"qU0beCoPl/e3iwxjgsuFtMwBbXjnWCNVFhm6qsGe86DcuZeYLuE4CFKG6ruOAFQWKtb2G4kHYvpc+6tG",
	"KmpD9IGiGvyZVMZbLinTOadL5JrzskyOiro2spyP7ZsZV1Y3qQvs6tOHykOPPkZCuq8+RnFd13JFl8jU",
	"5aEt4M7Cq04ucEmyrToClOEL8AWVdtH//3//H0JdgkUtzn0ZprWVyXSJfz38MA8Fz3XCMkDVXzbowhi+",
	"p8riQ38V4xl10aYLPPxWaFMfyOfdC5eBm2KRg6WVco4cEEWLRnYwJb5Ywa/ex18Ql/6s18FHcSbr88a0",
	"kTmZggX2lWLukFRpJWHLRq1VnlR4aJULQk7c3Mpk1DrRyhfdFSLFUo3KJrRrrU6PmMpivjBE29m4eSrA",
	"w3HIwuLwSoDSC5ZbDFrT1RuPujz2r8d49KW792873meMp1V/vFWM56E1wl/hnb9M8W9mij9DiWj12JSl",
	"KYiy1qxUdr40qlE/8uczyj+g3t8yBlaYxVCzudhjon/X8J3Uxo7lUsXvKU7dzrR/4PB0Jwk+gJgPuip3",
	"ue12YEXpoYSJUre5wIjDeIVSC3z3xmpMvAXDHQ5nCmV1t9vGLjFskbqC3yLfDr8f8nvEb53N/w3w20iS",
	"/97w29r83QG9ZR7psErZ3bTzX6f23uOmf+cmsgc2Q3ou/uoxSUJ4sFgov6+rCjFQmqLTYcpiuCqvrkRO",
	"nekR1WW5jQS+PsQNMV1PD2ma9uOwvC31XN4zHrvXzz4wBlduhd0Gdydpar0XvOrWX97QuGPvluipUkzX",
	"MdV58xaBe+Ws1p0f3ySNpn3tQQAv5/52jZzLZSuk2WPnaGfnQG3nhKVilQO6AZMOYyE0DqeFWoPL6rbR",
	"E70UyT2hceVG4a2QuP9Q1uePqG+SBHLjg9TaUGXKk51leZ/dlVSfUTAyUYAmTFT7lXM87MMHSZkua9Cr",
	"4FAGljGN07CQQjq4a69w9dbYEJU2SpmvaH2dzdQlhlCxdDXLV3gqhagkPi5/QjLKfdZwdeiEu2qgeS/M",
	"mhtvBnftVWy16G147hdmFqmiV7jaObuEak1l5r671anEOcZrzNfzZsYcCMK8WV24cp+8uXKp0vfFm6/x",
	"hMY/N2+uXpzzb8CbWy16G950ZRygHpo3v+AfX9R2M2RlUVQwdfQVmEbN4jYx1Gbv303maOtS0c3G5yuM",
	"oru0dyyvxNMYKtfhNsaLSyVfB+efXIswFDZM+KdmojqOV6aHrHdB3rlWJ2m61bi+uWXFrzQGnXnvJ9kA",
	"pR+hDGgZBddDJpjB0Afeyj4sE0thjSG/cpd7dJ8eav/N8d95ZlRtm5dLQElTraMmeSyHwGri8gIVzxle",
	"KrfSpFr8wKobS1dwWgmmmStX2yLu8Rw9kc7dp/eJ3M0Xrv5ZcOxAV7nRZFYB76vx1qnCXIe6E5FakJ7X",
	"X9RG4LexxLx9iMZHGGRY3Xp7cHVYZiOEOD9tf/H9Q4hyXskK3ZURtwCZLpiBoQs7bIJXVd79/YOpUypd",
	"QWwLCLm63j0ETBNc7sE6861d/b5iwnUSVLcr7SaPygSOmOCFNv6OF8JmLhVLyUuWujPm0Eb8vQDkHW8k",
	"+hLpb2QMtiES8lnqNTfMQKLAKAaXwR2FQNJooxcLk5l11yqwOoMf4fA1dtQrrJF10TkSnnaQuMgeWaEn",
	"624Mvzin42YdSX3QoMJJboFNmNPnJQ20/YTqOul+D2HjuRf3Sib+mufw1tKs3u3etnSwibMGBEvc4E3R",
	"NSJ0hYnhjF5aawy6uebNy7Y7WedtlL3H9PGXZTd1YsdLqT7oLasBt8DX6gXiwZ46l4R/JwmQG4T7d2nS",
	"nbl7d5pXxzJBHL24w62kcGGEBqF5jDczD/u2p/4imb9IJkQyLoHFjhES+8/hErjM0U5wrSJ/IQdW4E+G",
	"Qy4TyhdSm8nT0dMRnlfXCTQomRaJ1171p3oyHNKcDYyUn0EMZsr+Gl6O8U5lP9kvJc1gOo3t2v9uWFaN",
	"p35NjSdO7te/q7LbxrNzRVN39EL1qIpc3Hy6+Y8AAAD//5JbZOu4lAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
