// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for UserKycStatus.
const (
	UserKycStatusApproved UserKycStatus = "approved"
	UserKycStatusExpired  UserKycStatus = "expired"
	UserKycStatusNone     UserKycStatus = "none"
	UserKycStatusPending  UserKycStatus = "pending"
	UserKycStatusRejected UserKycStatus = "rejected"
	UserKycStatusRevoked  UserKycStatus = "revoked"
	UserKycStatusVerified UserKycStatus = "verified"
)

// Defines values for UserRole.
const (
	ADMIN   UserRole = "ADMIN"
	MANAGER UserRole = "MANAGER"
	USER    UserRole = "USER"
)

// Defines values for GetListKycVerificationsParamsStatus.
const (
	GetListKycVerificationsParamsStatusApproved  GetListKycVerificationsParamsStatus = "approved"
	GetListKycVerificationsParamsStatusSubmitted GetListKycVerificationsParamsStatus = "submitted"
)

// APIResponse defines model for APIResponse.
type APIResponse struct {
	Data    interface{} `json:",omitempty"`
	Message string      `json:"message"`
}

// AddClaimRequest defines model for AddClaimRequest.
type AddClaimRequest struct {
	// ClaimTopic The topic of the claim (e.g., 7 for KYC)
	ClaimTopic int `json:"claimTopic"`
	UserId     int `json:"userId"`
}

// AddClaimResponse defines model for AddClaimResponse.
type AddClaimResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// BurnTokenRequest defines model for BurnTokenRequest.
type BurnTokenRequest struct {
	// Amount The amount of tokens to burn, in human format (not wei). The request is refused rather than approximated when the amount cannot be converted exactly: it must carry at most 15 significant digits, stay below 9007199254740992, and have no more decimals than the token declares. The result is written to an immutable ledger, so an amount that merely resembles the one requested is worse than a rejection.
	Amount float64 `json:"amount"`

	// To The address to burn the tokens to
	To string `json:"to"`

	// TokenContractAddress The address of the token contract
	TokenContractAddress string `json:"tokenContractAddress"`
}

// BurnTokenResponse defines model for BurnTokenResponse.
type BurnTokenResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// ConfigureAuthorityResponse defines model for ConfigureAuthorityResponse.
type ConfigureAuthorityResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// ContractDetails defines model for ContractDetails.
type ContractDetails struct {
	// Address The address of the contract
	Address string `json:"address"`

	// ExplorerUrl Direct link to the contract on Etherscan
	ExplorerUrl *string `json:"explorerUrl,omitempty"`

	// Name The name/type of the contract
	Name string `json:"name"`
}

// CreateIdentityRequest defines model for CreateIdentityRequest.
type CreateIdentityRequest struct {
	// CountryCode ISO 3166-1 numeric, as stored on chain by the IdentityRegistry (uint16)
	CountryCode int `json:"countryCode"`

	// UserId The user ID of the investor
	UserId int `json:"userId"`
}

// CreateIdentityResponse defines model for CreateIdentityResponse.
type CreateIdentityResponse struct {
	Data    *IdentityInfos `json:"data,omitempty"`
	Message string         `json:"message"`
}

// CreateIssuanceOrderRequest defines model for CreateIssuanceOrderRequest.
type CreateIssuanceOrderRequest struct {
	Quantity     int `json:"quantity"`
	RealEstateId int `json:"realEstateId"`
}

// CreateIssuanceOrderResponse defines model for CreateIssuanceOrderResponse.
type CreateIssuanceOrderResponse struct {
	Data    *IssuanceOrder `json:"data,omitempty"`
	Message string         `json:"message"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	// NbDecimal Number of decimals
	NbDecimal int `json:"nbDecimal"`

	// Symbol On-chain token symbol
	Symbol string `json:"symbol"`

	// TokenName Name of the token
	TokenName string `json:"tokenName"`
}

// CreateTokenResponse defines model for CreateTokenResponse.
type CreateTokenResponse struct {
	Data    *TokenInfos `json:"data,omitempty"`
	Message string      `json:"message"`
}

// IdentityInfos defines model for IdentityInfos.
type IdentityInfos struct {
	// CountryCode The country code of the investor
	CountryCode int `json:"countryCode"`

	// IdentityAddress The address of the created identity
	IdentityAddress string `json:"identityAddress"`

	// TransactionHash The hash of the transaction
	TransactionHash string `json:"transactionHash"`

	// UserId The user ID of the investor
	UserId int `json:"userId"`

	// WalletAddress The investor's wallet address — the last 20 bytes of the keccak256 of the public key, not the public key itself. The public key is never stored; when it is needed it is recovered from a signature.
	WalletAddress string `json:"walletAddress"`
}

// InitializeIdentityFactoryResponse defines model for InitializeIdentityFactoryResponse.
type InitializeIdentityFactoryResponse struct {
	Data    *ContractDetails `json:"data,omitempty"`
	Message string           `json:"message"`
}

// IssuanceOrder defines model for IssuanceOrder.
type IssuanceOrder struct {
	CreatedAt     time.Time  `json:"createdAt"`
	CreatedBy     int        `json:"createdBy"`
	Id            *int       `json:"id,omitempty"`
	OrderRef      string     `json:"orderRef"`
	RealEstateId  int        `json:"realEstateId"`
	StatusCode    *string    `json:"statusCode,omitempty"`
	StatusId      *int       `json:"statusId,omitempty"`
	StatusIfFinal *bool      `json:"statusIfFinal,omitempty"`
	StatusLabel   *string    `json:"statusLabel,omitempty"`
	TokenQuantity int        `json:"tokenQuantity"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
	UserId        int        `json:"userId"`
}

// Issuer The legal vehicle issuing the shares, as stored. Richer than RealEstateIssuer, which is the trimmed view embedded in a public asset.
type Issuer struct {
	// CountryCode ISO 3166-1 alpha-2
	CountryCode string     `json:"country_code"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Id          int        `json:"id"`
	LegalForm   string     `json:"legal_form"`

	// LeiCode Legal Entity Identifier, 20 upper-case alphanumerics
	LeiCode *string `json:"lei_code,omitempty"`
	Name    string  `json:"name"`

	// RealEstateCount How many non-deleted assets are attached to this issuer. It is what tells a manager whether withdrawing it from service is possible.
	RealEstateCount *int `json:"real_estate_count,omitempty"`

	// RegistrationNumber Registration number in the jurisdiction of country_code
	RegistrationNumber *string `json:"registration_number,omitempty"`

	// Status Status code — draft, active, suspended or dissolved
	Status string `json:"status"`

	// StatusId Identifier from ass.issuer_status
	StatusId  int        `json:"status_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// IssuerPatchRequest Fields to change. An omitted field keeps its current value; an optional field sent empty is cleared.
type IssuerPatchRequest struct {
	// CountryCode ISO 3166-1 alpha-2, upper case
	CountryCode        *string `json:"country_code,omitempty"`
	LegalForm          *string `json:"legal_form,omitempty"`
	LeiCode            *string `json:"lei_code,omitempty"`
	Name               *string `json:"name,omitempty"`
	RegistrationNumber *string `json:"registration_number,omitempty"`
	StatusId           *int    `json:"status_id,omitempty"`
}

// IssuerWriteRequest Full definition of an issuer. name, legal_form and country_code are required: a vehicle without a name, a legal form or a jurisdiction describes nothing an investor could rely on.
type IssuerWriteRequest struct {
	// CountryCode ISO 3166-1 alpha-2, upper case
	CountryCode string `json:"country_code"`

	// LegalForm SA, SARL, SCSp, RAIF...
	LegalForm string `json:"legal_form"`

	// LeiCode Legal Entity Identifier — exactly 20 upper-case alphanumerics.
	// Always optional: a LEI is only mandatory for entities under market reporting obligations or whose securities are admitted to trading, so a vehicle placed privately may legitimately have none. It is globally unique by construction, so a duplicate is refused.
	LeiCode *string `json:"lei_code,omitempty"`
	Name    string  `json:"name"`

	// RegistrationNumber Registration number in the jurisdiction of country_code — the RCS number in Luxembourg.
	// Required for an active issuer: a vehicle assets are attached to and published under must be identifiable in its register, which is an investor's only way to check that it exists. A vehicle still being incorporated does not have one yet, so it is created as a draft (status_id 1) and gets its number when the register assigns it.
	// Unique within its jurisdiction. Two issuers sharing one in the same country are refused with 409.
	RegistrationNumber *string `json:"registration_number,omitempty"`

	// StatusId Identifier from ass.issuer_status. Defaults to active (2) on a creation; send 1 to keep the issuer as a draft while it is still being incorporated. An issuer cannot be created dissolved (4).
	StatusId *int `json:"status_id,omitempty"`
}

// JwtToken defines model for JwtToken.
type JwtToken struct {
	ExpiresAt    time.Time `json:"expiresAt"`
	RefreshToken string    `json:"refreshToken"`
	Token        string    `json:"token"`
	User         User      `json:"user"`
}

// KycVerification defines model for KycVerification.
type KycVerification struct {
	CreatedAt time.Time `json:"created_at"`

	// DecidedAt The date and time when the KYC verification was decided
	DecidedAt *time.Time `json:"decided_at,omitempty"`

	// DecidedBy The ID of the user who decided the KYC verification
	DecidedBy           *int   `json:"decided_by,omitempty"`
	DeclaredCountryCode string `json:"declared_country_code"`
	DeclaredFullName    string `json:"declared_full_name"`
	Email               string `json:"email"`

	// ExpiresAt The date and time when the KYC verification expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Id        int        `json:"id"`

	// RejectionReason The reason for rejecting the KYC verification
	RejectionReason *string `json:"rejection_reason,omitempty"`

	// RevocationReason The reason for revoking the KYC verification
	RevocationReason *string `json:"revocation_reason,omitempty"`

	// RevokedAt The date and time when the KYC verification was revoked
	RevokedAt *time.Time `json:"revoked_at,omitempty"`

	// RevokedBy The ID of the user who revoked the KYC verification
	RevokedBy *int   `json:"revoked_by,omitempty"`
	Status    string `json:"status"`

	// SubmittedAt The date and time when the KYC verification was submitted
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	UpdatedAt   time.Time  `json:"updated_at"`
	UserId      int        `json:"user_id"`

	// VerificationMessage Additional message or reason for the verification status
	VerificationMessage *string `json:"verification_message,omitempty"`

	// VerificationStatus Status of the KYC verification (e.g., pending, approved, rejected)
	VerificationStatus *string `json:"verification_status,omitempty"`
}

// KycVerificationRequest defines model for KycVerificationRequest.
type KycVerificationRequest struct {
	// DeclaredCountryCode ISO 3166-1 alpha-2 country code
	DeclaredCountryCode string `json:"declared_country_code"`
	DeclaredFullName    string `json:"declared_full_name"`
}

// KycVerificationResponse defines model for KycVerificationResponse.
type KycVerificationResponse struct {
	Data *struct {
		// VerificationMessage Additional message or reason for the verification status
		VerificationMessage *string `json:"verification_message,omitempty"`

		// VerificationStatus Status of the KYC verification (e.g., pending, approved, rejected)
		VerificationStatus string `json:"verification_status"`
	} `json:"data,omitempty"`
	Message string `json:"message"`
}

// MintTokenRequest defines model for MintTokenRequest.
type MintTokenRequest struct {
	// Amount The amount of tokens to mint, in human format (not wei). The request is refused rather than approximated when the amount cannot be converted exactly: it must carry at most 15 significant digits, stay below 9007199254740992, and have no more decimals than the token declares. The result is written to an immutable ledger, so an amount that merely resembles the one requested is worse than a rejection.
	Amount float64 `json:"amount"`

	// To The address to mint the tokens to
	To string `json:"to"`

	// TokenContractAddress The address of the token contract
	TokenContractAddress string `json:"tokenContractAddress"`
}

// MintTokenResponse defines model for MintTokenResponse.
type MintTokenResponse struct {
	Data    *TxHashName `json:"data,omitempty"`
	Message string      `json:"message"`
}

// RealEstate defines model for RealEstate.
type RealEstate struct {
	// Active is estate active
	Active *bool `json:"active,omitempty"`

	// Address Full postal address. Served only to a MANAGER or an ADMIN; the public answer carries RealEstateLocation instead.
	Address *RealEstateAddress `json:"address,omitempty"`

	// Configuration Amounts and share counts are carried as decimal strings. JSON has a single numeric type, which most parsers read as a binary double: 199.99 comes back as 199.99001, and any integer above 2^53 is silently rounded. The string is a transport format, not the type of the data.
	Configuration *RealEstateConfiguration `json:"configuration,omitempty"`

	// ContractAddress Address of estate on blockchain (token)
	ContractAddress *string    `json:"contract_address,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	Description     *string    `json:"description,omitempty"`
	EstateType      *string    `json:"estate_type,omitempty"`
	EstateTypeId    *int       `json:"estate_type_id,omitempty"`
	Id              int        `json:"id"`
	Imageurl        *string    `json:"imageurl,omitempty"`

	// Issuer The legal vehicle issuing the shares.
	Issuer *RealEstateIssuer `json:"issuer,omitempty"`

	// Location Coarse location, safe to expose publicly. The street, the postal code and the coordinates are held back: they pinpoint a tokenized asset.
	Location      *RealEstateLocation      `json:"location,omitempty"`
	Media         *[]RealEstateMedia       `json:"media,omitempty"`
	Progression   *RealEstateProgression   `json:"progression,omitempty"`
	PublishedAt   *time.Time               `json:"published_at,omitempty"`
	Specification *RealEstateSpecification `json:"specification,omitempty"`

	// Status Lifecycle status code (draft, in_review, published, fundraising, funded, closed, cancelled)
	Status   *string `json:"status,omitempty"`
	StatusId *int    `json:"status_id,omitempty"`
	Title    *string `json:"title,omitempty"`

	// Token The ERC-3643 contract of the asset. Absent means not tokenized yet.
	Token     *RealEstateToken `json:"token,omitempty"`
	UpdatedAt *time.Time       `json:"updated_at,omitempty"`
}

// RealEstateAddress Full postal address. Served only to a MANAGER or an ADMIN; the public answer carries RealEstateLocation instead.
type RealEstateAddress struct {
	City string `json:"city"`

	// CountryCode ISO 3166-1 alpha-2
	CountryCode string `json:"country_code"`

	// Latitude Exact decimal, NUMERIC(9,6). Set together with longitude or not at all.
	Latitude *string `json:"latitude,omitempty"`

	// Longitude Exact decimal, NUMERIC(9,6). Set together with latitude or not at all.
	Longitude        *string `json:"longitude,omitempty"`
	PostalCode       string  `json:"postal_code"`
	Region           *string `json:"region,omitempty"`
	Street           string  `json:"street"`
	StreetComplement *string `json:"street_complement,omitempty"`
}

// RealEstateAddressPatch Address fields to change. Same fields as RealEstateAddress, none required: what is not sent keeps its current value.
type RealEstateAddressPatch struct {
	City *string `json:"city,omitempty"`

	// CountryCode ISO 3166-1 alpha-2
	CountryCode      *string `json:"country_code,omitempty"`
	Latitude         *string `json:"latitude,omitempty"`
	Longitude        *string `json:"longitude,omitempty"`
	PostalCode       *string `json:"postal_code,omitempty"`
	Region           *string `json:"region,omitempty"`
	Street           *string `json:"street,omitempty"`
	StreetComplement *string `json:"street_complement,omitempty"`
}

// RealEstateConfiguration Amounts and share counts are carried as decimal strings. JSON has a single numeric type, which most parsers read as a binary double: 199.99 comes back as 199.99001, and any integer above 2^53 is silently rounded. The string is a transport format, not the type of the data.
type RealEstateConfiguration struct {
	// CurrencyCode ISO 4217
	CurrencyCode           *string `json:"currency_code,omitempty"`
	PaymentFrequency       *int    `json:"payment_frequency,omitempty"`
	PaymentFrequencyType   *string `json:"payment_frequency_type,omitempty"`
	PaymentFrequencyTypeId *int    `json:"payment_frequency_type_id,omitempty"`

	// PricePerShare Exact decimal amount, NUMERIC(20,8)
	PricePerShare *string `json:"price_per_share,omitempty"`

	// TotalShares Exact integer count, NUMERIC(20,0)
	TotalShares *string `json:"total_shares,omitempty"`

	// TotalValuation total_shares x price_per_share, computed by the database
	TotalValuation *string  `json:"total_valuation,omitempty"`
	Yield          *float32 `json:"yield,omitempty"`
}

// RealEstateConfigurationInput Share configuration. total_valuation is absent on purpose: the database computes it from total_shares x price_per_share and refuses any write, which is what keeps the three values from ever disagreeing.
type RealEstateConfigurationInput struct {
	// CompartmentRef Luxembourg compartment reference, unique across assets
	CompartmentRef *string `json:"compartment_ref,omitempty"`

	// CurrencyCode ISO 4217. Required with the price it applies to: an amount without its currency means nothing, and defaulting it would record a currency nobody chose.
	CurrencyCode string `json:"currency_code"`

	// EntryFeeRate Percentage between 0 and 100
	EntryFeeRate *string `json:"entry_fee_rate,omitempty"`

	// ExitFeeRate Percentage between 0 and 100
	ExitFeeRate   *string `json:"exit_fee_rate,omitempty"`
	MaxInvestment *string `json:"max_investment,omitempty"`

	// MgmtFeeRate Percentage between 0 and 100
	MgmtFeeRate   *string `json:"mgmt_fee_rate,omitempty"`
	MinInvestment *string `json:"min_investment,omitempty"`

	// PaymentFrequency How many times per period the yield is paid. Required with the yield: a return with no rhythm cannot be compared to another one.
	PaymentFrequency int `json:"payment_frequency"`

	// PaymentFrequencyTypeId Identifier from ass.payment_frequency_type, the period the frequency counts in. Required for the same reason: "4" alone says nothing.
	PaymentFrequencyTypeId int `json:"payment_frequency_type_id"`

	// PricePerShare Exact positive decimal, NUMERIC(20,8)
	PricePerShare string `json:"price_per_share"`

	// TotalShares Exact positive integer, NUMERIC(20,0)
	TotalShares string `json:"total_shares"`

	// Yield Annual yield in percent
	Yield *string `json:"yield,omitempty"`
}

// RealEstateConfigurationPatch Share configuration fields to change. total_shares and price_per_share are optional here, unlike on a create, because they already have a value to keep.
type RealEstateConfigurationPatch struct {
	CompartmentRef         *string `json:"compartment_ref,omitempty"`
	CurrencyCode           *string `json:"currency_code,omitempty"`
	EntryFeeRate           *string `json:"entry_fee_rate,omitempty"`
	ExitFeeRate            *string `json:"exit_fee_rate,omitempty"`
	MaxInvestment          *string `json:"max_investment,omitempty"`
	MgmtFeeRate            *string `json:"mgmt_fee_rate,omitempty"`
	MinInvestment          *string `json:"min_investment,omitempty"`
	PaymentFrequency       *int    `json:"payment_frequency,omitempty"`
	PaymentFrequencyTypeId *int    `json:"payment_frequency_type_id,omitempty"`
	PricePerShare          *string `json:"price_per_share,omitempty"`
	TotalShares            *string `json:"total_shares,omitempty"`
	Yield                  *string `json:"yield,omitempty"`
}

// RealEstateIssuer The legal vehicle issuing the shares.
type RealEstateIssuer struct {
	// CountryCode ISO 3166-1 alpha-2
	CountryCode *string `json:"country_code,omitempty"`
	Id          *int    `json:"id,omitempty"`
	LegalForm   *string `json:"legal_form,omitempty"`
	Name        *string `json:"name,omitempty"`
	Status      *string `json:"status,omitempty"`
}

// RealEstateLocation Coarse location, safe to expose publicly. The street, the postal code and the coordinates are held back: they pinpoint a tokenized asset.
type RealEstateLocation struct {
	City *string `json:"city,omitempty"`

	// CountryCode ISO 3166-1 alpha-2
	CountryCode *string `json:"country_code,omitempty"`
}

// RealEstateMedia defines model for RealEstateMedia.
type RealEstateMedia struct {
	AltText *string `json:"alt_text,omitempty"`
	Id      *int    `json:"id,omitempty"`
	IsCover *bool   `json:"is_cover,omitempty"`

	// MediaType image, video, floorplan or virtual_tour
	MediaType *string `json:"media_type,omitempty"`
	Position  *int    `json:"position,omitempty"`
	Url       *string `json:"url,omitempty"`
}

// RealEstateMediaInput defines model for RealEstateMediaInput.
type RealEstateMediaInput struct {
	AltText *string `json:"alt_text,omitempty"`

	// IsCover At most one media per asset may be the cover.
	IsCover *bool `json:"is_cover,omitempty"`

	// MediaType image, video, floorplan or virtual_tour. Defaults to image.
	MediaType *string `json:"media_type,omitempty"`
	Position  *int    `json:"position,omitempty"`
	Url       string  `json:"url"`
}

// RealEstatePatchRequest Partial update. Every field is optional and an omitted one is left untouched; the sections are merged field by field, except media which is replaced as a whole.
type RealEstatePatchRequest struct {
	// Address Address fields to change. Same fields as RealEstateAddress, none required: what is not sent keeps its current value.
	Address *RealEstateAddressPatch `json:"address,omitempty"`

	// Configuration Share configuration fields to change. total_shares and price_per_share are optional here, unlike on a create, because they already have a value to keep.
	Configuration *RealEstateConfigurationPatch `json:"configuration,omitempty"`
	Description   *string                       `json:"description,omitempty"`
	EstateTypeId  *int                          `json:"estate_type_id,omitempty"`
	Imageurl      *string                       `json:"imageurl,omitempty"`
	IssuerId      *int                          `json:"issuer_id,omitempty"`

	// Media Replaces the whole gallery. Send an empty array to clear it.
	Media *[]RealEstateMediaInput `json:"media,omitempty"`

	// Specification Physical description. Measures travel as decimal strings for the same reason as amounts: a surface stored as NUMERIC must not come back rounded by a JSON parser.
	Specification *RealEstateSpecificationInput `json:"specification,omitempty"`
	Title         *string                       `json:"title,omitempty"`
}

// RealEstateProgression defines model for RealEstateProgression.
type RealEstateProgression struct {
	// TokensSold Shares held by non-cancelled issuance orders. An integer, because an order quantity is an integer; only total_shares needs a string.
	TokensSold     *int     `json:"tokens_sold,omitempty"`
	TokensSoldPctg *float32 `json:"tokens_sold_pctg,omitempty"`
}

// RealEstateSpecification defines model for RealEstateSpecification.
type RealEstateSpecification struct {
	BathroomNumber *int `json:"bathroom_number,omitempty"`
	BedroomNumber  *int `json:"bedroom_number,omitempty"`
	BuildYear      *int `json:"build_year,omitempty"`

	// EnergyClass Energy performance class, A to G
	EnergyClass *string `json:"energy_class,omitempty"`

	// GesClass Greenhouse gas class, A to G
	GesClass    *string  `json:"ges_class,omitempty"`
	LotSize     *float32 `json:"lot_size,omitempty"`
	PoolSize    *float32 `json:"pool_size,omitempty"`
	SurfaceArea *float32 `json:"surface_area,omitempty"`
	TerraceSize *float32 `json:"terrace_size,omitempty"`
}

// RealEstateSpecificationInput Physical description. Measures travel as decimal strings for the same reason as amounts: a surface stored as NUMERIC must not come back rounded by a JSON parser.
type RealEstateSpecificationInput struct {
	BathroomNumber *int `json:"bathroom_number,omitempty"`
	BedroomNumber  *int `json:"bedroom_number,omitempty"`
	BuildYear      *int `json:"build_year,omitempty"`

	// EnergyClass A to G
	EnergyClass *string `json:"energy_class,omitempty"`

	// GesClass A to G
	GesClass    *string `json:"ges_class,omitempty"`
	LotSize     *string `json:"lot_size,omitempty"`
	PoolSize    *string `json:"pool_size,omitempty"`
	SurfaceArea *string `json:"surface_area,omitempty"`
	TerraceSize *string `json:"terrace_size,omitempty"`
}

// RealEstateSummary Real estate as served by the list endpoint. Deliberately excludes the street address, the media gallery, the issuer and the token: a public list must expose the strict minimum.
type RealEstateSummary struct {
	// Active is estate active
	Active *bool `json:"active,omitempty"`

	// Configuration Amounts and share counts are carried as decimal strings. JSON has a single numeric type, which most parsers read as a binary double: 199.99 comes back as 199.99001, and any integer above 2^53 is silently rounded. The string is a transport format, not the type of the data.
	Configuration *RealEstateConfiguration `json:"configuration,omitempty"`

	// ContractAddress Address of estate on blockchain (token)
	ContractAddress *string    `json:"contract_address,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	Description     *string    `json:"description,omitempty"`
	EstateType      *string    `json:"estate_type,omitempty"`
	EstateTypeId    *int       `json:"estate_type_id,omitempty"`
	Id              int        `json:"id"`
	Imageurl        *string    `json:"imageurl,omitempty"`

	// Location Coarse location, safe to expose publicly. The street, the postal code and the coordinates are held back: they pinpoint a tokenized asset.
	Location      *RealEstateLocation      `json:"location,omitempty"`
	Progression   *RealEstateProgression   `json:"progression,omitempty"`
	Specification *RealEstateSpecification `json:"specification,omitempty"`

	// Status Lifecycle status code (draft, in_review, published, fundraising, funded, closed, cancelled)
	Status   *string `json:"status,omitempty"`
	StatusId *int    `json:"status_id,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// RealEstateToken The ERC-3643 contract of the asset. Absent means not tokenized yet.
type RealEstateToken struct {
	Address   *string `json:"address,omitempty"`
	Id        *int    `json:"id,omitempty"`
	NbDecimal *int    `json:"nb_decimal,omitempty"`
	Symbol    *string `json:"symbol,omitempty"`
	TokenName *string `json:"token_name,omitempty"`
}

// RealEstateWriteRequest Whole asset in one payload. The sections are written in a single transaction, so the request either creates a complete asset or changes nothing at all.
type RealEstateWriteRequest struct {
	// Address Full postal address. Served only to a MANAGER or an ADMIN; the public answer carries RealEstateLocation instead.
	Address RealEstateAddress `json:"address"`

	// Configuration Share configuration. total_valuation is absent on purpose: the database computes it from total_shares x price_per_share and refuses any write, which is what keeps the three values from ever disagreeing.
	Configuration *RealEstateConfigurationInput `json:"configuration,omitempty"`
	Description   *string                       `json:"description,omitempty"`

	// EstateTypeId Identifier from ass.real_estate_type. Required: the column is NOT NULL, so an asset without a type cannot be stored.
	EstateTypeId int     `json:"estate_type_id"`
	Imageurl     *string `json:"imageurl,omitempty"`

	// IssuerId Identifier from ass.issuer, the legal vehicle issuing the shares. Required: the token represents a stake in an issuer, never in the walls themselves, and the column is NOT NULL since migration 000016.
	IssuerId int                     `json:"issuer_id"`
	Media    *[]RealEstateMediaInput `json:"media,omitempty"`

	// Specification Physical description. Measures travel as decimal strings for the same reason as amounts: a surface stored as NUMERIC must not come back rounded by a JSON parser.
	Specification *RealEstateSpecificationInput `json:"specification,omitempty"`
	Title         string                        `json:"title"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignInResponse defines model for SignInResponse.
type SignInResponse struct {
	Data    *JwtToken `json:"data,omitempty"`
	Message string    `json:"message"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"fullName"`
	Password string              `json:"password"`
}

// SignUpResponse defines model for SignUpResponse.
type SignUpResponse struct {
	Data    *JwtToken `json:"data,omitempty"`
	Message string    `json:"message"`
}

// TokenDetails defines model for TokenDetails.
type TokenDetails struct {
	// Address The address of the token contract
	Address string `json:"address"`

	// Decimals The number of decimals for the token
	Decimals int `json:"decimals"`

	// ExplorerUrl Direct link to the token on Etherscan
	ExplorerUrl string `json:"explorerUrl"`

	// Name The name of the token
	Name string `json:"name"`

	// Symbol The symbol of the token
	Symbol string `json:"symbol"`

	// TotalSupply The total supply of tokens (in wei format)
	TotalSupply string `json:"totalSupply"`
}

// TokenInfos defines model for TokenInfos.
type TokenInfos struct {
	// OnbehalfTransactions A list of transactions performed on behalf of the identity
	OnbehalfTransactions *[]TxHashName `json:"OnbehalfTransactions,omitempty"`

	// Address Address of the token contract
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`

	// ModularComplianceAddr Address of the modularCompliance contract
	ModularComplianceAddr *string `json:"modularComplianceAddr,omitempty"`
	NbDecimal             int64   `json:"nbDecimal"`

	// Salt Deployment salt used for the token
	Salt *string `json:"salt,omitempty"`

	// Symbol Symbol of token
	Symbol string `json:"symbol"`

	// TokenName Name of token
	TokenName string `json:"token_name"`
}

// TrexSuiteInfos defines model for TrexSuiteInfos.
type TrexSuiteInfos struct {
	ClaimTopicsRegistry     ContractDetails `json:"claimTopicsRegistry"`
	IdentityRegistry        ContractDetails `json:"identityRegistry"`
	IdentityRegistryStorage ContractDetails `json:"identityRegistryStorage"`
	ModularCompliance       ContractDetails `json:"modularCompliance"`

	// Salt The salt used for the TREX Suite deployment
	Salt                   string          `json:"salt"`
	Token                  TokenDetails    `json:"token"`
	TrexFactory            ContractDetails `json:"trexFactory"`
	TrustedIssuersRegistry ContractDetails `json:"trustedIssuersRegistry"`
}

// TxHashName defines model for TxHashName.
type TxHashName struct {
	// OperationName The name of the operation performed
	OperationName string `json:"operationName"`

	// TransactionHash The hash of the transaction that performed the operation
	TransactionHash string `json:"transactionHash"`
}

// User defines model for User.
type User struct {
	// CountryCode ISO 3166-1 alpha-2, copied from the latest approved KYC. Null until a KYC has been approved. Read-only: the user cannot change it.
	CountryCode *string `json:"country_code"`

	// CreatedAt Date de création du compte
	CreatedAt time.Time `json:"created_at"`

	// Email Email de l'utilisateur
	Email openapi_types.Email `json:"email"`

	// FullName Nom complet de l'utilisateur
	FullName string `json:"full_name"`

	// Id ID unique de l'utilisateur
	Id int `json:"id"`

	// KycExpiresAt The date when the KYC expired
	KycExpiresAt *time.Time `json:"kyc_expires_at"`

	// KycStatus The KYC status of the user
	KycStatus *UserKycStatus `json:"kyc_status,omitempty"`

	// KycVerifiedAt The date when the KYC was verified
	KycVerifiedAt *time.Time `json:"kyc_verified_at"`

	// LastConnexion Date de la dernière connexion
	LastConnexion *time.Time `json:"last_connexion"`

	// Role Permission level of the account. The same value is carried by the JWT, which is what the server actually enforces; it is repeated here so a client can hide an action it is not allowed to perform without having to decode the token.
	Role *UserRole `json:"role,omitempty"`

	// UpdatedAt Date de dernière mise à jour
	UpdatedAt time.Time `json:"updated_at"`
}

// UserKycStatus The KYC status of the user
type UserKycStatus string

// UserRole Permission level of the account. The same value is carried by the JWT, which is what the server actually enforces; it is repeated here so a client can hide an action it is not allowed to perform without having to decode the token.
type UserRole string

// GetTrexSuiteInfosParams defines parameters for GetTrexSuiteInfos.
type GetTrexSuiteInfosParams struct {
	// Salt Salt used for the TREX Suite deployment (optional, uses default if not provided)
	Salt *string `form:"salt,omitempty" json:"salt,omitempty"`
}

// GetListKycVerificationsParams defines parameters for GetListKycVerifications.
type GetListKycVerificationsParams struct {
	Status *GetListKycVerificationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	UserId *int                                 `form:"userId,omitempty" json:"userId,omitempty"`
}

// GetListKycVerificationsParamsStatus defines parameters for GetListKycVerifications.
type GetListKycVerificationsParamsStatus string

// CreateIssuerJSONRequestBody defines body for CreateIssuer for application/json ContentType.
type CreateIssuerJSONRequestBody = IssuerWriteRequest

// PatchIssuerJSONRequestBody defines body for PatchIssuer for application/json ContentType.
type PatchIssuerJSONRequestBody = IssuerPatchRequest

// CreateIssuanceOrderJSONRequestBody defines body for CreateIssuanceOrder for application/json ContentType.
type CreateIssuanceOrderJSONRequestBody = CreateIssuanceOrderRequest

// CreateRealEstateJSONRequestBody defines body for CreateRealEstate for application/json ContentType.
type CreateRealEstateJSONRequestBody = RealEstateWriteRequest

// PatchRealEstateJSONRequestBody defines body for PatchRealEstate for application/json ContentType.
type PatchRealEstateJSONRequestBody = RealEstatePatchRequest

// PostAuthSignInJSONRequestBody defines body for PostAuthSignIn for application/json ContentType.
type PostAuthSignInJSONRequestBody = SignInRequest

// PostAuthSignUpJSONRequestBody defines body for PostAuthSignUp for application/json ContentType.
type PostAuthSignUpJSONRequestBody = SignUpRequest

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody = CreateIdentityRequest

// AddClaimToIdentityJSONRequestBody defines body for AddClaimToIdentity for application/json ContentType.
type AddClaimToIdentityJSONRequestBody = AddClaimRequest

// CreateTokenContractJSONRequestBody defines body for CreateTokenContract for application/json ContentType.
type CreateTokenContractJSONRequestBody = CreateTokenRequest

// BurnTokenAsyncJSONRequestBody defines body for BurnTokenAsync for application/json ContentType.
type BurnTokenAsyncJSONRequestBody = BurnTokenRequest

// MintTokenAsyncJSONRequestBody defines body for MintTokenAsync for application/json ContentType.
type MintTokenAsyncJSONRequestBody = MintTokenRequest

// PostKycVerificationsJSONRequestBody defines body for PostKycVerifications for application/json ContentType.
type PostKycVerificationsJSONRequestBody = KycVerificationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List the issuers
	// (GET /assets/issuers)
	GetIssuers(c *gin.Context)
	// Create an issuer
	// (POST /assets/issuers)
	CreateIssuer(c *gin.Context)
	// Dissolve an issuer
	// (DELETE /assets/issuers/{id})
	DeleteIssuer(c *gin.Context, id int)
	// Get one issuer
	// (GET /assets/issuers/{id})
	GetIssuerById(c *gin.Context, id int)
	// Update an issuer
	// (PATCH /assets/issuers/{id})
	PatchIssuer(c *gin.Context, id int)
	// Create a new order in primary market
	// (POST /assets/real-estate/issuance/orders)
	CreateIssuanceOrder(c *gin.Context)
	// Fetch a order in primary market
	// (GET /assets/real-estate/issuance/orders/{orderRef})
	FetchIssuanceOrder(c *gin.Context, orderRef string)
	// Create a real estate
	// (POST /assets/real-estates)
	CreateRealEstate(c *gin.Context)
	// Get all real estates
	// (GET /assets/real-estates/active)
	GetActiveRealEstates(c *gin.Context)
	// Delete a real estate
	// (DELETE /assets/real-estates/{id})
	DeleteRealEstate(c *gin.Context, id int)
	// Get one real estate
	// (GET /assets/real-estates/{id})
	GetRealEstateById(c *gin.Context, id int)
	// Update a real estate
	// (PATCH /assets/real-estates/{id})
	PatchRealEstate(c *gin.Context, id int)
	// Publish a real estate
	// (POST /assets/real-estates/{id}/publish)
	PublishRealEstate(c *gin.Context, id int)
	// Auth existing user and return a JWT
	// (POST /auth/sign-in)
	PostAuthSignIn(c *gin.Context)
	// Create a new user and return a JWT
	// (POST /auth/sign-up)
	PostAuthSignUp(c *gin.Context)
	// Create new Identity contract and add it to the registry
	// (POST /contract/identity)
	CreateIdentity(c *gin.Context)
	// Add a claim to an identity
	// (POST /contract/identity/claims/add)
	AddClaimToIdentity(c *gin.Context)
	// Create a new Token
	// (POST /contract/token)
	CreateTokenContract(c *gin.Context)
	// Withdraw the given amount for the userId in the sharetoken
	// (POST /contract/token/burn)
	BurnTokenAsync(c *gin.Context)
	// Register the given amount for the userId in the sharetoken
	// (POST /contract/token/mint)
	MintTokenAsync(c *gin.Context)
	// Get informations from contract Token
	// (GET /contract/token/{tokenAddress}/infos)
	GetTokenInfos(c *gin.Context, tokenAddress string)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Add a payment
	// (POST /payments/add)
	PaymentAdd(c *gin.Context)
	// Configure the Authority contract with the implementations addresses
	// (POST /trex/init/authority/configure)
	ConfigureAuthority(c *gin.Context)
	// Deploy identity factory
	// (POST /trex/init/contract/factory/identity)
	DeployIdentityFactory(c *gin.Context)
	// Deploy TREX factory
	// (POST /trex/init/contract/factory/trexFactory)
	DeployAndInitTrexFactoryAsync(c *gin.Context)
	// Deploy all contracts implementations
	// (POST /trex/init/implementations)
	DeployAllImplementationsAsync(c *gin.Context)
	// Deploy the TREX Suite contracts
	// (POST /trex/init/suite/deploy)
	DeployTrexSuiteAsync(c *gin.Context)
	// Get deployed TREX Suite information
	// (GET /trex/suite)
	GetTrexSuiteInfos(c *gin.Context, params GetTrexSuiteInfosParams)
	// Get the list of KYC verifications
	// (GET /users/kyc/verifications)
	GetListKycVerifications(c *gin.Context, params GetListKycVerificationsParams)
	// Create a new KYC verification
	// (POST /users/kyc/verifications)
	PostKycVerifications(c *gin.Context)
	// Get a specific KYC verification by ID
	// (GET /users/kyc/verifications/{verificationId})
	GetKycVerificationById(c *gin.Context, verificationId int)
	// Get the currently authenticated user
	// (GET /users/me)
	GetCurrentUser(c *gin.Context)
	// Save a real estate in favoris for one user
	// (DELETE /users/{userId}/favorites/real-estates/{realEstateId})
	RemoveFavoritesRealEstateForUser(c *gin.Context, userId int, realEstateId int)
	// Save a real estate in favoris for one user
	// (POST /users/{userId}/favorites/real-estates/{realEstateId})
	AddFavoritesRealEstateForUser(c *gin.Context, userId int, realEstateId int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetIssuers operation middleware
func (siw *ServerInterfaceWrapper) GetIssuers(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetIssuers(c)
}

// CreateIssuer operation middleware
func (siw *ServerInterfaceWrapper) CreateIssuer(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIssuer(c)
}

// DeleteIssuer operation middleware
func (siw *ServerInterfaceWrapper) DeleteIssuer(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteIssuer(c, id)
}

// GetIssuerById operation middleware
func (siw *ServerInterfaceWrapper) GetIssuerById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetIssuerById(c, id)
}

// PatchIssuer operation middleware
func (siw *ServerInterfaceWrapper) PatchIssuer(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchIssuer(c, id)
}

// CreateIssuanceOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateIssuanceOrder(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIssuanceOrder(c)
}

// FetchIssuanceOrder operation middleware
func (siw *ServerInterfaceWrapper) FetchIssuanceOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderRef" -------------
	var orderRef string

	err = runtime.BindStyledParameterWithOptions("simple", "orderRef", c.Param("orderRef"), &orderRef, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderRef: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FetchIssuanceOrder(c, orderRef)
}

// CreateRealEstate operation middleware
func (siw *ServerInterfaceWrapper) CreateRealEstate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRealEstate(c)
}

// GetActiveRealEstates operation middleware
func (siw *ServerInterfaceWrapper) GetActiveRealEstates(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActiveRealEstates(c)
}

// DeleteRealEstate operation middleware
func (siw *ServerInterfaceWrapper) DeleteRealEstate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRealEstate(c, id)
}

// GetRealEstateById operation middleware
func (siw *ServerInterfaceWrapper) GetRealEstateById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRealEstateById(c, id)
}

// PatchRealEstate operation middleware
func (siw *ServerInterfaceWrapper) PatchRealEstate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchRealEstate(c, id)
}

// PublishRealEstate operation middleware
func (siw *ServerInterfaceWrapper) PublishRealEstate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublishRealEstate(c, id)
}

// PostAuthSignIn operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthSignIn(c)
}

// PostAuthSignUp operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthSignUp(c)
}

// CreateIdentity operation middleware
func (siw *ServerInterfaceWrapper) CreateIdentity(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIdentity(c)
}

// AddClaimToIdentity operation middleware
func (siw *ServerInterfaceWrapper) AddClaimToIdentity(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddClaimToIdentity(c)
}

// CreateTokenContract operation middleware
func (siw *ServerInterfaceWrapper) CreateTokenContract(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTokenContract(c)
}

// BurnTokenAsync operation middleware
func (siw *ServerInterfaceWrapper) BurnTokenAsync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BurnTokenAsync(c)
}

// MintTokenAsync operation middleware
func (siw *ServerInterfaceWrapper) MintTokenAsync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MintTokenAsync(c)
}

// GetTokenInfos operation middleware
func (siw *ServerInterfaceWrapper) GetTokenInfos(c *gin.Context) {

	var err error

	// ------------- Path parameter "tokenAddress" -------------
	var tokenAddress string

	err = runtime.BindStyledParameterWithOptions("simple", "tokenAddress", c.Param("tokenAddress"), &tokenAddress, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tokenAddress: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTokenInfos(c, tokenAddress)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// PaymentAdd operation middleware
func (siw *ServerInterfaceWrapper) PaymentAdd(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PaymentAdd(c)
}

// ConfigureAuthority operation middleware
func (siw *ServerInterfaceWrapper) ConfigureAuthority(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfigureAuthority(c)
}

// DeployIdentityFactory operation middleware
func (siw *ServerInterfaceWrapper) DeployIdentityFactory(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployIdentityFactory(c)
}

// DeployAndInitTrexFactoryAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployAndInitTrexFactoryAsync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployAndInitTrexFactoryAsync(c)
}

// DeployAllImplementationsAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployAllImplementationsAsync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployAllImplementationsAsync(c)
}

// DeployTrexSuiteAsync operation middleware
func (siw *ServerInterfaceWrapper) DeployTrexSuiteAsync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeployTrexSuiteAsync(c)
}

// GetTrexSuiteInfos operation middleware
func (siw *ServerInterfaceWrapper) GetTrexSuiteInfos(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrexSuiteInfosParams

	// ------------- Optional query parameter "salt" -------------

	err = runtime.BindQueryParameter("form", true, false, "salt", c.Request.URL.Query(), &params.Salt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter salt: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTrexSuiteInfos(c, params)
}

// GetListKycVerifications operation middleware
func (siw *ServerInterfaceWrapper) GetListKycVerifications(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListKycVerificationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameter("form", true, false, "userId", c.Request.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetListKycVerifications(c, params)
}

// PostKycVerifications operation middleware
func (siw *ServerInterfaceWrapper) PostKycVerifications(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostKycVerifications(c)
}

// GetKycVerificationById operation middleware
func (siw *ServerInterfaceWrapper) GetKycVerificationById(c *gin.Context) {

	var err error

	// ------------- Path parameter "verificationId" -------------
	var verificationId int

	err = runtime.BindStyledParameterWithOptions("simple", "verificationId", c.Param("verificationId"), &verificationId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter verificationId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetKycVerificationById(c, verificationId)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentUser(c)
}

// RemoveFavoritesRealEstateForUser operation middleware
func (siw *ServerInterfaceWrapper) RemoveFavoritesRealEstateForUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "realEstateId" -------------
	var realEstateId int

	err = runtime.BindStyledParameterWithOptions("simple", "realEstateId", c.Param("realEstateId"), &realEstateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter realEstateId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveFavoritesRealEstateForUser(c, userId, realEstateId)
}

// AddFavoritesRealEstateForUser operation middleware
func (siw *ServerInterfaceWrapper) AddFavoritesRealEstateForUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "realEstateId" -------------
	var realEstateId int

	err = runtime.BindStyledParameterWithOptions("simple", "realEstateId", c.Param("realEstateId"), &realEstateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter realEstateId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddFavoritesRealEstateForUser(c, userId, realEstateId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/assets/issuers", wrapper.GetIssuers)
	router.POST(options.BaseURL+"/assets/issuers", wrapper.CreateIssuer)
	router.DELETE(options.BaseURL+"/assets/issuers/:id", wrapper.DeleteIssuer)
	router.GET(options.BaseURL+"/assets/issuers/:id", wrapper.GetIssuerById)
	router.PATCH(options.BaseURL+"/assets/issuers/:id", wrapper.PatchIssuer)
	router.POST(options.BaseURL+"/assets/real-estate/issuance/orders", wrapper.CreateIssuanceOrder)
	router.GET(options.BaseURL+"/assets/real-estate/issuance/orders/:orderRef", wrapper.FetchIssuanceOrder)
	router.POST(options.BaseURL+"/assets/real-estates", wrapper.CreateRealEstate)
	router.GET(options.BaseURL+"/assets/real-estates/active", wrapper.GetActiveRealEstates)
	router.DELETE(options.BaseURL+"/assets/real-estates/:id", wrapper.DeleteRealEstate)
	router.GET(options.BaseURL+"/assets/real-estates/:id", wrapper.GetRealEstateById)
	router.PATCH(options.BaseURL+"/assets/real-estates/:id", wrapper.PatchRealEstate)
	router.POST(options.BaseURL+"/assets/real-estates/:id/publish", wrapper.PublishRealEstate)
	router.POST(options.BaseURL+"/auth/sign-in", wrapper.PostAuthSignIn)
	router.POST(options.BaseURL+"/auth/sign-up", wrapper.PostAuthSignUp)
	router.POST(options.BaseURL+"/contract/identity", wrapper.CreateIdentity)
	router.POST(options.BaseURL+"/contract/identity/claims/add", wrapper.AddClaimToIdentity)
	router.POST(options.BaseURL+"/contract/token", wrapper.CreateTokenContract)
	router.POST(options.BaseURL+"/contract/token/burn", wrapper.BurnTokenAsync)
	router.POST(options.BaseURL+"/contract/token/mint", wrapper.MintTokenAsync)
	router.GET(options.BaseURL+"/contract/token/:tokenAddress/infos", wrapper.GetTokenInfos)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/payments/add", wrapper.PaymentAdd)
	router.POST(options.BaseURL+"/trex/init/authority/configure", wrapper.ConfigureAuthority)
	router.POST(options.BaseURL+"/trex/init/contract/factory/identity", wrapper.DeployIdentityFactory)
	router.POST(options.BaseURL+"/trex/init/contract/factory/trexFactory", wrapper.DeployAndInitTrexFactoryAsync)
	router.POST(options.BaseURL+"/trex/init/implementations", wrapper.DeployAllImplementationsAsync)
	router.POST(options.BaseURL+"/trex/init/suite/deploy", wrapper.DeployTrexSuiteAsync)
	router.GET(options.BaseURL+"/trex/suite", wrapper.GetTrexSuiteInfos)
	router.GET(options.BaseURL+"/users/kyc/verifications", wrapper.GetListKycVerifications)
	router.POST(options.BaseURL+"/users/kyc/verifications", wrapper.PostKycVerifications)
	router.GET(options.BaseURL+"/users/kyc/verifications/:verificationId", wrapper.GetKycVerificationById)
	router.GET(options.BaseURL+"/users/me", wrapper.GetCurrentUser)
	router.DELETE(options.BaseURL+"/users/:userId/favorites/real-estates/:realEstateId", wrapper.RemoveFavoritesRealEstateForUser)
	router.POST(options.BaseURL+"/users/:userId/favorites/real-estates/:realEstateId", wrapper.AddFavoritesRealEstateForUser)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3IbR5rgVTKwEzF2RBEEKUo24T9LU7Kbbb1WpNrraXkYiaoPQDYTmeXMLIJohSLm",
	"EHOA/Tl7jr7JnGQjv3xUFlCFB0VS0rY6YsYiqiqf3/v5vpfLWSkFCKN7w/c9nU9hRvGfJ6/P3oAupdBg",
	"/yyVLEEZBviwoIba/4qKczri0BsaVUHWu9mTtGR7uSxgAmIPboyie4ZO8KO/aSl6w14mZ8zArDSL3ocP",
	"WW8GWtMJzmEWJfSGPW0UExN8qOCPiikoesO/xhd/z8KLcvQ3yE3vQ9Y7KYpTTtnsDfxRgTarC87t0wtZ",
	"shyXDzpXrDQMF3QxBWLsIyLHxEyB4MvkG+hP+hn5joylIr/8dvptL+vBDZ2VdrvfxUUwYWACyq6i0qDO",
	"CjtBfO9gYP+3+vLS3vyXWbrO9fusb4Zy/mrcG/71fe9fFIx7w97/2K8vdd/f6H56nR+yrvtcN8LFzZ+o",
	"nr6kM8DlL63t9w9Z78dKiQt5BaLzGuhMVsK0X4F7hndgx9DESDKqlMgIE2RazaiwNzGjhnwjpCFzYN/2",
	"if1QudkI00TBuNJQEEXNFBQxUyoILUslb9iMGijIfAoC79jPllNhBxsByaW4BmXfgRuaG74YEmbIrNL2",
	"JaUWhBoyk9qQg8dEs4lgY5ZTYUjBJszojGhDF2QEXM7J8WDw3cHx8eHjo++OBsfHhxmhoiBTeg1ESDKT",
	"CkgBOZtRrt0SDULgFQj7O6cKdNiZrjhubK6YMXbpklBB2GxWGYt3hEMxAZURjb/7TZmpXSso4As7BMxG",
	"HDROIkU8LihwXKk0+HMiCuxdMin6KahbEO5//13Wc6ffG/YKWVmcz3ozesNm1aw3XNrxQdabMeEe1cAv",
	"qtnIIYqRHSBQFAp0vPn6XOxP6Zp6g5uDw0dHj5989/3xgI7yAsZdf/eyZbpi578CcSqFUTQ3J27S9Svy",
	"lMFdUu6/vLMVLVGD1uXhqWUBg9qIQ4J+nyN1OJVizCaVgpPKTKViZvHZrhMP/ikYyrhuIWI7AMydg4od",
	"p+RSgXqr+OoSnjIFuSGciSuLRekSiBTkmSWLOqeisZ6pMaUe7u9rKCVntA/hrT6T+35D+x+3aGEPvPXA",
	"7JN9+/7aIzsrQBhmFhtxh0Z0wSnb8ORUATUQRuwWGSyiqcWpLFpWfnb+ijw6ePJk74CIagaK5Rmhmmgj",
	"FRT2pPMpZYKMFrileq4J00YtyDcVE+bgSUOkODo6XC9UrJ6dfUbOnoaTY+Ia7Aoa1BsvZaMAkm42zrnN",
	"4T08Boe5z8RY6k4kdsvUuqIih1eqANV50X9U1MFWLYIm56+A8mfa4Kbb3lg6yMbrWT32mrNsLvITHGi6",
	"gPUHul66E6OnTqxZhdaXyPstoAbJpwGk37dBvl7MRrJlrFdiz2GX48b+tZRaXLx69YsTT56DmJhpb/h4",
	"0CUGvGylTPbXBtNvjP/2fPDou+8fPToYDB435zkYDLbi7jhr3GKWHF03oHw63m4nXotuTZzcjZReIM3H",
	"F4hVHNdRsw4ayfz0u4hyOZ5pQVjNWVIO7Vja5v/fKl4qKjRFSdoKG+3LmVI9jRBWf7AsKDyG7x8f0Ucw",
	"gMODo+NDOH70/QEcD8ZH9NFR/uTx8ZPjJ0+KR+MxFHn+5DA/+A4O4LvBd4cHg4Pjg4PjtuXdE0fJenPK",
	"OayXp8OA/6qJeztey3//x3/ilJxqQw4HZLQwEC/rCvKcXh0+fhJ+KKsRZzm5gkVGrALX/I0wo4GPnRKV",
	"/qyJgGtQnk//4NRBZtwDKCw4eD0yl9dgWflYyRmhqPFRUynovxP3JfYvQ/HygWZLXHoZzNby7TPBDKOc",
	"/T3y7p9obqT6JCx8WcTuoioNxrRKVRwGnyAnqpVTamDPMCSvK6DvP/mxg9ezov136VjzuMVItVlAyHr2",
	"YaUD9VsZwD1e//HZ+CcmHGP1r4yk5EBF/cpzOgLeOgFynP+1VsqpymLXs6zJyLbGrXiMy0vKlsWm+mrT",
	"O2uFa60rBxyrxIbDhHJyDVOWcyBM64qJCZIKPaUKdCKy98kblkeT0Zt6NTh8RuZTlk8tZXDkms1mUJBr",
	"BnMCsxEUSDkEoYHYUK3BOFLRygkv801aBeXllO4drgHiS7rDZXVBNh7RpR2jFXI4sI6lPsezfYb35/Wb",
	"MbMndTggVVmC2supBrcNryHpdYphK1pdAl7CZd5uNfyTnJMZFQsipNgrgIPl53j0mlAFhBpD8ykUThNm",
	"GkEAVJ+cOZvalBpigHNNqB2HTkBZjoCmwzkz00LRuYUYZhwb0KCuWW4hiZRSazbinh20aQ2o6VG70ktv",
	"+FpZ/5vkJeJeslBkQexvlWK6YEjcLc9rwE3WRUNWpzjH351cZTlsoejYZMRyjWvIiK50CcJCr1SkYFpL",
	"fg1F9wSXrEVuqG/fc0ut++6kL/2ysm6KswMUr7DLoOQ3wDjrLZ1VvfJ4TN2E5DU1+TRRcJo7/YkBL9A8",
	"mU+pmECfnAgiZ8xYwBvbh+QKoNRW/iB5pRQIQ64pr+AHQgWROA7l/lVtn6IjxEJUzoFaQnQHRCNzGEgs",
	"BrbdZRPpl7WXGRPx72w9SejE5mTMw8ePN47ZgS3rgbCF63Rc6q+KGei+1IpzUsCYWQnJYRsVkVTYHWWk",
	"PjE05acXgpQmwOWQ0MhvLAWRlSHUj0E9P8JRpCK0ieRuUSPQVp6dWrJjV+HFZTsjLwha9KV4eBhZIion",
	"GTk/efM8I+en52VG3pyc/dTv91s04R1gaSv2gjTM+2fWcZr+O3HC53ShI87Zm3n+7MximhR8Yel9Qa38",
	"i+49lIgZaFKJAhSZUXUFhigopTL2KuSIswmCp7ZXN59KDURDXin3GXKbwhMCy20ULZiYOL9MhIiS0xwK",
	"Uip2TQ3gIhYWKJhB7xRfBB+RgMCjJlyOKOcLUgn2RwVkZHVkoY2qEGr8BEVVcpZTA4kPrMGZ7gtD74Sf",
	"RdXvzel58tnz6gZmI1mpSf8d2pwY6mMWc4RnYB5LU6zrYP8Wa1E20/YHf8uVRs8f8+CFDjUmkHi7/TYk",
	"vwQd/9UD0ZwuHDOA/Mp53ZghcMO00X1yEtekDeOcjABlCZFLVUqFtodCOnR39y4FkAUYvFOnhgYbBbUS",
	"CrJu8k2kgeTgW9zWxO7XrtkfXXRxhj3YM2ETYV/qvxNvHSBZ6uT3mt5Nn1zMpT9WjWIygr+AcJGazmpz",
	"jSN9zuVqByRHg2MHdwl4PTm6Y3GiT57CmFbcICf2kPDN4bdEWgkcz4xJ8YPlrwU5sO9YpuzsGThOep7z",
	"KbO3jsfddU/I5v2nicPYX04Um8g3R9+2y4NLkstGoaVNPvnz3KAdblUPhpuSKdC76G4Kxgr0NA7YrjK2",
	"PrHa3Cb9/q1u2XUwozbm9uNlySbaNv/LIv8LKHS5OyjpsAXspBMVkLMifrOqPtqPEcPsADVa/fLbKblO",
	"FkPmVBM/Vi/bce7Ron3u2gSHFrn5VIYpWtfQKmH7WILiclk2aFuNe3NccX7ZqZLBjLJ2C4O/vY8+Sj/O",
	"1sfYpdbGSIZLBVQ7gFldlXuGLMV/4M0D3cebotC1dE+3n+NaXu06xdUdAagfa+uTDXPvAKD+k+0BtFZa",
	"V/lDNXLS1J1sPo629fZ3104dJbvsgsh0TZdJzFtzYydFwbyO6N8hCDgRhuwWG9tb1rDr5TRm3GAf8Fe5",
	"cng+Bq4E4cRZjKW6hiLzCAPFt9vp6eFs4qW3Ep0umtWweTUuJxClLZhGp9uyk05u0qEabqslB2FTBjps",
	"CNiHWa+kxoCyw/77X0/2/u3394cf/qWDT7RQ5nqiP8upIE/lZmvJDqe91Vnej9Og+es/L860rWP1Wtq9",
	"Ji+YMHcbhTljwnyNwvxnjMK0N/81CnOnKMwE/T7H6MbatbX9uupvzqvZjKpFy+qSoMjthgonaqX46MPb",
	"7lPv88PkgYLhoTADsx0mf4Hf1SdElaJ2V71oI9pJ8ova8nazO9X3tj6Q5UvN2uzZCignznuGwQyqQO8V",
	"FCEksUDXOwFRlJIJ4yidNgqSkIxgKx0zzoPpjbw4eXny87M3xNnhTp6+OHs5dDbUa1ALS9qAIzED7+Zg",
	"mtCRBstCRpDTSgOhpFSQM11jdskErkMT6tCb/T348vrv8KxWIafdkl9KbSgPA/fJuds2bsTS7bYN/JDG",
	"j1Ch52joUYqBTnzBz72+R5jQBmi7q6bpYU+ctrs7fmuq9vxtq4meGmaqtuGeWd4ZuFtGXr598ezN2ek3",
	"x9mTb+2BGGLkpHZzEi7FBEeyZ2IZMTWEct7gP72j4/6Tg4Mnh60u6TjCx6/Fb2rdUp70Dx4dHD963LYS",
	"d/3dpg4FE29AarFJWuhf8+jSYjWHGQizOV3Jj9ZcUeYAZAtz3wq4o2eyVfpFBBqvuCbP6QzCzzSFY/9J",
	"ho6GxHWF/nDmDNLom+zwZd433K8F9PWg93mBw5pLDckQ0Zy5dKsoX2iUWDFWxamazq/hKBN6BTxaETep",
	"7pM/n796SaZo39ZMTDiE8HRiFxO8GShBl1RpUFZap97DMGKCqgVxguWQHBwf94+PSS5noMmI5lf2Lffj",
	"YHDgxGkqFsRbOQgdyWsgh//++BEa0xkHYazsKytRQBE5DFrXkc4rKnQplfEaRR3Jl6YDWLGnFeIQJPN1",
	"kHV0ePBdg3A8e/umlWbQhb3EyzEK5SLviJFaee3SvfN+ixHx1U7jUKlYDpclqEu87A1E1CsYNS09HGTf",
	"N1IJeu6W2kUViw8u/qlrnnCh+co0g6VpHg8G3ZNYYtEB3+kqyA1Z2n9mYa6sTCKtUENHzlNdz354fHz8",
	"fSsTWFiq1xCpxlyitWhJCdoBSc9EWbXozOceO5M3+2Rp/7UIRKQgZaVKqWHY2FjYsY7BRuuPCJHP6dka",
	"kdCqppB4K5GYOwKOGDVVAI58azc+xsEWTNOJAmBi0h5UMCupMgjKyoU/Lrnpo4+WJO/ahYFFTsiC35rm",
	"SmrtvbOtQW3boXOfRE8wigsotykMyjKEliW3IpuRw0QPD3EYNR/LF2QGVMRIC0fKCudU9AFfcx9wgaIz",
	"rT8UciSLBcmnUq/EAneQF0AGOAa4VF7tau7tNagchKETICMwcwBBBriig3bsghtm7nC4Gb25dI7tDk6W",
	"9WaT2Z3OyMSmGVtJckf0n9WUNClB2f9j0jkgFkH3KCkr2qAGXxiivcVUSrgHQhI1XZjprGGSsoAdwggk",
	"iqpSLF9+amw5yLbmHlt7wNs/zxwC1NuOj4PAwESy+WANRSe+s5AOybve0bseodwKg5ouIlbsvMHtmFgp",
	"NUOP/YpKcNdsLM7kF3kbThY5yZJ8JkRFeQAyYW/AYkBTYeofPt7CyJTsY/UMl+liG2KsA63ft+dvHfpF",
	"C39r0TUazApjbZbZlYI6/HEKCjkDZ1eQBG1AbSAwU1gQyq1o6oOiqGNeIZpjS261mc1sQa03E+A7oal3",
	"RiZ3pD1bYfJGBOzGnJ30oo8J5+/fS7T9LSPnO4MoOp3e6w8mGJ9Wt3EqrSJHuH8hI5qOEU/gxsqZ3qzF",
	"F6mJz/MNZypzUayi8NnXUhVMUOOjGqeWwlnlb+iQMhjq2u10n84ctv70XgQ78ZLRmptLAzftuNV18Uxf",
	"YnJYey4OWqSjYtjcFpvRCWTkmhUgMzLmUqqSU0GkItdMmYrySyMr1WHWYqZpqUhj6RXfGaDwSKJSs8u5",
	"JPtf4oreN2clCTwHFMoQODDUdQQexK5B9etd3u3pNaMD8aOm9RB/2nTGLY6zbc67kfak+Ab+uz7Z4DVV",
	"hlFOnJOgT55dg1rUNvXITZ0ZJqYhYKymJhzGhlTCyCqfQuEM3Nr5FR1iz0BNYtbCyA+cEbjJoTT++qI2",
	"qcDHLqOdaD6VvNUKeFsnkJM9kCwsmcW2G6ZFkPmw5BZpY+MuuWgtK0Rgab/u4Lfq/DY6p5ajpPEsnV6O",
	"R0kmlHNQiz45B3eZLisEvVIoZnGgijBjAfk2ni6H5i3uLl1C3oiq3NINmH5WD84M3z22fD2Veq3kxEJI",
	"a9Cnc0pfatkmop87YXTqwVtIsZdTkQO6spjPLCWYkqhdgG/QEqKXSrjHJBRxiFHg+OIPwaeUiL4CoEDb",
	"K26uKzksWfdlmZvJx1uqzpfvsXlQI2qmSsrZam5NsqoRFJvfqRgvLhdAO56DADVZXOactvnnnuFTyxRw",
	"t/b88c2MnFgo/7lBpk/bSPQEdNfgPysAMZX24iZUrxn4absDy1xq9nfY5iosp5B8h9d1pcY0h0uqgG73",
	"hQGl7BfbzrEDdHTYMV9PF5rllJPk5z55AVRXFrCNotfAW1wObTYF5BLOgzG0yOC2H4rjUB30cBfXI6RB",
	"H4NzMXhvgUVZ6rwZzk/Rxm5awHo9314F8Q3vN8C9Nn+0lvTbBP13AOO3gebEIPF40C72JMDcEojbhN3E",
	"ZHL4fb99xGXo3YnihxCTFr5ZhzRQvRTOwJk2STDDU+BsBMolVcFNzqvCM9xmiIPTg5yw45lw1kgU8VoR",
	"Uuxhnd+N0yH0eiXLD81yQzyYtMpHmKvSItrquDH3RptsfBeykR8HQ5ouO+uYndThVn5ZUpARl/mVq7vz",
	"DR7Ht3eVm76DnHZ7Oe428h2XuwpGUUtHK0pDdNlugFTeuSP5bF16+HM2hnzhctTqRPFvfJY4E5cKrhnM",
	"szp3LiPjShSKMo2OkzFS64zkXGr8bxCxvt2YRN4iFwUBcmNA+Xq9KqY1rdqQnr053Xv05OhRUhXPuZmd",
	"CYOcODdddA8lRo4FmP46jWdrA4IYXRZ1nax1da/aA826EnTW09X1SdC/oh7iVHUmUIks6YJLGvz2qeoY",
	"wmCx4oUPM0iK0WAcrElCgoGh08TRBiseu8AJEyaUyhuSk9xnF/ZzhzrmXZHQqO4ska1U6RkM2sqNrdKp",
	"zW6ftAqG/bB25gy9LYVXM3Qwv3x1QV6+ff48RiHj0dZJ6BhTUXu1fNmTDg0lJYuNKmpt+2qowdvmcjo2",
	"u9Gku7RdF/mroFRg8dSpWvQKs1Nj0n7mizz5jNU55RjhDTMN/BqrvkRb5/LhWWjOgczYxLs6BoPB4OBJ",
	"1zF9VPjpZ66UN7xUOEiWFNdcguUUCNpo8zmbiLPuhISYWFhLl1QY+T/9n/1cztLMLfd6ayCP1nOpmiW4",
	"e7oqQWnIFYbjxVHiy5t2H6aLH6zb4cPHfMfE4I6Ib7uyt+W9n/244vzlSn7SiTBSLMhzGP/jv64VPNyl",
	"xeVk29+fPaXP7/7w4Z0UI76nvAmXzYw1Pdsr/K7U/oxGg5XSmu2VQHcteew2ert6x/jtvVY77q4r+mJB",
	"zl1RkQUJ+fGrQnRHWVQU0/DZmgnOLzqjKc6rsuSLrvYIhnKi8Y0kN+wbJsgcmI/fXIqoGHT8b9cSzkmV",
	"1KR2bLrkJoC0YXdSwXQFg16JEUwpH1/UEmyr6QV1frv35L1gy3Q1n904sXZmXVh0K/Egzd1ZFQq2Udbv",
	"FcdvUW2x0zEii4pTdWq1AGYVRruHjTtb+eo+dtkoYdygSnHLTJgnR+357JS3qFZPoeQS4y+IfYFgamQn",
	"Aey5gMk9++reweGjXSjAeY39K8PuUhL5Uqyvibwy+I9sQv4kKw07F0NG2ZEmyXVx+tbiyCkYtuK5gpvz",
	"ihnoKkQc26voUIt951qldbnhOxzi3Ejls5t3HGkFLW4xRjvgIkNZgdiLN8/+N8EzJkWE7AY0zBZIbs8p",
	"Nx0AvFW+XEPuwarKcONr1t5ii0ZV2kDh4otuf/nLST724LJY2mYFMLovunNFWSuQtt1z80ha0aFmKSuo",
	"YP+NquLLrYSV+HrN8pquDMRLdLrixWWECWY6hZiPKZHtMqtrzttY3i15wfHmSM2VasvNE2w7/7e6tW7x",
	"zqX6clmyUIva1cg2oE2sLEB++e20T15WnJNKGMYJxaoEU6rJCEDE9/rkDdBiTwq+GNalW7xNyFngXI2w",
	"1Wir5UZf29avaPoDlhgjRRpCcvWP/+tAq6jQNGiW8jwGh0/2Bgd7g4OLg8PhYDAcDP5t60IuUb1dckXb",
	"n+3k/F8rwzjT1EDVKHN+ey24i33KWTB8rp94C5251db2NCRbrBu9NXT7apFfblXCqVFmx31RtN7V4WDz",
	"XS3D1Mou7bK6PBcXfhG6UYwjFBMT1QwLrUmBMdOuFIeVNDwm9EKpD/xnqMsRy5C5H13BpN/T7fkBW1ca",
	"BtzhBOdUk2Qdq8d48PgOjpFTbS5zKQTctAaQBjzklBSgBPvHf7mIb/9+67oGFwePh48+bl1K8vZkkhlD",
	"BxjhcA1RmaU50k3vjrCcyQWEMx0TIr0v+M+/XiwnQrnoN3UNitDcVFhRE8RYqhz0D7Hmf+kK+k1Bgaur",
	"mXMGrjwJmTIMkiWeBbGYKUs5l3OXHeJZUjS6T+k1mrOxdpssoJb4PY31YPr2/NmbXtbziem9rIdJ6U3I",
	"8+9sKFTVfrH1rc6YBvKP/0P+JpdozkfQ2DaJPi0yFGhlVwmn1ro2vrbq4twKYj7aA6gCdVKZaf3XT2F9",
	"f/71wmoM+HZv6J/Wa50aU/Y+2IGZGLeUPXnBBAa1nLw+c4lAU6DcTF1lz160ovd+rJ3gL1iuZKgIfvL6",
	"zJEU5+3tHfQH/QF2DihB0JL1hr1H/UH/EVohzRT3s++S4fZ9sU370wRabvFHml8ROR7beTjTBv2uCnz8",
	"Q1dJg7RmpS9b33S20FVnig9ik+MfEvguqTJLXTdyaiiXkyrmG2IgnGusMZVz3YigaBRhjZHiT2PRzFBr",
	"lCq3PXxVDpOS7KFOK5baMZJosGR0gQ6f2r+E/sYZzEZ2MIuxQmJhA1D4bfsyUinurOgNez+D8QI5sgBn",
	"2MW7ORwMnPAmjM/GwHRD527Z/5svAOgUh61dQnUlk6a958Oyf7H36hf71tHgYKdFbG25Xp3QIpo9XF/z",
	"IqI4ruLRQ63iTQLnAcqpKByM27U83vFaPmItZ8KKvJS7kiKKPFNKqga1Qm9BSqf++vuH37OeDiFNvedM",
	"mwQ70OSB3XH/GhpZ/O6LFrTkeXj3eQsqB29v7qpYiSWIt3L/JnLxTlzUSJuWHsaApBQdx4xz56Vl2hUz",
	"Z9pXzELPfVwWqmmuGrJL7S85FcLXE0b61KjinFb5qkswN6tJ//d//Gd7refl2s5W9zFyU3Xn/juxRZVm",
	"O5aQYQkLMEN/OphzvK40M+7PvyhFDs2yzFimAUszu7D9NnpUt4hDduYjKn6UxeLOoL6lRv6HJlO38tuH",
	"FXJ4cMcraEM5t31PdB4Q0a8pZ0WIgPlKeNsI79Hg+KHWchGxpkENMhfhQU2ow5kRb6N8/uzMZ7X5FNIo",
	"J+iYwu2Ijqst9WUxEYcUdbxLGxP5kC3Ll/vvWfHBcRUObVn8DXnRRdAomFlteegpbebTJRAQZKMLo3Y1",
	"HzDlyvjSMOHOFv6SqCBcaiDKioh1JBKtCmZCfRgl53Z6nDZ4c+sC647AJsrdmAnKLRWPa8epHCkPFbw8",
	"m6hnjAMOQ7Gvo8FxRgSdWdo/9XUF0FqG5BmDh9L0fz+XVMQdpnthzJQ2jkUFhuxlaEzGqkOxPMfBSK0C",
	"LJv2NXFQnwx9Ymop2TcDCcBcLMnOyZdgoQlLZq4E1InCH4vbsiaHgyPfPkKBQf0Zy6Z6JTinnNf9CUII",
	"P3K7MWU8dsJrsquneByRXZVU0RkY1G7++r7HBEZwmGlw7Q6dttjkNFmCaCuF9H9fYUNHbREBoZHRV8rd",
	"SrmPHozaOQB9KQ35SVai+ASMw+NIG0n48kh/gOz1xD/bbEhw5R+3sSOsU5J/XGC3vodA88EDSJtfdezP",
	"kmB8WSj6Mxifg92NnmV7rZVmxnfmU+oqjgQrChXDNNt7bdO5LOaGb9N4DuUvnxVeCxaoCdVNiDBf2YsN",
	"uIsgVnGg166PjnBB2VZCjc14fDktrORS96d6IYNoEwSqqs7HcKYB797BDlEydC9s71qILyXVx0NDorrF",
	"T5MH1CYDxw365Kn0xb9i7UK3bL833/xJEy5dHw/qpLXxGEJLsGBLqG2P2lBRaDKCKRMFYaZPnqKxINRz",
	"xEP1vSYpJ1gSBx3arnT63Jcyi+YdNLWOVg0ell6fXpz95VnoXPdOnDjrgzPKOBMFSsfentFmX2k7Pi8W",
	"M180BIFyTp35VSxlctQydlxfn7goPfy42RTMp4y6JJEQlO9tJnZRE4nmLiWrybT/TpxaQA35AW2rTzv3",
	"+XZcOkrN0da0ukOqyRw4H9Z130oliyqHjIwWDszd3rEm/SpweyxLVj6SZurn6ZNX9sooef7q/Dyd3isK",
	"UT6RoTyZbxro9qQNXWgyrtBjVTCsN28V35xXhXcuxTtA3/1Jp34QPvfJNUOfOPlHZRHclyl0eVzxMpyd",
	"sQSlZWpQD0Y9l+ejwM+AigbqOrgqpSA3fXIi/BmS6DdbvoF0Q5Z24t25m0B4j7EJGmNS+uStKKSHa9xs",
	"FdZv94kICUVIO7LnrOCaOVrjyrkJr5PO7dVbPkOqMqpRWJRxD+tAkRnD/JI2KQjrTNy3qnNf5r5G6ZGt",
	"zH0PKYB9tfR9Ff8+hb546ujMWKoRKwoQIaIgSFU+GXqcuHC+PAH1bVnsYj5UQPmeS/faD2VT9p0dEEPb",
	"vK+qy21R9++/H3LWMtMn8mK0rqT7Js+rUfwzett0leegNbL7hBS2Ey0V93kL4zERMPflbZggpWL2uW98",
	"m0DESSjYG/a1NXDsvw/t/j8koQ1NMPkJPAtNoWQzJw0Db8NPY5TKfZsU6i10MrYvi07g5RC6BZBshI0G",
	"pej2ajsdwvIe7CViRcE9I/ewMC34uKv2lPPhasazFRZj/pvCP3VLLVMnZY4sRkwpH+8FTPSVn1FKRGWJ",
	"FhDacFdY+vkEUSja+U+e/3ry23nQtDIylXP0oUTpHANonJxBmA4Nnpm4Zpr5yJaoYjrN/fWr8wvSdpzo",
	"y9n3KlYI74kdiaXgDL3Jp6mC4mJ3/N/Y+yopkXIFpSG0pMr0yevKmOBxCPUAxkq6pmC1EuxqYcGNBWBm",
	"rPKTefFZswIIjMfgqiuEeAHqggW8XsAXbo9OIXD5PZgjM0eFAjeEivUIXAMCu/8+OfWnKXx/GlQ/xlIB",
	"zv23qpj4AD4s1uJPGy+R0/zKRwOmjdUVYMlwpz3UFYpcv5qgBmFAopjEbhrKxcYXVpNKzhWB4unZ+fmr",
	"53959nQp+sr12hhXmnKCEYk4H5Y0DGpQSOl3CkoM3w4qGhTN3P40pilqrqGNfB3M1axybpU4akAF6w1+",
	"hIA6o1de83ID4214GLNqo9PkGg4wJw9ZSMhzKGPspKtNv4fBc22H1BHlkLSmuh9ZoaMYxgPLCck2v0Y8",
	"fI146HRcOQpTE5Ei9Wp+mRELaVuyVSGzU3rYr+tmtTq2XtdFuZiY9MlJ6sjC6yM+xtXxIRf4SrnGWNJE",
	"9tCe/nl2UttYQ1t+++YodaMFB7kAS+ismCKt+BIKkbU7z9Awm5C7h4k1bevit2XY6WcHbR+yzU4Y2myD",
	"p3cBuE2xMudybFzsBwqftfCK2Qihyih2FXF8uxFP0yev6jgaX5td101TkgiaMRNU5IzyHWNprCCyVJ47",
	"jX/BXRXRDsywVrLFCWfYtdKQi+1BCS2KfFPJnQvjvLKagbCCAsys5OhDSo4Gx91RIQ32/qkiQ9zOv/K3",
	"T2znw1qODhg+mbHvJCBsgiiiWEWTLzBKxAWlbWS32Vp26kJEtuamsQs3tjvOgV23VtwMZ+zbzgVdxiS9",
	"Bxts9wdCRd1VdGJ59NHgyFIoHYiQHSBy55lVQJCMISmV4+j79KMXTDsnVwdzrsnUFxndsl67CA6WT4/o",
	"X6RI4XT4DTi1ZXCHa1ZWhGqLiTELUyO2DPDAQAy0q7hsi4Ih+64NZlFCxdgLIzHiy5s15knRx4T0gaIa",
	"fDdQ4yWXgumS0wVizUUoSJ9GloT1gLPpYHTJsC5lX/d9DO0m3/WEdF+9661GFsR2eeC6EMceQSFMJanY",
	"GywsrnWB3bRLE8GCPTU5D6EtBmZktMD/+vPDukbYURML7qvuAv0uS8aPFCW+9hgZZ5Dy+T6hZRIKb+hl",
	"KobtITSJLLkSSQPtcTTnsu70qo0sfRLLXHl/f0w9oassT7o8FGezH7q1hRiLOqzCG5NiqEk0n82nMkZY",
	"jGQ1mRqi7WpC+zxsS0im9g7nApSestLeoBVdvfCokxjsJCZoOTyHSOG77jfDO9Dk6EI7Eik0hHQ4OXrm",
	"xjx5+Zsfy8KHZwoYd+CjMdwUq/ET6cCYm4iTr8b6OOk5Bnz4qAU5TtOqnE2sachbieWpc5KwHGUd7+Si",
	"QWIgB0Y8paEgVr1wyUZG1pEUSAMwECmJQ+qKaHgIMf0+TXufMrJhO+b71ar3Vev5MkIckDx9uREOtzU3",
	"pt61bs/lC3oFdfJntxfPVcnSSXU+JMoj9Ecxs11yrmv+5NhFGhbp/Eh144Pa5cfnllX4QEZd+yW1DPzG",
	"C2QtvkNn9wlZYCsePeq6DfffiV89Fw6uHhZUPu9HQ83MeQU9EfJtjyFn2ofsGeqLdbqwTtdwV7t4XSoK",
	"nZFSanu4C+SzhI6N5aU+eM+XIkfetkDZIyiLLsO41i5d9O9GNyDyVKNjLWn7b8ilkDOW2xtNG6TYP6+Z",
	"rijvDD720bOrXsSoseYoW5IrIeehWkkd09l/J166EahYDucUFgAwaBUzp0P+sheH+uR1fc21dxxFr3og",
	"uiGmum1LGIyN+7GoGWiFqkLKd2hLbWSMbE5WH6OxO+Ow34lXTmC1S0XI0qTEbj5U1AX8NZagw9Rzi19J",
	"hbpaoWnIvCOM80RfqVMizFySKS1LV8kel+5iHdIm3dRbQn3SW5QFHw9ci2MU2hvhCwmi1aZTdCnEChmi",
	"jhsPAQaOMiBRcKvDBLzavT2nFhDDFuvKez7LfcaEt18xTTSXcze01SBKbtcfMHYJKLzovixst2UUuj7J",
	"6VZDqIVbjRPbvQfEsJnTTu0h+8oBmuSc5VexwrtV90aVMailOsuPo1ZJjqG7KGdhqsPgHeDEO0X9Bp3b",
	"3sqOxLDdwuP3/+DG6IcWMh9MzHvhqZpUFtxR3nTlEB9WznPJwzxxyWFhpoTX/RMKexcp/fN9tlwwkmMe",
	"nnhE7P/yRD2PzlvKepWZ7ms2EXtMdMeuvpba2MlcRf97CkVpNkR4YDV1qVdBy8281VbuqxW47tDUByEx",
	"lPtSnyFZaGTv4mHp3FthJTRBsJyZpXZzZaXR2FTgYVEHJQQFWNaCcu3juLylMwm8omgDw4yWEdVAZGWo",
	"U/8IE1a+zqFPnmLgRG5cgdGjwUFDAlJgFDJ3FAApKRjm1wgT9+6tfWhlBo692RGJI5ZadHLWMTsOVh11",
	"MWJWoiCUuOptAWct3K1gbFVuh7Fvy3vE2LqNxgPHjC11p+jC2A1h5J8aVx/OtStCucgo4frIBidAW5UZ",
	"qxI+PNKGdTUR1t3bZkx1ikGlXYtnOZnYy3bMU7OiKQRb3KqLqDgtcxU1G/kAO2BmqL2/H9scbEoGqdsh",
	"3GMeSKy2/UkY6/IiukHBium3iKCzlxSGr1vYYaxQgX43I9Ps2EVyd3Xpyl7dAzIpUN51r/tYjlzv06Lo",
	"vuKTojh1Vcvv+ZrDRJ/oguvp7+5qT4oCS81S5msMpZ1Dbnt7scL+OpTE6uyn9WD3h5c40yfNy/IrWEOc",
	"0cgQjEkJZ+jQWTzZhY+IhrXYHCvkb7hod6Ftt7w/qtSaq/6xUgInOdELkd/TLcdJdrrjw4divD8iMws5",
	"Cq4UFlWx6FgsZTaX6grJKhMV6FCmYETzqwn2pfY2W5e5YSpdGxtmQDG5HSUvKKDo37XclRzxpkp5Tu6a",
	"09p2O3JGRCoWLkl/7lNconRgtz8ksyi8xf7Izg3hunnH2NMgtkhxDfYYXWEEvujftUC11abvACV/DXZq",
	"exgTdg1xy8HiakWjsyJWrphSBebjUXfG3Am1o+4LJsy9o26c5PNEXbu8Lx11kyP+50HdrTZ9B6j7JpTT",
	"fWDUfY//8T3KPuyz0HCqNdH5ZzBJC7ptPA7p6J9NnnOyhzWCbyNk0p6LmlHXLQ/tS1FtuY3o4+ryrzvn",
	"P7k32k9hw4L/lFb9x/lCdsZ69ee1e+ukKLaa179uMfV2kuaS7uAXmRylnyEYvo2Cm30mmEGDmlSo1vk0",
	"aFijJYRXTsJXvftUnldm26RlfXFpcGGHSIjiNmuMQAsr1haZlRzsDXrE8TS9kcTUQBd7uYxy9ndYufJI",
	"t8auU9gWFhvXsjCo8qHD2H0WUIjLX5r0/zcQcCcbNXwyjmf70de61B9v3c2eiMKe+EX9RS1hfhoxzwuf",
	"KNnc6kSxLeHtT3MJ4TYeIOdnzS+++AOknEdCpJcJ0C1OFONz9p09ZdNxxradX/wpLnXIjAe6xQG6do57",
	"eG7pabof1kmWzaanK9LlUurqdh09yTchtSMjGM1VwJhW3BA2DqE616yA4lvcRG/Y+6MCxDwvv/rOmJ9I",
	"Tm2eSJu2Ve85kVB9JfTrVhdaSzppMoo9kzFGI4VjdboInsPHiHg/g6lD3NqX3QVcK/BkNSG9f7XI913X",
	"ubymdl3A9Zxp88si/0vj/XYFZhkCXOe+FAZCwzNdjVx6U9qS7/eWzmLtIzuFrnevEVhbpdQvHcxn2cfp",
	"rfAy/98fPPb+pxBk/mVWcXblUV3T919+OyXXSzgQcO6X304bbZtWgxNaEOg+THlL03wif8vKKrovavlU",
	"P/cAhk+ItA+XICLFmLPcZAT6k36GkXXuHCxjoyuY4EumNMIsvuAKNQLmK1tcwfU1vHT/ffrnWfFhHXNd",
	"QpWtE86bU3w+ockr/PAr/4v87wFDj1dQNAqnXyYjpkSXkNvtrFKf0YKcPV2DoLO1qtOpy3p7q3192nvC",
	"Cxy/K2hvXAeGf0KkeDDgxD1/4QCZJEzyxVKctG9BHuARrz4FyPdOe/mwP6bXUjEDy8mHKuZ3nC0XoWrC",
	"7xusJvVTGKbOC/lJKg/Rm1lJ1KV2YCFZ60jpuj8flrQBID4nG3IEsXN6vZS9ijVY8aJdCKsU0ApoWaMQ",
	"SVeo3leQ+QoybSDj6KCdo81w+BSugcsSjYPurV7WqxT37dWH+/tc5pRPpTbD7wffD3r20pccn5jf50Xq",
	"+lM93N+nJesbib3xx8r+tX990LPX7Bf7PsAMUmU7tP87sXglv56EBm/xF8eD67+toJD8GWtYJ79dKFq4",
	"xLH4U3SsLn1qx/79w/8LAAD//1sCu1xP8QAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
