//go:build integration

// End-to-end coverage of the investor journey, through the HTTP-facing services only.
//
// Everything here is called the way a handler calls it: CreateIdentity, then
// AddClaimToIdentity, then Mint. Nothing is reconstructed locally — no wallet
// generated by the test, no proxy deployed by the test, no registry bound by the
// test. That is the whole point: the earlier suite was green while
// POST /contract/identity dereferenced a nil pointer, because no test ever crossed
// the Go-to-database boundary the production path crosses.
//
// The proof at the end is binary, and it is the milestone:
//
//	investor who went through the journey → mint succeeds
//	wallet that did not                   → mint reverts, balance stays 0
//
// Requires both a node and a database:
//
//	cd tools/hardhat && npx hardhat node
//	TEST_DATABASE_URL="postgres://…" go test -tags integration ./internal/blockchain/services/...
package services

import (
	"context"
	"math/big"
	"strings"
	"testing"
	"time"

	"github.com/TookenOrg/tooken-services/internal/api/server"
	"github.com/ethereum/go-ethereum/common"
	_ "github.com/lib/pq"
)

// Investor ids no fixture uses. blk.user_wallet and blk.identity carry no foreign key
// on user_id, so no usr.users row is needed.
const (
	e2eInvestorUserID = 970001
	e2eSecondUserID   = 970002
	e2eRejectedUserID = 970003
)

func TestInvestorJourneyEndToEnd(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Second)
	defer cancel()

	env := newChainDBEnv(ctx, t)
	fixture := env.Fixture
	svc := NewService()

	suite := fixture.DeploySuite(t, "E2EJourney", "Tooken E2E", "TKE2E", common.Address{})
	env.SetSharedIRSRow(t, suite.IRSAddr)

	var investorWallet, investorIdentity common.Address

	// ---- step 1: the investor gets a wallet, an ONCHAINID and a registry entry ----

	t.Run("CreateIdentity onboards the investor end to end", func(t *testing.T) {
		created, err := svc.CreateIdentity(ctx, server.CreateIdentityRequest{
			UserId:      e2eInvestorUserID,
			CountryCode: 250,
		})
		if err != nil {
			t.Fatalf("CreateIdentity: %v", err)
		}

		investorWallet = common.HexToAddress(created.WalletAddress)
		investorIdentity = common.HexToAddress(created.IdentityAddress)

		if investorWallet == (common.Address{}) || investorIdentity == (common.Address{}) {
			t.Fatalf("CreateIdentity must return a wallet and an identity, got %+v", created)
		}
		if created.CountryCode != 250 || created.UserId != e2eInvestorUserID {
			t.Fatalf("the response must echo the request, got %+v", created)
		}

		// The ONCHAINID must really be a contract, not just an address in a struct.
		code, err := fixture.Client.CodeAt(ctx, investorIdentity, nil)
		failOnErr(t, err, "CodeAt(identity)")
		if len(code) == 0 {
			t.Fatalf("no contract deployed at the returned identity address %s", investorIdentity.Hex())
		}

		// And the whole thing must have been persisted: a wallet, an identity row.
		var walletCount int
		if err := env.DB.QueryRow(
			`SELECT count(*) FROM blk.user_wallet WHERE user_id = $1 AND wallet_address = $2 AND is_active`,
			e2eInvestorUserID, investorWallet.Hex()).Scan(&walletCount); err != nil {
			t.Fatal(err)
		}
		if walletCount != 1 {
			t.Fatalf("the investor wallet must be persisted and active, found %d rows", walletCount)
		}

		var identityCount int
		if err := env.DB.QueryRow(
			`SELECT count(*) FROM blk.identity WHERE user_id = $1 AND address = $2`,
			e2eInvestorUserID, investorIdentity.Hex()).Scan(&identityCount); err != nil {
			t.Fatal(err)
		}
		if identityCount != 1 {
			t.Fatalf("the investor identity must be persisted, found %d rows", identityCount)
		}

		// ...and the registry entry must exist on-chain, in the shared whitelist.
		stored, err := suite.IRS.StoredIdentity(fixture.Call, investorWallet)
		failOnErr(t, err, "IRS.storedIdentity")
		if stored != investorIdentity {
			t.Fatalf("the shared whitelist must hold %s for %s, got %s",
				investorIdentity.Hex(), investorWallet.Hex(), stored.Hex())
		}
		country, err := suite.IRS.StoredInvestorCountry(fixture.Call, investorWallet)
		failOnErr(t, err, "IRS.storedInvestorCountry")
		if country != 250 {
			t.Fatalf("stored country: expected 250, got %d", country)
		}
	})

	// ---- step 2: registered is not verified -------------------------------------

	t.Run("being registered is not being KYC verified", func(t *testing.T) {
		// Written down because it is the trap of this domain: the registry entry and
		// the claim are two different facts, and only both together open the mint.
		verified, err := suite.IR.IsVerified(fixture.Call, investorWallet)
		failOnErr(t, err, "IsVerified before the claim")
		if verified {
			t.Fatal("an investor with no KYC claim must not be verified")
		}

		_, err = suite.Token.Mint(fixture.Auth, investorWallet, big.NewInt(1))
		if err == nil {
			t.Fatal("minting to a registered but unverified investor must revert")
		}
		if !strings.Contains(err.Error(), "Identity is not verified") {
			t.Fatalf("the revert must name the reason, got: %v", err)
		}
	})

	// ---- step 3: the claim, through the production service ----------------------

	t.Run("AddClaimToIdentity makes the investor verified", func(t *testing.T) {
		tx, err := svc.AddClaimToIdentity(ctx, server.AddClaimRequest{
			UserId:     e2eInvestorUserID,
			ClaimTopic: int(kycTopic),
		})
		if err != nil {
			t.Fatalf("AddClaimToIdentity: %v", err)
		}
		if tx == nil {
			t.Fatal("AddClaimToIdentity must return the transaction it sent")
		}

		verified, err := suite.IR.IsVerified(fixture.Call, investorWallet)
		failOnErr(t, err, "IsVerified after the claim")
		if !verified {
			t.Fatal("a registered investor holding a KYC claim must be verified")
		}
	})

	// ---- step 4: the proof, both ways -------------------------------------------

	t.Run("the verified investor can be minted to", func(t *testing.T) {
		amount := new(big.Int).Mul(big.NewInt(1000), new(big.Int).Exp(big.NewInt(10), big.NewInt(18), nil))

		tx, err := suite.Token.Mint(fixture.Auth, investorWallet, amount)
		failOnErr(t, err, "Mint to the verified investor")
		fixture.Mine(tx, "Mint")

		balance, err := suite.Token.BalanceOf(fixture.Call, investorWallet)
		failOnErr(t, err, "BalanceOf")
		if balance.Cmp(amount) != 0 {
			t.Fatalf("investor balance: expected %s, got %s", amount, balance)
		}
	})

	t.Run("a wallet that never went through the journey is refused", func(t *testing.T) {
		stranger := common.HexToAddress("0x000000000000000000000000000000000000dEaD")

		_, err := suite.Token.Mint(fixture.Auth, stranger, big.NewInt(1))
		if err == nil {
			t.Fatal("minting to a non-KYC wallet must revert")
		}
		if !strings.Contains(err.Error(), "Identity is not verified") {
			t.Fatalf("the revert must name the reason, got: %v", err)
		}

		balance, err := suite.Token.BalanceOf(fixture.Call, stranger)
		failOnErr(t, err, "BalanceOf stranger")
		if balance.Sign() != 0 {
			t.Fatalf("the non-KYC wallet must hold nothing, got %s", balance)
		}
	})

	// ---- and the promise of one shared whitelist --------------------------------

	t.Run("a token deployed afterwards accepts the investor with no new KYC", func(t *testing.T) {
		later := fixture.DeploySuite(t, "E2ELater", "Tooken E2E Later", "TKE2L", suite.IRSAddr)

		verified, err := later.IR.IsVerified(fixture.Call, investorWallet)
		failOnErr(t, err, "IsVerified on the later token")
		if !verified {
			t.Fatal("the investor must be verified on a token created after the onboarding")
		}

		amount := new(big.Int).Mul(big.NewInt(250), new(big.Int).Exp(big.NewInt(10), big.NewInt(18), nil))
		tx, err := later.Token.Mint(fixture.Auth, investorWallet, amount)
		failOnErr(t, err, "Mint on the later token")
		fixture.Mine(tx, "Mint on the later token")

		balance, err := later.Token.BalanceOf(fixture.Call, investorWallet)
		failOnErr(t, err, "BalanceOf on the later token")
		if balance.Cmp(amount) != 0 {
			t.Fatalf("later token balance: expected %s, got %s", amount, balance)
		}
	})

	// ---- and the guard against onboarding the same investor twice ---------------

	t.Run("a second CreateIdentity for the same investor is refused", func(t *testing.T) {
		identitiesBefore := countIdentities(t, env, e2eInvestorUserID)

		_, err := svc.CreateIdentity(ctx, server.CreateIdentityRequest{
			UserId:      e2eInvestorUserID,
			CountryCode: 250,
		})
		if err == nil {
			t.Fatal("an investor who already has an identity must be refused")
		}

		// The assertion that matters is not the error: it is that nothing was
		// deployed. A guard that refuses after spending a transaction has already
		// produced the orphan it exists to prevent.
		if after := countIdentities(t, env, e2eInvestorUserID); after != identitiesBefore {
			t.Fatalf("no second ONCHAINID must be created, identity rows went from %d to %d",
				identitiesBefore, after)
		}
	})

	// ---- when the database refuses the last step --------------------------------

	t.Run("a failed InsertIdentity is reported, and the response stays empty", func(t *testing.T) {
		// Steps 2 to 4 have already moved the chain — a wallet exists, an ONCHAINID is
		// deployed, the investor is in the shared whitelist — when step 5 fails. The
		// error must come out, and it must NOT come out next to a response that looks
		// like a success: an IdentityInfos carrying a wallet and an ONCHAINID for an
		// identity the database does not know is worse than no answer at all.
		//
		// The refusal is produced by the schema rather than by a mock, so the test
		// exercises the real InsertIdentity against the real table.
		if _, err := env.DB.Exec(
			`ALTER TABLE blk.identity ADD CONSTRAINT identity_probe_reject CHECK (false) NOT VALID`); err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() {
			_, _ = env.DB.Exec(`ALTER TABLE blk.identity DROP CONSTRAINT IF EXISTS identity_probe_reject`)
		})

		created, err := svc.CreateIdentity(ctx, server.CreateIdentityRequest{
			UserId:      e2eRejectedUserID,
			CountryCode: 250,
		})
		if err == nil {
			t.Fatal("a failed InsertIdentity must be reported")
		}
		if created != (server.IdentityInfos{}) {
			t.Fatalf("a failed creation must not answer with a filled response, got %+v", created)
		}
	})

	t.Run("a different investor is still onboarded normally", func(t *testing.T) {
		// Without this, a guard hard-wired to refuse everything would look just as
		// green as a correct one.
		created, err := svc.CreateIdentity(ctx, server.CreateIdentityRequest{
			UserId:      e2eSecondUserID,
			CountryCode: 442,
		})
		if err != nil {
			t.Fatalf("CreateIdentity for a fresh investor: %v", err)
		}

		secondWallet := common.HexToAddress(created.WalletAddress)
		if secondWallet == investorWallet {
			t.Fatal("two investors must not share a wallet")
		}

		country, err := suite.IRS.StoredInvestorCountry(fixture.Call, secondWallet)
		failOnErr(t, err, "IRS.storedInvestorCountry for the second investor")
		if country != 442 {
			t.Fatalf("stored country: expected 442, got %d", country)
		}
	})
}

func countIdentities(t *testing.T, env *chainDBEnv, userID int) int {
	t.Helper()
	var count int
	if err := env.DB.QueryRow(`SELECT count(*) FROM blk.identity WHERE user_id = $1`, userID).Scan(&count); err != nil {
		t.Fatal(err)
	}
	return count
}
