-- 000013 — Resynchronise the identity sequences
--
-- Reproduced on PostgreSQL 16: a table declared
-- `GENERATED BY DEFAULT AS IDENTITY` accepts an explicit id, and an explicit
-- id does not advance the sequence. Three seeded rows (1, 2, 3) leave the
-- sequence at 1, so the first insert that lets the identity choose collides:
--
--     ERROR:  duplicate key value violates unique constraint "pk_real_estates"
--     DETAIL:  Key (id)=(1) already exists.
--
-- Every fixture, every seed script and every restored dump that carries its
-- ids creates this gap, on any table, which is why this migration sweeps the
-- whole project rather than the one table where it was noticed.
--
-- A sequence is only ever moved *forward*. Lowering one would hand out ids
-- that already exist and turn a startup error into a slow corruption, so a
-- sequence already ahead of the data is left exactly where it is.

DO $$
DECLARE
    r RECORD;
    seq TEXT;
    max_id BIGINT;
    seq_value BIGINT;
BEGIN
    FOR r IN
        SELECT c.table_schema, c.table_name, c.column_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
            ON t.table_schema = c.table_schema
           AND t.table_name = c.table_name
           AND t.table_type = 'BASE TABLE'
        WHERE c.table_schema IN ('ass', 'iss', 'blk', 'usr', 'rel')
          AND (c.is_identity = 'YES' OR c.column_default LIKE 'nextval(%')
    LOOP
        seq := pg_get_serial_sequence(
            format('%I.%I', r.table_schema, r.table_name), r.column_name);

        CONTINUE WHEN seq IS NULL;

        EXECUTE format('SELECT COALESCE(max(%I), 0) FROM %I.%I',
                       r.column_name, r.table_schema, r.table_name)
        INTO max_id;

        EXECUTE format('SELECT last_value FROM %s', seq) INTO seq_value;

        IF max_id > seq_value THEN
            PERFORM setval(seq, max_id, true);
            RAISE NOTICE 'sequence % moved from % to % (%.%)',
                seq, seq_value, max_id, r.table_schema, r.table_name;
        END IF;
    END LOOP;
END
$$;
