-- 000026 — an ONCHAINID belongs to someone, and one wallet at a time
--
-- ═══════════════════════════════════════════════════════════════════════════
-- PART ONE — nothing tied blk.user_wallet and blk.identity to a real user
-- ═══════════════════════════════════════════════════════════════════════════
--
--   Both tables carry a user_id, and both are plain bigints. The only foreign
--   key in the blk schema is identity.wallet_id -> user_wallet.id: nothing has
--   ever checked that the investor exists.
--
--   During the manual walkthrough of 2026-09-18, POST /contract/identity with
--   userId 1 generated a wallet, deployed an ONCHAINID and registered the
--   investor in the shared whitelist without once verifying that user 1 was
--   real. It happened to be.
--
--   An identity recorded on-chain and attached to nobody is not a row that can
--   be repaired later: the deployment is permanent, and the only thing that
--   could say whose it was is the one thing missing.
--
-- WHY NOT VALID, THEN VALIDATE
--   NOT VALID adds the constraint for future writes without scanning the table
--   or holding a long lock; VALIDATE then checks the past, taking only a weak
--   lock. Both statements live here, in the file — 000021 left its VALIDATE out
--   and 000022 had to be written to catch up. A constraint that is only
--   validated in somebody's shell history does not survive a rebuild.
--
-- WHY RESTRICT AND NOT CASCADE
--   Deleting an investor who owns a deployed ONCHAINID must not quietly erase
--   the trace of it. The chain keeps the identity whatever the database does,
--   so refusing the deletion is the only answer that leaves the two agreeing.

ALTER TABLE blk.user_wallet DROP CONSTRAINT IF EXISTS user_wallet_user_id_fkey;
ALTER TABLE blk.user_wallet
    ADD CONSTRAINT user_wallet_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES usr.users(id) ON DELETE RESTRICT NOT VALID;

ALTER TABLE blk.identity DROP CONSTRAINT IF EXISTS identity_user_id_fkey;
ALTER TABLE blk.identity
    ADD CONSTRAINT identity_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES usr.users(id) ON DELETE RESTRICT NOT VALID;

-- Checks the rows that were written before the constraint existed. If this
-- fails, orphans are already there:
--
--   SELECT 'user_wallet' AS t, user_id FROM blk.user_wallet
--   WHERE user_id NOT IN (SELECT id FROM usr.users)
--   UNION ALL
--   SELECT 'identity', user_id FROM blk.identity
--   WHERE user_id NOT IN (SELECT id FROM usr.users);
--
-- Deal with them one by one before re-running: they are on-chain identities,
-- not drafts.
ALTER TABLE blk.user_wallet VALIDATE CONSTRAINT user_wallet_user_id_fkey;
ALTER TABLE blk.identity VALIDATE CONSTRAINT identity_user_id_fkey;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART TWO — who built this wallet (D5)
-- ═══════════════════════════════════════════════════════════════════════════
--
--   The platform creates a wallet, or the investor brings one. Since D5 was
--   amended, no wallet carries a key at all — 000023 dropped the columns — so
--   this does not answer "can we sign for them?", which is always no.
--
--   It answers "who built it?", and that is what decides whether a proof of
--   control is required: an address the investor typed in could be one they do
--   not own, and shares minted there are gone with the holder unidentifiable.
--
--   An explicit column rather than an inference: "no key stored" and "key lost"
--   would look identical, and a question asked at the moment of minting
--   deserves a written answer.

ALTER TABLE blk.user_wallet
    ADD COLUMN IF NOT EXISTS custody text NOT NULL DEFAULT 'custodial';

ALTER TABLE blk.user_wallet DROP CONSTRAINT IF EXISTS user_wallet_custody_ck;
ALTER TABLE blk.user_wallet ADD CONSTRAINT user_wallet_custody_ck
    CHECK (custody IN ('custodial', 'external'));

COMMENT ON COLUMN blk.user_wallet.custody IS
    'custodial = generated by the platform (control is implied) | external = brought by the investor (a signed challenge is required before minting to it).';

-- ═══════════════════════════════════════════════════════════════════════════
-- PART THREE — one active wallet per investor (D7)
-- ═══════════════════════════════════════════════════════════════════════════
--
--   The IdentityRegistry maps one wallet to one ONCHAINID. Two active wallets
--   would mean two answers to "where do we deliver?", and the code would pick
--   whichever the query ordered first.
--
--   If this index fails to build, duplicates already exist:
--
--     SELECT user_id, count(*), array_agg(id)
--     FROM blk.user_wallet WHERE is_active
--     GROUP BY user_id HAVING count(*) > 1;
--
--   Deactivate all but one per user before re-running — and choose deliberately
--   which one, because that is the address the shares will go to.
CREATE UNIQUE INDEX IF NOT EXISTS user_wallet_one_active_per_user_idx
    ON blk.user_wallet (user_id) WHERE is_active;
