package database

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	assetsDb "github.com/TookenOrg/tooken-services/internal/assets_managements/database"
	"github.com/TookenOrg/tooken-services/internal/orders/pricing"
	"github.com/TookenOrg/tooken-services/internal/utils"
	"github.com/lib/pq"
	"github.com/shopspring/decimal"
)

// Refusals of PlaceIssuanceOrder. The service exposes them under its own names
// (aliases, same values): this package cannot import services (import cycle).
var (
	ErrOrderAssetNotFound       = errors.New("real estate not found")        // 404
	ErrOrderAssetNotOpen        = errors.New("fundraising is not open")      // 409
	ErrOrderIdempotencyKeyReuse = errors.New("idempotency key reused")       // 422
	ErrOrderInvestorNotEligible = errors.New("investor not eligible")        // 403
	ErrOrderNotEnoughShares     = errors.New("not enough shares left")       // 409
	ErrOrderStakeLimit          = errors.New("investor stake limit reached") // 409
)

// PlaceOrderDTO is what the caller knows before the transaction. Nothing in it
// comes from the asset: price, fees and limits are read under the lock.
type PlaceOrderDTO struct {
	UserID         int
	RealEstateID   int
	Quantity       int
	IdempotencyKey string
	OrderReference string        // generated by the service, regenerated on collision
	ReservationTTL time.Duration // reservation_expires_at = now() + TTL, computed by the database (U2)
}

// PlacedOrderDTO identifies the order the call ended on. Replayed is true when
// the idempotency key had already produced it: nothing was written (U5).
type PlacedOrderDTO struct {
	OrderID        int64
	OrderReference string
	Replayed       bool
}

// lockedRealEstateDTO is the asset as it is once the lock is held. Every
// business check of the order reads it, never an earlier read.
type lockedRealEstateDTO struct {
	StatusID             int
	Active               bool
	Deleted              bool
	Tokenized            bool
	HasSharesConfig      bool
	TotalShares          int64
	PricePerShare        decimal.Decimal
	CurrencyCode         string
	EntryFeeRate         decimal.NullDecimal // NULL: no entry fee
	MaxSharesPerInvestor sql.NullInt64       // NULL: no cap (U8)
}

// PlaceIssuanceOrder reserves shares for an investor in one transaction.
//
// The asset row is locked first and every check runs after: two orders on the
// same asset are serialised, so the stock they read is the stock they write
// against (TICKET-M3-3 §3.1). Orders on different assets do not wait.
func PlaceIssuanceOrder(ctx context.Context, in PlaceOrderDTO) (placed PlacedOrderDTO, err error) {
	err = utils.InTransaction(ctx, func(tx *sql.Tx) error {
		// 1 - Lock first, nothing else.
		if err := lockRealEstate(ctx, tx, in.RealEstateID); err != nil {
			return err
		}

		// 2 - Replay before any business check: a replayed key returns the
		// existing order as it is, even if the fundraising closed since (§3.5).
		existing, found, err := findOrderByIdempotencyKey(ctx, tx, in.UserID, in.IdempotencyKey)
		if err != nil {
			return err
		}
		if found {
			if existing.realEstateID != in.RealEstateID || existing.quantity != in.Quantity {
				return ErrOrderIdempotencyKeyReuse
			}
			placed = PlacedOrderDTO{OrderID: existing.id, OrderReference: existing.reference, Replayed: true}
			return nil
		}

		// 3 - The asset, read under the lock.
		asset, err := readLockedRealEstate(ctx, tx, in.RealEstateID)
		if err != nil {
			return err
		}
		if err := checkRealEstateOpen(asset); err != nil {
			return err
		}

		// 4 - KYC of in.UserID must be "verified"
		kycVerified, err := checkKYCisVerified(ctx, tx, in.UserID)
		if err != nil {
			return err
		}
		if !kycVerified {
			return ErrOrderInvestorNotEligible
		}

		// 5 - Stock and per-investor cap. No lock on the orders themselves:
		// the asset lock of step 1 already makes every other order wait.
		onAsset, byUser, err := readReservedShares(ctx, tx, in.RealEstateID, in.UserID)
		if err != nil {
			return err
		}
		if err := checkSharesAvailable(asset, onAsset, byUser, in.Quantity); err != nil {
			return err
		}

		// 6 - Price the order with what was read under the lock (step 3).
		var entryFeeRate *decimal.Decimal
		if asset.EntryFeeRate.Valid {
			entryFeeRate = &asset.EntryFeeRate.Decimal
		}
		price := pricing.PriceOrder(int64(in.Quantity), asset.PricePerShare, entryFeeRate)

		// 7 - Insert the order, directly in AWAITING_PAYMENT.
		orderID, err := insertOrder(ctx, tx, in, asset.CurrencyCode, price)
		if err != nil {
			return err
		}
		placed = PlacedOrderDTO{OrderID: orderID, OrderReference: in.OrderReference}

		// 8 - Insert the fee line, if any
		for _, fee := range price.Fees {
			if err := insertFee(ctx, tx, orderID, fee); err != nil {
				return err
			}
		}

		// 9 - The two history rows of D23: CREATED, then AWAITING_PAYMENT.
		return insertCreationHistory(ctx, tx, orderID, in.UserID)
	})
	if err != nil {
		return PlacedOrderDTO{}, err
	}

	return placed, nil
}

// lockRealEstate takes the row lock on the asset.
//
// The query reads nothing else on purpose: when FOR UPDATE has to wait,
// PostgreSQL refreshes the locked row but not the rows of a joined table, which
// stay as they were when the statement started (TICKET-M3-3 §3.7, proven).
func lockRealEstate(ctx context.Context, tx *sql.Tx, realEstateID int) error {
	const query = `SELECT 1 FROM ass.real_estate WHERE id = $1 FOR UPDATE`

	var one int
	if err := tx.QueryRowContext(ctx, query, realEstateID).Scan(&one); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrOrderAssetNotFound
		}
		return fmt.Errorf("lock real estate %d: %w", realEstateID, err)
	}

	return nil
}

type idempotentOrder struct {
	id           int64
	reference    string
	realEstateID int
	quantity     int
}

// findOrderByIdempotencyKey looks for the order this key already produced.
// The lock of step 1 is what makes it safe: a concurrent request with the same
// key waits on the asset, then sees the committed order (§3.4).
func findOrderByIdempotencyKey(ctx context.Context, tx *sql.Tx, userID int, key string) (o idempotentOrder, found bool, err error) {
	const query = `
SELECT id, order_reference, asset_id, quantity
FROM iss.issuance_orders
WHERE user_id = $1 AND idempotency_key = $2
`

	err = tx.QueryRowContext(ctx, query, userID, key).Scan(&o.id, &o.reference, &o.realEstateID, &o.quantity)
	if errors.Is(err, sql.ErrNoRows) {
		return idempotentOrder{}, false, nil
	}
	if err != nil {
		return idempotentOrder{}, false, fmt.Errorf("find order by idempotency key: %w", err)
	}

	return o, true, nil
}

// readLockedRealEstate reads what the order checks, in a statement of its own
// issued after the lock, so it sees every change committed before the lock
// was granted. The join is safe here: no FOR UPDATE, fresh snapshot.
func readLockedRealEstate(ctx context.Context, tx *sql.Tx, realEstateID int) (lockedRealEstateDTO, error) {
	const query = `
SELECT
    re.status_id,
    re.active,
    re.deleted_at IS NOT NULL,
    re.token_id IS NOT NULL,
    sc.id IS NOT NULL,
    COALESCE(sc.total_shares, 0),
    COALESCE(sc.price_per_share, 0),
    COALESCE(sc.currency_code, ''),
    sc.entry_fee_rate,
    sc.max_shares_per_investor
FROM ass.real_estate re
LEFT JOIN ass.real_estate_shares_config sc
    ON sc.real_estate_id = re.id
WHERE re.id = $1
`

	var a lockedRealEstateDTO
	err := tx.QueryRowContext(ctx, query, realEstateID).Scan(
		&a.StatusID,
		&a.Active,
		&a.Deleted,
		&a.Tokenized,
		&a.HasSharesConfig,
		&a.TotalShares,
		&a.PricePerShare,
		&a.CurrencyCode,
		&a.EntryFeeRate,
		&a.MaxSharesPerInvestor,
	)
	if err != nil {
		return lockedRealEstateDTO{}, fmt.Errorf("read locked real estate %d: %w", realEstateID, err)
	}

	return a, nil
}

// Order statuses written by PlaceIssuanceOrder (iss.issuance_order_statuses).
const (
	statusCreated         = 1
	statusAwaitingPayment = 2
)

// readReservedShares returns the shares held on the asset by every investor,
// and by userID alone, in one pass. What "held" means is the shared definition,
// assetsDb.ReservedOrders (§2.5): lapsed reservations do not count.
func readReservedShares(ctx context.Context, tx *sql.Tx, realEstateID, userID int) (onAsset, byUser int64, err error) {
	const query = `
SELECT
    COALESCE(SUM(o.quantity), 0),
    COALESCE(SUM(o.quantity) FILTER (WHERE o.user_id = $2), 0)` + assetsDb.ReservedOrders + `
  AND o.asset_id = $1
`

	if err = tx.QueryRowContext(ctx, query, realEstateID, userID).Scan(&onAsset, &byUser); err != nil {
		return 0, 0, fmt.Errorf("read reserved shares of real estate %d: %w", realEstateID, err)
	}

	return onAsset, byUser, nil
}

// checkSharesAvailable refuses an order the asset cannot serve, then one that
// would take the investor above the cap. The messages say what to do (§3.6).
func checkSharesAvailable(a lockedRealEstateDTO, onAsset, byUser int64, quantity int) error {
	requested := int64(quantity)

	remaining := a.TotalShares - onAsset
	if requested > remaining {
		return fmt.Errorf("%w: only %d shares left, %d requested",
			ErrOrderNotEnoughShares, max(remaining, 0), requested)
	}

	// NULL: no cap in M3-3 (U8).
	if a.MaxSharesPerInvestor.Valid {
		limit := a.MaxSharesPerInvestor.Int64
		if byUser+requested > limit {
			return fmt.Errorf("%w: you already hold %d of %d shares allowed on this asset, %d requested",
				ErrOrderStakeLimit, byUser, limit, requested)
		}
	}

	return nil
}

// checkRealEstateOpen applies U7: an asset the public cannot see is a 404, a
// visible one that does not take orders yet (or any more) is a 409.
func checkRealEstateOpen(a lockedRealEstateDTO) error {
	if a.Deleted || !a.Active {
		return ErrOrderAssetNotFound
	}

	if a.StatusID != assetsDb.StatusFundraising || !a.Tokenized || !a.HasSharesConfig {
		return ErrOrderAssetNotOpen
	}

	return nil
}

func checkKYCisVerified(ctx context.Context, tx *sql.Tx, userID int) (bool, error) {
	const query = `
SELECT kyc_status
FROM usr.users
WHERE id = $1 and kyc_status = 'verified' and (kyc_expires_at IS NULL OR kyc_expires_at > now())
`

	var kycStatus string
	err := tx.QueryRowContext(ctx, query, userID).Scan(&kycStatus)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, nil
		}
		return false, fmt.Errorf("check KYC for user %d: %w", userID, err)
	}

	return true, nil
}

const idempotencyKeyConstraint = "issuance_orders_idempotency_uidx"

// isUniqueViolation reports whether err is a Postgres unique violation
// (SQLSTATE 23505) on the given constraint or unique index.
func isUniqueViolation(err error, constraint string) bool {
	var pqErr *pq.Error
	return errors.As(err, &pqErr) && pqErr.Code == "23505" && pqErr.Constraint == constraint
}

// insertOrder writes the order in AWAITING_PAYMENT with its frozen amounts.
//
// Both dates come from the database clock (U2, §3.3): created_at by default,
// reservation_expires_at from now() of the same transaction, so the CHECK
// reservation_expires_at > created_at holds by construction.
func insertOrder(ctx context.Context, tx *sql.Tx, in PlaceOrderDTO, currencyCode string, price pricing.PricedOrder) (orderID int64, err error) {
	const query = `
INSERT INTO iss.issuance_orders (
    user_id, asset_id, quantity, status_id, order_reference, idempotency_key,
    unit_price, currency_code, gross_amount, fee_amount, amount_due,
    reservation_expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now() + make_interval(secs => $12))
RETURNING id
`

	err = tx.QueryRowContext(ctx, query,
		in.UserID, in.RealEstateID, in.Quantity, statusAwaitingPayment, in.OrderReference, in.IdempotencyKey,
		price.UnitPrice, currencyCode, price.GrossAmount, price.FeeAmount, price.AmountDue,
		in.ReservationTTL.Seconds(),
	).Scan(&orderID)
	if err != nil {
		if isDuplicateReferenceErr(err) {
			return 0, ErrDuplicateOrderReference
		}
		// The asset lock does not serialise one key replayed on two assets:
		// the later order meets the unique index instead of step 2 (§3.4).
		if isUniqueViolation(err, idempotencyKeyConstraint) {
			return 0, ErrOrderIdempotencyKeyReuse
		}
		return 0, fmt.Errorf("insert order: %w", err)
	}

	return orderID, nil
}

func insertFee(ctx context.Context, tx *sql.Tx, orderID int64, fee pricing.PricedFee) error {
	const query = `
INSERT INTO iss.issuance_order_fees (
    order_id, fee_code, rate, base_amount, amount
)
VALUES ($1, $2, $3, $4, $5)
`

	_, err := tx.ExecContext(ctx, query, orderID, fee.Code, fee.Rate, fee.BaseAmount, fee.Amount)
	if err != nil {
		return fmt.Errorf("insert fee for order %d: %w", orderID, err)
	}
	return nil
}

// insertCreationHistory records how the order came to be (D23): NULL -> CREATED,
// then CREATED -> AWAITING_PAYMENT, both by the investor.
//
// One statement, so both rows get the same created_at (now() of the
// transaction). A timeline must therefore order by (created_at, id), not by
// created_at alone: the identity follows the order of the VALUES list.
func insertCreationHistory(ctx context.Context, tx *sql.Tx, orderID int64, userID int) error {
	const query = `
INSERT INTO iss.issuance_order_status_history (order_id, from_status_id, to_status_id, actor_user_id)
VALUES ($1, NULL, $2, $4),
       ($1, $2,   $3, $4)
`

	if _, err := tx.ExecContext(ctx, query, orderID, statusCreated, statusAwaitingPayment, userID); err != nil {
		return fmt.Errorf("insert creation history of order %d: %w", orderID, err)
	}

	return nil
}
