SET search_path = '';
CREATE SCHEMA IF NOT EXISTS ass;
CREATE SCHEMA IF NOT EXISTS blk;
CREATE SCHEMA IF NOT EXISTS iss;
CREATE SCHEMA IF NOT EXISTS rel;
CREATE SCHEMA IF NOT EXISTS usr;
CREATE OR REPLACE FUNCTION ass.real_estate_sync_active() RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE projected BOOLEAN;
BEGIN
SELECT s.is_public INTO projected
FROM ass.real_estate_status s
WHERE s.id = NEW.status_id;
-- A foreign key already rejects an unknown status, but it is checked after
-- this trigger has run. Raising here turns a constraint violation into a
-- sentence, and keeps the projection honest if that key is ever dropped.
IF NOT FOUND THEN RAISE EXCEPTION 'unknown ass.real_estate_status id: %',
NEW.status_id;
END IF;
NEW.active := projected;
RETURN NEW;
END;
$function$;
CREATE OR REPLACE FUNCTION ass.real_estate_sync_contract_address() RETURNS trigger LANGUAGE plpgsql AS $function$ BEGIN IF NEW.token_id IS NULL THEN NEW.contract_address := NULL;
ELSE
SELECT t.address INTO NEW.contract_address
FROM blk.token t
WHERE t.id = NEW.token_id;
END IF;
RETURN NEW;
END;
$function$;
CREATE OR REPLACE FUNCTION blk.update_updated_at_column() RETURNS trigger LANGUAGE plpgsql AS $function$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$function$;
CREATE SEQUENCE IF NOT EXISTS ass.issuer_id_seq AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS ass.real_estate_media_id_seq AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS blk.contract_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS blk.contract_implementation_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS blk.token_id_seq AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS blk.token_transaction_id_seq AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS iss.issuance_allocations_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS iss.issuance_order_statuses_id_seq AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS iss.issuance_orders_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS rel.user_asset_favorite_id_seq AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS usr.users_id_seq AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;
CREATE TABLE IF NOT EXISTS ass.issuer (
    id integer DEFAULT nextval('ass.issuer_id_seq'::regclass) NOT NULL,
    name text NOT NULL,
    legal_form text NOT NULL,
    registration_number text,
    country_code character(2) DEFAULT 'LU'::bpchar NOT NULL,
    lei_code character(20),
    status_id smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS ass.issuer_status (
    id smallint NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    is_final boolean DEFAULT false NOT NULL
);
CREATE TABLE IF NOT EXISTS ass.payment_frequency_type (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS ass.real_estate (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(2000),
    imageurl character varying(500),
    estate_type integer NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    contract_address character varying(42),
    status_id smallint DEFAULT 1 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone,
    issuer_id integer NOT NULL,
    token_id integer,
    deleted_at timestamp with time zone
);
CREATE TABLE IF NOT EXISTS ass.real_estate_address (
    real_estate_id integer NOT NULL,
    street text NOT NULL,
    street_complement text,
    postal_code text NOT NULL,
    city text NOT NULL,
    region text,
    country_code character(2) NOT NULL,
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS ass.real_estate_media (
    id integer DEFAULT nextval('ass.real_estate_media_id_seq'::regclass) NOT NULL,
    real_estate_id integer NOT NULL,
    url text NOT NULL,
    alt_text text,
    media_type text DEFAULT 'image'::text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    is_cover boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS ass.real_estate_shares_config (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    real_estate_id integer NOT NULL,
    total_shares numeric(20, 0) NOT NULL,
    price_per_share numeric(20, 8) NOT NULL,
    yield numeric(7, 4),
    payment_frequency integer,
    payment_frequency_type integer,
    currency_code character(3) DEFAULT 'EUR'::bpchar NOT NULL,
    compartment_ref text,
    min_investment numeric(20, 8),
    max_investment numeric(20, 8),
    entry_fee_rate numeric(7, 4),
    mgmt_fee_rate numeric(7, 4),
    exit_fee_rate numeric(7, 4),
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    total_valuation numeric(40, 8) GENERATED ALWAYS AS ((total_shares * price_per_share)) STORED
);
CREATE TABLE IF NOT EXISTS ass.real_estate_specification (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    real_estate_id integer NOT NULL,
    lot_size numeric(12, 2),
    surface_area numeric(12, 2) NOT NULL,
    bedroom_number integer,
    bathroom_number integer,
    pool_size numeric(12, 2),
    terrace_size numeric(12, 2),
    built_year integer,
    energy_class character(1),
    ges_class character(1)
);
CREATE TABLE IF NOT EXISTS ass.real_estate_status (
    id smallint NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    is_final boolean DEFAULT false NOT NULL,
    is_public boolean DEFAULT false NOT NULL,
    "position" smallint DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS ass.real_estate_type (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(50) NOT NULL,
    active boolean DEFAULT true NOT NULL
);
CREATE TABLE IF NOT EXISTS blk.chains (
    id bigint NOT NULL,
    name text NOT NULL,
    network text NOT NULL,
    is_evm boolean DEFAULT true NOT NULL,
    rpc_url text,
    explorer_url text,
    native_symbol text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS blk.contract_implementation (
    id bigint DEFAULT nextval('blk.contract_implementation_id_seq'::regclass) NOT NULL,
    tx_hash character varying(66) NOT NULL,
    address character varying(42) NOT NULL,
    contract_name character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    version smallint,
    chain_id bigint
);
CREATE TABLE IF NOT EXISTS blk.contract_instance (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    contract_implementation_id bigint NOT NULL,
    parent_contract_id bigint NOT NULL,
    address character varying(42) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    contract_name character varying(50),
    chain_id bigint
);
CREATE TABLE IF NOT EXISTS blk.contract_role (
    id bigint DEFAULT nextval('blk.contract_id_seq'::regclass) NOT NULL,
    tx_hash character varying(66) NOT NULL,
    address character varying(42) NOT NULL,
    contract_name character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS blk.eth_transaction (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    tx_hash character varying(66) NOT NULL,
    tx_name character varying(50) NOT NULL,
    block_number bigint NOT NULL,
    to_address character varying(42),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    value_wei numeric(78, 0) NOT NULL
);
CREATE TABLE IF NOT EXISTS blk.identity (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    wallet_id bigint NOT NULL,
    address character varying(42) NOT NULL,
    tx_hash character varying(66) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS blk.token (
    id integer DEFAULT nextval('blk.token_id_seq'::regclass) NOT NULL,
    symbol character varying(50) NOT NULL,
    token_name character varying(100) NOT NULL,
    address character varying(42) NOT NULL,
    nb_decimal bigint NOT NULL,
    modular_compliance_addr character varying(42),
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    salt text
);
CREATE TABLE IF NOT EXISTS blk.token_transaction (
    id integer DEFAULT nextval('blk.token_transaction_id_seq'::regclass) NOT NULL,
    token_id integer NOT NULL,
    tx_hash character varying(66) NOT NULL,
    tx_name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS blk.user_wallet (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    wallet_address character varying(42) NOT NULL,
    label character varying(50),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS iss.issuance_allocations (
    id bigint DEFAULT nextval('iss.issuance_allocations_id_seq'::regclass) NOT NULL,
    issuance_order_id bigint NOT NULL,
    asset_id bigint NOT NULL,
    quantity integer NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS iss.issuance_order_statuses (
    id integer DEFAULT nextval('iss.issuance_order_statuses_id_seq'::regclass) NOT NULL,
    code character varying(30) NOT NULL,
    label character varying(100) NOT NULL,
    is_final boolean DEFAULT false NOT NULL,
    counts_as_reserved boolean DEFAULT true NOT NULL
);
CREATE TABLE IF NOT EXISTS iss.issuance_orders (
    id bigint DEFAULT nextval('iss.issuance_orders_id_seq'::regclass) NOT NULL,
    user_id bigint NOT NULL,
    asset_id bigint NOT NULL,
    quantity integer NOT NULL,
    status_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    order_reference character varying(32)
);
CREATE TABLE IF NOT EXISTS rel.user_asset_favorite (
    id bigint DEFAULT nextval('rel.user_asset_favorite_id_seq'::regclass) NOT NULL,
    user_id bigint NOT NULL,
    real_estate_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS usr.users (
    id integer DEFAULT nextval('usr.users_id_seq'::regclass) NOT NULL,
    full_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_connexion timestamp with time zone,
    role text DEFAULT 'USER'::text NOT NULL,
    kyc_status text DEFAULT 'none'::text NOT NULL,
    kyc_verified_at timestamp with time zone,
    kyc_expires_at timestamp with time zone
);
ALTER TABLE ass.issuer
ADD CONSTRAINT issuer_country_code_ck CHECK ((country_code ~ '^[A-Z]{2}$'::text));
ALTER TABLE ass.issuer
ADD CONSTRAINT issuer_lei_ck CHECK (
        (
            (lei_code IS NULL)
            OR (lei_code ~ '^[A-Z0-9]{20}$'::text)
        )
    );
ALTER TABLE ass.issuer
ADD CONSTRAINT issuer_pkey PRIMARY KEY (id);
ALTER TABLE ass.issuer_status
ADD CONSTRAINT issuer_status_code_key UNIQUE (code);
ALTER TABLE ass.issuer_status
ADD CONSTRAINT issuer_status_pkey PRIMARY KEY (id);
ALTER TABLE ass.payment_frequency_type
ADD CONSTRAINT pk_payment_frequency_type PRIMARY KEY (id);
ALTER TABLE ass.real_estate
ADD CONSTRAINT pk_real_estates PRIMARY KEY (id);
ALTER TABLE ass.real_estate
ADD CONSTRAINT real_estate_active_requires_token_ck CHECK (
        (
            (NOT active)
            OR (token_id IS NOT NULL)
        )
    );
ALTER TABLE ass.real_estate
ADD CONSTRAINT real_estate_deleted_not_tokenized_ck CHECK (
        (
            (deleted_at IS NULL)
            OR (token_id IS NULL)
        )
    );
ALTER TABLE ass.real_estate
ADD CONSTRAINT real_estate_deleted_status_ck CHECK (
        (
            (deleted_at IS NULL)
            OR (status_id = 7)
        )
    );
ALTER TABLE ass.real_estate_address
ADD CONSTRAINT real_estate_address_coordinates_ck CHECK (((latitude IS NULL) = (longitude IS NULL)));
ALTER TABLE ass.real_estate_address
ADD CONSTRAINT real_estate_address_country_code_ck CHECK ((country_code ~ '^[A-Z]{2}$'::text));
ALTER TABLE ass.real_estate_address
ADD CONSTRAINT real_estate_address_latitude_ck CHECK (
        (
            (latitude IS NULL)
            OR (
                (latitude >= ('-90'::integer)::numeric)
                AND (latitude <= (90)::numeric)
            )
        )
    );
ALTER TABLE ass.real_estate_address
ADD CONSTRAINT real_estate_address_longitude_ck CHECK (
        (
            (longitude IS NULL)
            OR (
                (longitude >= ('-180'::integer)::numeric)
                AND (longitude <= (180)::numeric)
            )
        )
    );
ALTER TABLE ass.real_estate_address
ADD CONSTRAINT real_estate_address_pkey PRIMARY KEY (real_estate_id);
ALTER TABLE ass.real_estate_media
ADD CONSTRAINT real_estate_media_pkey PRIMARY KEY (id);
ALTER TABLE ass.real_estate_media
ADD CONSTRAINT real_estate_media_position_ck CHECK (("position" >= 0));
ALTER TABLE ass.real_estate_media
ADD CONSTRAINT real_estate_media_type_ck CHECK (
        (
            media_type = ANY (
                ARRAY ['image'::text, 'video'::text, 'floorplan'::text, 'virtual_tour'::text]
            )
        )
    );
ALTER TABLE ass.real_estate_shares_config
ADD CONSTRAINT pk_real_estate_shares_config PRIMARY KEY (id);
ALTER TABLE ass.real_estate_shares_config
ADD CONSTRAINT real_estate_shares_config_currency_ck CHECK ((currency_code ~ '^[A-Z]{3}$'::text));
ALTER TABLE ass.real_estate_shares_config
ADD CONSTRAINT real_estate_shares_config_fees_ck CHECK (
        (
            (
                (entry_fee_rate IS NULL)
                OR (
                    (entry_fee_rate >= (0)::numeric)
                    AND (entry_fee_rate <= (100)::numeric)
                )
            )
            AND (
                (mgmt_fee_rate IS NULL)
                OR (
                    (mgmt_fee_rate >= (0)::numeric)
                    AND (mgmt_fee_rate <= (100)::numeric)
                )
            )
            AND (
                (exit_fee_rate IS NULL)
                OR (
                    (exit_fee_rate >= (0)::numeric)
                    AND (exit_fee_rate <= (100)::numeric)
                )
            )
        )
    );
ALTER TABLE ass.real_estate_shares_config
ADD CONSTRAINT real_estate_shares_config_investment_range_ck CHECK (
        (
            (min_investment IS NULL)
            OR (max_investment IS NULL)
            OR (min_investment <= max_investment)
        )
    );
ALTER TABLE ass.real_estate_shares_config
ADD CONSTRAINT real_estate_shares_config_price_per_share_ck CHECK (
        (
            (price_per_share IS NULL)
            OR (price_per_share >= (0)::numeric)
        )
    );
ALTER TABLE ass.real_estate_shares_config
ADD CONSTRAINT real_estate_shares_config_total_shares_ck CHECK (
        (
            (total_shares IS NULL)
            OR (total_shares > (0)::numeric)
        )
    );
ALTER TABLE ass.real_estate_specification
ADD CONSTRAINT pk_real_estate_specifications PRIMARY KEY (id);
ALTER TABLE ass.real_estate_specification
ADD CONSTRAINT real_estate_specification_built_year_ck CHECK (
        (
            (built_year IS NULL)
            OR (
                (built_year >= 1000)
                AND (built_year <= 2200)
            )
        )
    );
ALTER TABLE ass.real_estate_specification
ADD CONSTRAINT real_estate_specification_energy_class_ck CHECK (
        (
            (energy_class IS NULL)
            OR (
                (energy_class >= 'A'::bpchar)
                AND (energy_class <= 'G'::bpchar)
            )
        )
    );
ALTER TABLE ass.real_estate_specification
ADD CONSTRAINT real_estate_specification_ges_class_ck CHECK (
        (
            (ges_class IS NULL)
            OR (
                (ges_class >= 'A'::bpchar)
                AND (ges_class <= 'G'::bpchar)
            )
        )
    );
ALTER TABLE ass.real_estate_specification
ADD CONSTRAINT real_estate_specification_measures_ck CHECK (
        (
            (
                (lot_size IS NULL)
                OR (lot_size >= (0)::numeric)
            )
            AND (
                (surface_area IS NULL)
                OR (surface_area >= (0)::numeric)
            )
            AND (
                (pool_size IS NULL)
                OR (pool_size >= (0)::numeric)
            )
            AND (
                (terrace_size IS NULL)
                OR (terrace_size >= (0)::numeric)
            )
        )
    );
ALTER TABLE ass.real_estate_status
ADD CONSTRAINT real_estate_status_code_key UNIQUE (code);
ALTER TABLE ass.real_estate_status
ADD CONSTRAINT real_estate_status_pkey PRIMARY KEY (id);
ALTER TABLE ass.real_estate_type
ADD CONSTRAINT pk_estate_type PRIMARY KEY (id);
ALTER TABLE blk.chains
ADD CONSTRAINT chains_pkey PRIMARY KEY (id);
ALTER TABLE blk.contract_implementation
ADD CONSTRAINT contract_implementation_address_check CHECK (((address)::text ~ '^0x[a-fA-F0-9]{40}$'::text));
ALTER TABLE blk.contract_implementation
ADD CONSTRAINT contract_implementation_address_key UNIQUE (address);
ALTER TABLE blk.contract_implementation
ADD CONSTRAINT contract_implementation_contract_name_key UNIQUE (contract_name);
ALTER TABLE blk.contract_implementation
ADD CONSTRAINT contract_implementation_pkey PRIMARY KEY (id);
ALTER TABLE blk.contract_implementation
ADD CONSTRAINT contract_implementation_tx_hash_check CHECK (((tx_hash)::text ~ '^0x[a-fA-F0-9]{64}$'::text));
ALTER TABLE blk.contract_implementation
ADD CONSTRAINT contract_implementation_tx_hash_key UNIQUE (tx_hash);
ALTER TABLE blk.contract_instance
ADD CONSTRAINT contract_instance_address_unique UNIQUE (address);
ALTER TABLE blk.contract_instance
ADD CONSTRAINT contract_instance_pkey PRIMARY KEY (id);
ALTER TABLE blk.contract_role
ADD CONSTRAINT contract_address_check CHECK (((address)::text ~ '^0x[0-9a-fA-F]{40}$'::text));
ALTER TABLE blk.contract_role
ADD CONSTRAINT contract_pkey PRIMARY KEY (id);
ALTER TABLE blk.contract_role
ADD CONSTRAINT contract_role_contract_name_key UNIQUE (contract_name);
ALTER TABLE blk.contract_role
ADD CONSTRAINT contract_tx_hash_check CHECK (((tx_hash)::text ~ '^0x[0-9a-fA-F]{64}$'::text));
ALTER TABLE blk.eth_transaction
ADD CONSTRAINT eth_transaction_pkey PRIMARY KEY (id);
ALTER TABLE blk.eth_transaction
ADD CONSTRAINT eth_transaction_tx_hash_unique UNIQUE (tx_hash);
ALTER TABLE blk.identity
ADD CONSTRAINT identity_address_unique UNIQUE (address);
ALTER TABLE blk.identity
ADD CONSTRAINT identity_pkey PRIMARY KEY (id);
ALTER TABLE blk.identity
ADD CONSTRAINT identity_tx_hash_unique UNIQUE (tx_hash);
ALTER TABLE blk.token
ADD CONSTRAINT modular_compliance_addr_check CHECK (
        (
            (modular_compliance_addr IS NULL)
            OR (
                (modular_compliance_addr)::text ~ '^0x[a-fA-F0-9]{40}$'::text
            )
        )
    );
ALTER TABLE blk.token
ADD CONSTRAINT token_addr_check CHECK (((address)::text ~ '^0x[a-fA-F0-9]{40}$'::text));
ALTER TABLE blk.token
ADD CONSTRAINT token_name_unique UNIQUE (token_name);
ALTER TABLE blk.token
ADD CONSTRAINT token_nb_decimal_ck CHECK (
        (
            (nb_decimal >= 0)
            AND (nb_decimal <= 18)
        )
    ) NOT VALID;
ALTER TABLE blk.token
ADD CONSTRAINT token_pkey PRIMARY KEY (id);
ALTER TABLE blk.token
ADD CONSTRAINT token_salt_not_empty_ck CHECK (
        (
            (salt IS NULL)
            OR (salt <> ''::text)
        )
    );
ALTER TABLE blk.token_transaction
ADD CONSTRAINT token_transaction_pkey PRIMARY KEY (id);
ALTER TABLE blk.token_transaction
ADD CONSTRAINT tx_hash_check CHECK (((tx_hash)::text ~ '^0x[a-fA-F0-9]{64}$'::text));
ALTER TABLE blk.user_wallet
ADD CONSTRAINT user_wallet_pkey PRIMARY KEY (id);
ALTER TABLE blk.user_wallet
ADD CONSTRAINT user_wallet_wallet_address_key UNIQUE (wallet_address);
ALTER TABLE iss.issuance_allocations
ADD CONSTRAINT issuance_allocations_pkey PRIMARY KEY (id);
ALTER TABLE iss.issuance_allocations
ADD CONSTRAINT issuance_allocations_quantity_check CHECK ((quantity > 0));
ALTER TABLE iss.issuance_order_statuses
ADD CONSTRAINT issuance_order_statuses_code_key UNIQUE (code);
ALTER TABLE iss.issuance_order_statuses
ADD CONSTRAINT issuance_order_statuses_pkey PRIMARY KEY (id);
ALTER TABLE iss.issuance_orders
ADD CONSTRAINT issuance_orders_order_reference_uk UNIQUE (order_reference);
ALTER TABLE iss.issuance_orders
ADD CONSTRAINT issuance_orders_pkey PRIMARY KEY (id);
ALTER TABLE iss.issuance_orders
ADD CONSTRAINT issuance_orders_quantity_check CHECK ((quantity > 0));
ALTER TABLE rel.user_asset_favorite
ADD CONSTRAINT uq_user_asset_favorite UNIQUE (user_id, real_estate_id);
ALTER TABLE rel.user_asset_favorite
ADD CONSTRAINT user_asset_favorite_pkey PRIMARY KEY (id);
ALTER TABLE usr.users
ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE usr.users
ADD CONSTRAINT users_kyc_expiry_ck CHECK (
        (
            (kyc_expires_at IS NULL)
            OR (kyc_verified_at IS NULL)
            OR (kyc_expires_at > kyc_verified_at)
        )
    );
ALTER TABLE usr.users
ADD CONSTRAINT users_kyc_status_ck CHECK (
        (
            kyc_status = ANY (
                ARRAY ['none'::text, 'pending'::text, 'verified'::text, 'rejected'::text, 'expired'::text]
            )
        )
    );
ALTER TABLE usr.users
ADD CONSTRAINT users_kyc_verified_at_ck CHECK (
        (
            (kyc_status <> 'verified'::text)
            OR (kyc_verified_at IS NOT NULL)
        )
    );
ALTER TABLE usr.users
ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE usr.users
ADD CONSTRAINT users_role_ck CHECK (
        (
            role = ANY (
                ARRAY ['USER'::text, 'MANAGER'::text, 'ADMIN'::text]
            )
        )
    );
ALTER TABLE ass.issuer
ADD CONSTRAINT issuer_status_id_fkey FOREIGN KEY (status_id) REFERENCES ass.issuer_status(id);
ALTER TABLE ass.real_estate
ADD CONSTRAINT real_estate_estate_type_fkey FOREIGN KEY (estate_type) REFERENCES ass.real_estate_type(id) ON DELETE RESTRICT;
ALTER TABLE ass.real_estate
ADD CONSTRAINT real_estate_issuer_id_fkey FOREIGN KEY (issuer_id) REFERENCES ass.issuer(id) ON DELETE RESTRICT;
ALTER TABLE ass.real_estate
ADD CONSTRAINT real_estate_status_id_fkey FOREIGN KEY (status_id) REFERENCES ass.real_estate_status(id);
ALTER TABLE ass.real_estate
ADD CONSTRAINT real_estate_token_id_fkey FOREIGN KEY (token_id) REFERENCES blk.token(id) ON DELETE RESTRICT;
ALTER TABLE ass.real_estate_address
ADD CONSTRAINT real_estate_address_real_estate_id_fkey FOREIGN KEY (real_estate_id) REFERENCES ass.real_estate(id) ON DELETE CASCADE;
ALTER TABLE ass.real_estate_media
ADD CONSTRAINT real_estate_media_real_estate_id_fkey FOREIGN KEY (real_estate_id) REFERENCES ass.real_estate(id) ON DELETE CASCADE;
ALTER TABLE ass.real_estate_shares_config
ADD CONSTRAINT fk_real_estate_shares_config_real_estate FOREIGN KEY (real_estate_id) REFERENCES ass.real_estate(id) ON DELETE CASCADE;
ALTER TABLE ass.real_estate_specification
ADD CONSTRAINT fk_real_estate_specification_real_estate FOREIGN KEY (real_estate_id) REFERENCES ass.real_estate(id) ON DELETE CASCADE;
ALTER TABLE blk.contract_implementation
ADD CONSTRAINT fk_contract_impl_chain FOREIGN KEY (chain_id) REFERENCES blk.chains(id);
ALTER TABLE blk.contract_instance
ADD CONSTRAINT contract_instance_contract_implementation_id_fkey FOREIGN KEY (contract_implementation_id) REFERENCES blk.contract_implementation(id);
ALTER TABLE blk.contract_instance
ADD CONSTRAINT contract_instance_parent_contract_id_fkey FOREIGN KEY (parent_contract_id) REFERENCES blk.contract_role(id);
ALTER TABLE blk.contract_instance
ADD CONSTRAINT fk_contract_instance_chain FOREIGN KEY (chain_id) REFERENCES blk.chains(id);
ALTER TABLE blk.identity
ADD CONSTRAINT identity_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES blk.user_wallet(id);
ALTER TABLE blk.token_transaction
ADD CONSTRAINT token_transaction_token_id_fkey FOREIGN KEY (token_id) REFERENCES blk.token(id) ON DELETE CASCADE;
ALTER TABLE iss.issuance_allocations
ADD CONSTRAINT fk_issuance_allocations_order FOREIGN KEY (issuance_order_id) REFERENCES iss.issuance_orders(id) ON DELETE CASCADE;
ALTER TABLE iss.issuance_allocations
ADD CONSTRAINT issuance_allocations_issuance_order_id_fkey FOREIGN KEY (issuance_order_id) REFERENCES iss.issuance_orders(id) ON DELETE CASCADE;
ALTER TABLE iss.issuance_orders
ADD CONSTRAINT fk_issuance_orders_asset FOREIGN KEY (asset_id) REFERENCES ass.real_estate(id) ON DELETE RESTRICT;
ALTER TABLE iss.issuance_orders
ADD CONSTRAINT fk_issuance_orders_status FOREIGN KEY (status_id) REFERENCES iss.issuance_order_statuses(id);
ALTER TABLE iss.issuance_orders
ADD CONSTRAINT fk_issuance_orders_user FOREIGN KEY (user_id) REFERENCES usr.users(id) ON DELETE RESTRICT;
ALTER TABLE rel.user_asset_favorite
ADD CONSTRAINT fk_fav_asset FOREIGN KEY (real_estate_id) REFERENCES ass.real_estate(id) ON DELETE CASCADE;
ALTER TABLE rel.user_asset_favorite
ADD CONSTRAINT fk_fav_user FOREIGN KEY (user_id) REFERENCES usr.users(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX issuer_lei_uk ON ass.issuer USING btree (lei_code)
WHERE (lei_code IS NOT NULL);
CREATE UNIQUE INDEX issuer_registration_uk ON ass.issuer USING btree (country_code, registration_number)
WHERE (registration_number IS NOT NULL);
CREATE INDEX real_estate_address_country_city_idx ON ass.real_estate_address USING btree (country_code, city);
CREATE INDEX real_estate_estate_type_idx ON ass.real_estate USING btree (estate_type);
CREATE INDEX real_estate_issuer_id_idx ON ass.real_estate USING btree (issuer_id);
CREATE INDEX real_estate_media_real_estate_position_idx ON ass.real_estate_media USING btree (real_estate_id, "position");
CREATE UNIQUE INDEX real_estate_media_single_cover_uk ON ass.real_estate_media USING btree (real_estate_id)
WHERE is_cover;
CREATE INDEX real_estate_not_deleted_idx ON ass.real_estate USING btree (id)
WHERE (deleted_at IS NULL);
CREATE UNIQUE INDEX real_estate_shares_config_compartment_ref_uk ON ass.real_estate_shares_config USING btree (compartment_ref)
WHERE (compartment_ref IS NOT NULL);
CREATE UNIQUE INDEX real_estate_shares_config_real_estate_uk ON ass.real_estate_shares_config USING btree (real_estate_id);
CREATE UNIQUE INDEX real_estate_specification_real_estate_uk ON ass.real_estate_specification USING btree (real_estate_id);
CREATE INDEX real_estate_status_id_idx ON ass.real_estate USING btree (status_id);
CREATE UNIQUE INDEX real_estate_token_id_uk ON ass.real_estate USING btree (token_id)
WHERE (token_id IS NOT NULL);
CREATE INDEX idx_address ON blk.contract_implementation USING btree (address);
CREATE INDEX idx_contract_address ON blk.contract_role USING btree (address);
CREATE INDEX idx_contract_cname ON blk.contract_role USING btree (contract_name);
CREATE INDEX idx_contract_name ON blk.contract_implementation USING btree (contract_name);
CREATE INDEX idx_contract_tx_hash ON blk.contract_role USING btree (tx_hash);
CREATE INDEX idx_eth_tx_block ON blk.eth_transaction USING btree (block_number);
CREATE INDEX idx_eth_tx_name ON blk.eth_transaction USING btree (tx_name);
CREATE INDEX idx_eth_tx_to ON blk.eth_transaction USING btree (to_address);
CREATE INDEX idx_identity_user_id ON blk.identity USING btree (user_id);
CREATE INDEX idx_identity_wallet_id ON blk.identity USING btree (wallet_id);
CREATE INDEX idx_tx_hash ON blk.contract_implementation USING btree (tx_hash);
CREATE INDEX idx_user_wallet_user_id ON blk.user_wallet USING btree (user_id);
CREATE UNIQUE INDEX token_salt_uk ON blk.token USING btree (salt)
WHERE (salt IS NOT NULL);
CREATE INDEX issuance_orders_asset_status_idx ON iss.issuance_orders USING btree (asset_id, status_id);
CREATE INDEX issuance_orders_user_idx ON iss.issuance_orders USING btree (user_id);
CREATE UNIQUE INDEX users_email_uk ON usr.users USING btree (lower((email)::text));
CREATE INDEX users_role_kyc_idx ON usr.users USING btree (role, kyc_status);
ALTER SEQUENCE ass.issuer_id_seq OWNED BY ass.issuer.id;
ALTER SEQUENCE ass.real_estate_media_id_seq OWNED BY ass.real_estate_media.id;
ALTER SEQUENCE blk.contract_id_seq OWNED BY blk.contract_role.id;
ALTER SEQUENCE blk.contract_implementation_id_seq OWNED BY blk.contract_implementation.id;
ALTER SEQUENCE blk.token_id_seq OWNED BY blk.token.id;
ALTER SEQUENCE blk.token_transaction_id_seq OWNED BY blk.token_transaction.id;
ALTER SEQUENCE iss.issuance_allocations_id_seq OWNED BY iss.issuance_allocations.id;
ALTER SEQUENCE iss.issuance_order_statuses_id_seq OWNED BY iss.issuance_order_statuses.id;
ALTER SEQUENCE iss.issuance_orders_id_seq OWNED BY iss.issuance_orders.id;
ALTER SEQUENCE rel.user_asset_favorite_id_seq OWNED BY rel.user_asset_favorite.id;
ALTER SEQUENCE usr.users_id_seq OWNED BY usr.users.id;
CREATE TRIGGER real_estate_sync_active_trg BEFORE
INSERT
    OR
UPDATE ON ass.real_estate FOR EACH ROW EXECUTE FUNCTION ass.real_estate_sync_active();
CREATE TRIGGER real_estate_sync_contract_address_trg BEFORE
INSERT
    OR
UPDATE OF token_id ON ass.real_estate FOR EACH ROW EXECUTE FUNCTION ass.real_estate_sync_contract_address();
INSERT INTO ass.issuer_status (id, code, label, is_final)
VALUES (1, 'draft', 'Brouillon', 'f') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.issuer_status (id, code, label, is_final)
VALUES (2, 'active', 'Actif', 'f') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.issuer_status (id, code, label, is_final)
VALUES (3, 'suspended', 'Suspendu', 'f') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.issuer_status (id, code, label, is_final)
VALUES (4, 'dissolved', 'Dissous', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.payment_frequency_type (id, name)
VALUES (1, 'MINUTE') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.payment_frequency_type (id, name)
VALUES (2, 'HOUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.payment_frequency_type (id, name)
VALUES (3, 'DAY') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.payment_frequency_type (id, name)
VALUES (4, 'MONTH') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.payment_frequency_type (id, name)
VALUES (5, 'YEAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position")
VALUES (1, 'draft', 'Brouillon', 'f', 'f', 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position")
VALUES (2, 'in_review', 'En revue', 'f', 'f', 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position")
VALUES (3, 'published', 'Publié', 'f', 't', 30) ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position")
VALUES (4, 'fundraising', 'En levée', 'f', 't', 40) ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position")
VALUES (5, 'funded', 'Financé', 'f', 't', 50) ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position")
VALUES (6, 'closed', 'Clôturé', 't', 'f', 60) ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position")
VALUES (7, 'cancelled', 'Annulé', 't', 'f', 70) ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_type (id, name, active)
VALUES (1, 'building', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_type (id, name, active)
VALUES (2, 'business building', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_type (id, name, active)
VALUES (3, 'local commercial', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO ass.real_estate_type (id, name, active)
VALUES (4, 'warehouse', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved)
VALUES (1, 'CREATED', 'Order created', 'f', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved)
VALUES (2, 'RESERVED', 'Tokens reserved', 'f', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved)
VALUES (
        3,
        'PAYMENT_PENDING',
        'Payment pending',
        'f',
        't'
    ) ON CONFLICT (id) DO NOTHING;
INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved)
VALUES (
        4,
        'PAYMENT_CONFIRMED',
        'Payment confirmed',
        'f',
        't'
    ) ON CONFLICT (id) DO NOTHING;
INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved)
VALUES (5, 'COMPLETED', 'Tokens delivered', 't', 't') ON CONFLICT (id) DO NOTHING;
INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved)
VALUES (6, 'CANCELLED', 'Order cancelled', 't', 'f') ON CONFLICT (id) DO NOTHING;
INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved)
VALUES (7, 'EXPIRED', 'Reservation expired', 't', 'f') ON CONFLICT (id) DO NOTHING;
SELECT setval(
        pg_get_serial_sequence('ass.issuer_status', 'id'),
        (
            SELECT COALESCE(max(id), 0) + 1
            FROM ass.issuer_status
        ),
        false
    );
SELECT setval(
        pg_get_serial_sequence('ass.payment_frequency_type', 'id'),
        (
            SELECT COALESCE(max(id), 0) + 1
            FROM ass.payment_frequency_type
        ),
        false
    );
SELECT setval(
        pg_get_serial_sequence('ass.real_estate_status', 'id'),
        (
            SELECT COALESCE(max(id), 0) + 1
            FROM ass.real_estate_status
        ),
        false
    );
SELECT setval(
        pg_get_serial_sequence('ass.real_estate_type', 'id'),
        (
            SELECT COALESCE(max(id), 0) + 1
            FROM ass.real_estate_type
        ),
        false
    );
SELECT setval(
        pg_get_serial_sequence('iss.issuance_order_statuses', 'id'),
        (
            SELECT COALESCE(max(id), 0) + 1
            FROM iss.issuance_order_statuses
        ),
        false
    );
COMMENT ON COLUMN ass.real_estate.active IS 'Projection of status_id through ass.real_estate_status.is_public, maintained by real_estate_sync_active_trg. Read-only in practice: writing it has no effect, the trigger recomputes it from status_id on every write. It exists because the listing and the detail queries filter on it; status_id is the value to set.';
COMMENT ON COLUMN ass.real_estate.created_at IS 'Creation instant. Timestamptz like every other date of the table: a registry compares instants, not wall clocks.';
COMMENT ON COLUMN ass.real_estate.deleted_at IS 'Soft deletion timestamp. NULL means the asset exists. Non-NULL implies status_id = 7 (cancelled) and forbids tokenization.';
COMMENT ON COLUMN ass.real_estate.imageurl IS 'Legacy cover image. The gallery of ass.real_estate_media is the model going forward; this column is kept until the front stops reading it.';
COMMENT ON COLUMN ass.real_estate.issuer_id IS 'The legal vehicle issuing the shares. Mandatory: a token represents a stake in an issuer, never in the walls themselves (decision A1). The API refuses a creation without it (400); this constraint answers for every other writer.';
COMMENT ON COLUMN ass.real_estate_status.is_public IS 'Whether an asset in this status is served to the public — and, since 000021, the single source of ass.real_estate.active. Changing it here does not update assets already stored: any migration that does must follow with UPDATE ass.real_estate SET status_id = status_id on the affected rows.';
COMMENT ON TABLE blk.contract_instance IS 'contracts deployed by trex suite';
COMMENT ON TABLE blk.contract_role IS 'Directory of the platform singletons: which address plays which role (TREX_FACTORY, CLAIM_ISSUER, TRANSFER_RESTRICTION_MODULE, SHARED_IRS). A designation, not an inventory - contract_instance records what was deployed. contract_name is the business key and the only lookup path.';
COMMENT ON COLUMN blk.contract_role.address IS 'Not unique: a T-REX suite has no address of its own, so the same contract legitimately holds several roles. Canonical form is EIP-55 checksummed, the form common.Address.Hex() produces; readers must canonicalise any address they receive before comparing, since this is a case-sensitive varchar.';
COMMENT ON COLUMN blk.contract_role.contract_name IS 'The role played, not the contract type. Unique: every reader resolves a role through this column alone. Mind the distinction with the implementation key - IDENTITY_REGISTRY_STORAGE names the deployed logic in contract_implementation, while SHARED_IRS names the role of being the one investor whitelist shared by every token.';
COMMENT ON COLUMN blk.contract_role.tx_hash IS 'Not unique: one factory transaction deploys six contracts, so several roles legitimately share the transaction that created them.';
COMMENT ON COLUMN blk.token.salt IS 'Salt handed to the T-REX factory at deployment. Built by defineSalt as "re-<asset id>" for a tokenised asset, and equal to token_name for the manual POST /contract/token path. It is what tokenForPublication resolves on before deploying, so that a deployment interrupted before the asset was bound can be adopted on replay instead of being deployed twice. Derived from a primary key, it is stable even when the title — and therefore token_name — changes. NULL means "not recorded", which is the case for every token created before this migration that carries no asset.';
COMMENT ON COLUMN blk.token.token_name IS 'Visible name of the token, built as "Tooken <title> #<asset id>" by defineTokenName. Unique because it is the idempotency key CreateToken resolves on: two tokens sharing a name would let a replayed deployment bind an asset to the wrong contract address.';
COMMENT ON COLUMN iss.issuance_order_statuses.counts_as_reserved IS 'Un ordre dans ce statut immobilise-t-il les parts commandees ? FALSE uniquement pour les etats qui les relachent (annulation, expiration, refus, echec). Tout nouveau statut doit fixer ce drapeau explicitement.';
COMMENT ON CONSTRAINT real_estate_active_requires_token_ck ON ass.real_estate IS 'No asset can be on sale without a token behind it. Added NOT VALID by 000021 so the legacy rows would not block it, validated by 000022 once they were cleared — so it now holds for stored rows as well as new ones.';
COMMENT ON CONSTRAINT fk_issuance_orders_asset ON iss.issuance_orders IS 'RESTRICT, not CASCADE: an order is a financial record and must survive the removal of the listing. Assets are retired with status_id = 7 and deleted_at, never with a DELETE.';