-- Extract a replayable schema baseline from a live database.
--
-- ⚠️  RUN THIS WHOLE FILE, NOT JUST THE QUERY.
--
-- The SET below is part of the extraction, not a preference. pg_get_expr,
-- pg_get_constraintdef and pg_get_indexdef render object names relatively to
-- the extracting session's search_path: anything reachable through it comes out
-- unqualified. Extracting from the Aiven console, whose search_path carries the
-- business schemas, produced REFERENCES token(id) and nextval('token_id_seq')
-- — eleven names that resolve to nothing on a fresh database.
--
-- An empty search_path forces every name to be qualified at the source, which
-- is the only place the problem can be fixed. Compensating afterwards with a
-- search_path header in the output only re-resolves those bare names by luck:
-- two schemas holding a table of the same name would silently bind to the
-- wrong one.
--
-- Everything this script reads is schema-qualified already, so emptying the
-- path costs nothing. pg_catalog stays implicitly searchable, which is why the
-- ::regclass casts below still work.
SET search_path = '';

WITH ns AS (
    SELECT oid, nspname
    FROM pg_namespace
    WHERE nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast', 'public')
      AND nspname NOT LIKE 'pg\_%'
      AND nspname NOT LIKE 'aiven%'
      AND nspname <> 'cron'
), parts AS (

    -- The replayed file gets an empty search_path too, and that is a safety
    -- net rather than a formality: every name the extraction emits is
    -- qualified, so any bare name left in the output is a bug in this script.
    -- With no path to fall back on, such a name fails loudly on replay instead
    -- of quietly binding to whichever schema happens to come first.
    SELECT 0 AS ord, '' AS o2, '' AS o3,
           'SET search_path = '''';' AS ddl

    UNION ALL

    SELECT 1 AS ord, ns.nspname AS o2, '' AS o3,
           format('CREATE SCHEMA IF NOT EXISTS %I;', ns.nspname) AS ddl
    FROM ns

    UNION ALL

    SELECT 2, ns.nspname, t.typname,
           format('CREATE TYPE %I.%I AS ENUM (%s);',
                  ns.nspname, t.typname,
                  (SELECT string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder)
                     FROM pg_enum e WHERE e.enumtypid = t.oid))
    FROM pg_type t
    JOIN ns ON ns.oid = t.typnamespace
    WHERE t.typtype = 'e'

    UNION ALL

    SELECT 3, ns.nspname, t.typname,
           format('CREATE DOMAIN %I.%I AS %s%s%s;',
                  ns.nspname, t.typname,
                  format_type(t.typbasetype, t.typtypmod),
                  CASE WHEN t.typnotnull THEN ' NOT NULL' ELSE '' END,
                  COALESCE((SELECT ' ' || string_agg(pg_get_constraintdef(dc.oid), ' ')
                              FROM pg_constraint dc WHERE dc.contypid = t.oid), ''))
    FROM pg_type t
    JOIN ns ON ns.oid = t.typnamespace
    WHERE t.typtype = 'd'

    UNION ALL

    SELECT 3.5, ns.nspname, p.proname,
           pg_get_functiondef(p.oid) || ';'
    FROM pg_proc p
    JOIN ns ON ns.oid = p.pronamespace
    WHERE p.prokind IN ('f', 'p')

    UNION ALL

    SELECT 4, ns.nspname, c.relname,
           format('CREATE SEQUENCE IF NOT EXISTS %I.%I AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s %s;',
                  ns.nspname, c.relname,
                  format_type(s.seqtypid, NULL),
                  s.seqincrement, s.seqmin, s.seqmax, s.seqstart,
                  CASE WHEN s.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END)
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    JOIN pg_sequence s ON s.seqrelid = c.oid
    WHERE c.relkind = 'S'
      AND NOT EXISTS (SELECT 1 FROM pg_depend dep
                       WHERE dep.objid = c.oid
                         AND dep.classid = 'pg_class'::regclass
                         AND dep.deptype = 'i')

    UNION ALL

    SELECT 5, ns.nspname, c.relname,
           format(E'CREATE TABLE IF NOT EXISTS %I.%I (\n%s\n);',
                  ns.nspname, c.relname,
                  (SELECT string_agg(
                              '    ' || format('%I %s%s%s',
                                  a.attname,
                                  format_type(a.atttypid, a.atttypmod),
                                  CASE
                                      WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                                      WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                                      WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
                                      ELSE COALESCE(' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid), '')
                                  END,
                                  CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),
                              E',\n' ORDER BY a.attnum)
                     FROM pg_attribute a
                     LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
                    WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped))
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    WHERE c.relkind IN ('r', 'p')

    UNION ALL

    SELECT 6, ns.nspname, c.relname || '.' || con.conname,
           format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s;',
                  ns.nspname, c.relname, con.conname, pg_get_constraintdef(con.oid))
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE con.contype IN ('p', 'u', 'c')

    UNION ALL

    SELECT 7, ns.nspname, c.relname || '.' || con.conname,
           format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s;',
                  ns.nspname, c.relname, con.conname, pg_get_constraintdef(con.oid))
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE con.contype = 'f'

    UNION ALL

    SELECT 8, ns.nspname, ic.relname,
           pg_get_indexdef(i.indexrelid) || ';'
    FROM pg_index i
    JOIN pg_class ic ON ic.oid = i.indexrelid
    JOIN pg_class c ON c.oid = i.indrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE NOT EXISTS (SELECT 1 FROM pg_constraint con
                       WHERE con.conindid = i.indexrelid
                         AND con.contype IN ('p', 'u', 'x'))

    UNION ALL

    SELECT 9, ns.nspname, c.relname,
           format('ALTER SEQUENCE %I.%I OWNED BY %I.%I.%I;',
                  ns.nspname, c.relname, tns.nspname, t.relname, a.attname)
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    JOIN pg_depend d ON d.objid = c.oid
                    AND d.classid = 'pg_class'::regclass
                    AND d.deptype = 'a'
    JOIN pg_class t ON t.oid = d.refobjid
    JOIN pg_namespace tns ON tns.oid = t.relnamespace
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
    WHERE c.relkind = 'S'

    UNION ALL

    SELECT 10, ns.nspname, c.relname,
           format(E'CREATE OR REPLACE VIEW %I.%I AS\n%s', ns.nspname, c.relname,
                  pg_get_viewdef(c.oid, true))
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    WHERE c.relkind = 'v'

    UNION ALL

    SELECT 11, ns.nspname, c.relname || '.' || t.tgname,
           pg_get_triggerdef(t.oid) || ';'
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE NOT t.tgisinternal

    UNION ALL

    -- Reference data, and only reference data.
    --
    -- Migrations 000006 and 000007 create these two lookup tables and fill them
    -- in the same breath. A baseline taken at version 17 is replayed with the
    -- counter forced past both, so their INSERT statements never run and every
    -- status foreign key fails on the first real row.
    --
    -- These rows are read from the live database rather than copied out of the
    -- migrations, so a status added in production reaches the baseline on the
    -- next extraction instead of quietly going missing. The list below is
    -- deliberately explicit: a table that holds business rows has no place in a
    -- schema baseline, and guessing which is which from the catalog would sooner
    -- or later export somebody's data.
    SELECT 12, 'ass', 'issuer_status',
           string_agg(
               format('INSERT INTO ass.issuer_status (id, code, label, is_final) VALUES (%s, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.code, s.label, s.is_final),
               E'\n' ORDER BY s.id)
    FROM ass.issuer_status s

    UNION ALL

    SELECT 12, 'ass', 'real_estate_status',
           string_agg(
               format('INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position") VALUES (%s, %L, %L, %L, %L, %s) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.code, s.label, s.is_final, s.is_public, s."position"),
               E'\n' ORDER BY s.id)
    FROM ass.real_estate_status s

    UNION ALL

    -- The two lookup tables below were missing from this script until a test
    -- tried to create an asset on a database rebuilt from the baseline:
    --
    --   pq: insert or update on table "real_estate" violates foreign key
    --       constraint "real_estate_estate_type_fkey"
    --
    -- Nothing had caught it because real_estate_write_integration_test.go seeds
    -- both tables itself before its fixtures. The suite therefore stayed green
    -- on a baseline that could not, on its own, hold a single asset — the
    -- fixture was hiding the hole rather than revealing it.
    --
    -- Which is the reason they belong here and not in a fixture: a reference
    -- table an asset cannot exist without is part of the schema, not part of a
    -- test's setup.
    SELECT 12, 'ass', 'real_estate_type',
           string_agg(
               format('INSERT INTO ass.real_estate_type (id, name, active) VALUES (%s, %L, %L) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.name, s.active),
               E'\n' ORDER BY s.id)
    FROM ass.real_estate_type s

    UNION ALL

    SELECT 12, 'ass', 'payment_frequency_type',
           string_agg(
               format('INSERT INTO ass.payment_frequency_type (id, name) VALUES (%s, %L) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.name),
               E'\n' ORDER BY s.id)
    FROM ass.payment_frequency_type s

    UNION ALL

    -- This one is worse than the two above: no migration creates it either.
    -- 000010 already speaks of "the existing reference table", so it predates
    -- the migration history entirely. A database built from the migrations
    -- alone gets the table from nowhere and its rows from nowhere, and the
    -- first order written fails on fk_issuance_orders_status.
    SELECT 12, 'iss', 'issuance_order_statuses',
           string_agg(
               format('INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved) VALUES (%s, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.code, s.label, s.is_final, s.counts_as_reserved),
               E'\n' ORDER BY s.id)
    FROM iss.issuance_order_statuses s

    UNION ALL

    -- Sequences, put back where the rows above left them.
    --
    -- The reference tables above are inserted with explicit ids, which does not
    -- move the sequence behind the column. A database rebuilt from this
    -- baseline therefore holds seven statuses and a sequence still sitting at
    -- 1, and the next insert dies on "duplicate key value violates unique
    -- constraint". That failure has already been paid for once, in the commit
    -- that resynchronised the identity sequences.
    --
    -- The value is computed on replay, not frozen here, so it follows whatever
    -- the INSERTs above actually wrote. is_called = false means "hand out this
    -- number next", which keeps id 1 available on a table that is empty rather
    -- than skipping it.
    --
    -- ⚠️  THE SEQUENCE NAME IS RESOLVED ON REPLAY, NOT HERE
    --   Writing the name this script sees was wrong, and it broke the moment a
    --   table whose sequence does not follow the default naming was added:
    --   ass.real_estate_type carries ass.estate_type_id_seq in production — a
    --   name left over from before the table was renamed — while a database
    --   rebuilt from the CREATE TABLE above gets ass.real_estate_type_id_seq.
    --   Replaying the frozen name gave:
    --
    --     ERROR: relation "ass.estate_type_id_seq" does not exist
    --
    --   and, with ON_ERROR_STOP, everything after that point was lost.
    --
    --   pg_get_serial_sequence is therefore emitted as-is and evaluated by the
    --   target, which is the only database that knows how its own sequences are
    --   named. A baseline must not carry the source's naming accidents.
    --
    -- WHY THERE IS NO LONGER A WHERE CLAUSE
    --   It used to skip tables that had no sequence on the source. That is the
    --   wrong side to ask: setval is strict, so a table without one on the
    --   target makes pg_get_serial_sequence return NULL and the whole call
    --   returns NULL, quietly and without error. The target decides, as it
    --   should.
    --
    -- The list must stay in step with the reference tables exported above: a
    -- table seeded with explicit ids and left out here is a duplicate key
    -- waiting for the first insert after a rebuild.
    SELECT 12.5, split_part(t.tbl, '.', 1), split_part(t.tbl, '.', 2),
           format('SELECT setval(pg_get_serial_sequence(%L, ''id''), (SELECT COALESCE(max(id), 0) + 1 FROM %s), false);',
                  t.tbl, t.tbl)
    FROM (VALUES ('ass.issuer_status'),
                 ('ass.real_estate_status'),
                 ('ass.real_estate_type'),
                 ('ass.payment_frequency_type'),
                 ('iss.issuance_order_statuses')) AS t(tbl)

    UNION ALL

    -- Comments, which are not decoration in this repository.
    --
    -- The migrations carry fifteen COMMENT statements, and several hold the
    -- reasoning behind a constraint rather than a description of it: why
    -- issuer_id is mandatory, what counts_as_reserved means and why it cannot
    -- be derived from is_final, how a token name is built and what breaks if
    -- two tokens share one.
    --
    -- A baseline replayed with the counter forced past those migrations drops
    -- every one of them: the rebuilt database keeps the rules and loses the
    -- reasons. Extracting them puts the reasoning back where a developer meets
    -- it, in \d+ on the table he is about to change.
    SELECT 13, ns.nspname, c.relname || '.' || COALESCE(a.attname, ''),
           format('COMMENT ON %s %s IS %L;',
                  CASE WHEN d.objsubid = 0 THEN 'TABLE' ELSE 'COLUMN' END,
                  CASE WHEN d.objsubid = 0
                       THEN format('%I.%I', ns.nspname, c.relname)
                       ELSE format('%I.%I.%I', ns.nspname, c.relname, a.attname)
                  END,
                  d.description)
    FROM pg_description d
    JOIN pg_class c ON c.oid = d.objoid
    JOIN ns ON ns.oid = c.relnamespace
    LEFT JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = d.objsubid
    WHERE d.classoid = 'pg_class'::regclass
      AND c.relkind IN ('r', 'v')
      AND (d.objsubid = 0 OR a.attname IS NOT NULL)

    UNION ALL

    SELECT 14, ns.nspname, con.conname,
           format('COMMENT ON CONSTRAINT %I ON %I.%I IS %L;',
                  con.conname, ns.nspname, c.relname, d.description)
    FROM pg_description d
    JOIN pg_constraint con ON con.oid = d.objoid
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE d.classoid = 'pg_constraint'::regclass

)
SELECT string_agg(ddl, E'\n' ORDER BY ord, o2, o3) AS baseline
FROM parts;
