WITH ns AS (
    SELECT oid, nspname
    FROM pg_namespace
    WHERE nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast', 'public')
      AND nspname NOT LIKE 'pg\_%'
      AND nspname NOT LIKE 'aiven%'
      AND nspname <> 'cron'
), parts AS (

    -- A self-contained header, and it is not a nicety.
    --
    -- pg_get_expr, pg_get_constraintdef and pg_get_indexdef render object names
    -- relative to the extracting session's search_path: anything reachable
    -- through it comes out unqualified. Extracting from a console whose
    -- search_path contains 'blk' yields nextval('token_id_seq') and
    -- REFERENCES token(id), which resolve to nothing on a fresh database.
    --
    -- Rather than qualify them after the fact, the script carries the same
    -- search_path it was born with, so the bare names resolve again on replay.
    -- Extracting with SET search_path = '' makes every name qualified and
    -- renders this line harmless, which is the better habit.
    SELECT 0 AS ord, '' AS o2, '' AS o3,
           format('SET search_path = %s, public;',
                  (SELECT string_agg(quote_ident(nspname), ', ' ORDER BY nspname)
                   FROM ns)) AS ddl

    UNION ALL

    SELECT 1 AS ord, ns.nspname AS o2, '' AS o3,
           format('CREATE SCHEMA IF NOT EXISTS %I;', ns.nspname) AS ddl
    FROM ns

    UNION ALL

    SELECT 2, ns.nspname, t.typname,
           format('CREATE TYPE %I.%I AS ENUM (%s);',
                  ns.nspname, t.typname,
                  (SELECT string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder)
                     FROM pg_enum e WHERE e.enumtypid = t.oid))
    FROM pg_type t
    JOIN ns ON ns.oid = t.typnamespace
    WHERE t.typtype = 'e'

    UNION ALL

    SELECT 3, ns.nspname, t.typname,
           format('CREATE DOMAIN %I.%I AS %s%s%s;',
                  ns.nspname, t.typname,
                  format_type(t.typbasetype, t.typtypmod),
                  CASE WHEN t.typnotnull THEN ' NOT NULL' ELSE '' END,
                  COALESCE((SELECT ' ' || string_agg(pg_get_constraintdef(dc.oid), ' ')
                              FROM pg_constraint dc WHERE dc.contypid = t.oid), ''))
    FROM pg_type t
    JOIN ns ON ns.oid = t.typnamespace
    WHERE t.typtype = 'd'

    UNION ALL

    SELECT 3.5, ns.nspname, p.proname,
           pg_get_functiondef(p.oid) || ';'
    FROM pg_proc p
    JOIN ns ON ns.oid = p.pronamespace
    WHERE p.prokind IN ('f', 'p')

    UNION ALL

    SELECT 4, ns.nspname, c.relname,
           format('CREATE SEQUENCE IF NOT EXISTS %I.%I AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s %s;',
                  ns.nspname, c.relname,
                  format_type(s.seqtypid, NULL),
                  s.seqincrement, s.seqmin, s.seqmax, s.seqstart,
                  CASE WHEN s.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END)
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    JOIN pg_sequence s ON s.seqrelid = c.oid
    WHERE c.relkind = 'S'
      AND NOT EXISTS (SELECT 1 FROM pg_depend dep
                       WHERE dep.objid = c.oid
                         AND dep.classid = 'pg_class'::regclass
                         AND dep.deptype = 'i')

    UNION ALL

    SELECT 5, ns.nspname, c.relname,
           format(E'CREATE TABLE IF NOT EXISTS %I.%I (\n%s\n);',
                  ns.nspname, c.relname,
                  (SELECT string_agg(
                              '    ' || format('%I %s%s%s',
                                  a.attname,
                                  format_type(a.atttypid, a.atttypmod),
                                  CASE
                                      WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                                      WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                                      WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
                                      ELSE COALESCE(' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid), '')
                                  END,
                                  CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),
                              E',\n' ORDER BY a.attnum)
                     FROM pg_attribute a
                     LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
                    WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped))
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    WHERE c.relkind IN ('r', 'p')

    UNION ALL

    SELECT 6, ns.nspname, c.relname || '.' || con.conname,
           format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s;',
                  ns.nspname, c.relname, con.conname, pg_get_constraintdef(con.oid))
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE con.contype IN ('p', 'u', 'c')

    UNION ALL

    SELECT 7, ns.nspname, c.relname || '.' || con.conname,
           format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s;',
                  ns.nspname, c.relname, con.conname, pg_get_constraintdef(con.oid))
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE con.contype = 'f'

    UNION ALL

    SELECT 8, ns.nspname, ic.relname,
           pg_get_indexdef(i.indexrelid) || ';'
    FROM pg_index i
    JOIN pg_class ic ON ic.oid = i.indexrelid
    JOIN pg_class c ON c.oid = i.indrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE NOT EXISTS (SELECT 1 FROM pg_constraint con
                       WHERE con.conindid = i.indexrelid
                         AND con.contype IN ('p', 'u', 'x'))

    UNION ALL

    SELECT 9, ns.nspname, c.relname,
           format('ALTER SEQUENCE %I.%I OWNED BY %I.%I.%I;',
                  ns.nspname, c.relname, tns.nspname, t.relname, a.attname)
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    JOIN pg_depend d ON d.objid = c.oid
                    AND d.classid = 'pg_class'::regclass
                    AND d.deptype = 'a'
    JOIN pg_class t ON t.oid = d.refobjid
    JOIN pg_namespace tns ON tns.oid = t.relnamespace
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
    WHERE c.relkind = 'S'

    UNION ALL

    SELECT 10, ns.nspname, c.relname,
           format(E'CREATE OR REPLACE VIEW %I.%I AS\n%s', ns.nspname, c.relname,
                  pg_get_viewdef(c.oid, true))
    FROM pg_class c
    JOIN ns ON ns.oid = c.relnamespace
    WHERE c.relkind = 'v'

    UNION ALL

    SELECT 11, ns.nspname, c.relname || '.' || t.tgname,
           pg_get_triggerdef(t.oid) || ';'
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE NOT t.tgisinternal

    UNION ALL

    -- Reference data, and only reference data.
    --
    -- Migrations 000006 and 000007 create these two lookup tables and fill them
    -- in the same breath. A baseline taken at version 17 is replayed with the
    -- counter forced past both, so their INSERT statements never run and every
    -- status foreign key fails on the first real row.
    --
    -- These rows are read from the live database rather than copied out of the
    -- migrations, so a status added in production reaches the baseline on the
    -- next extraction instead of quietly going missing. The list below is
    -- deliberately explicit: a table that holds business rows has no place in a
    -- schema baseline, and guessing which is which from the catalog would sooner
    -- or later export somebody's data.
    SELECT 12, 'ass', 'issuer_status',
           string_agg(
               format('INSERT INTO ass.issuer_status (id, code, label, is_final) VALUES (%s, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.code, s.label, s.is_final),
               E'\n' ORDER BY s.id)
    FROM ass.issuer_status s

    UNION ALL

    SELECT 12, 'ass', 'real_estate_status',
           string_agg(
               format('INSERT INTO ass.real_estate_status (id, code, label, is_final, is_public, "position") VALUES (%s, %L, %L, %L, %L, %s) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.code, s.label, s.is_final, s.is_public, s."position"),
               E'\n' ORDER BY s.id)
    FROM ass.real_estate_status s

    UNION ALL

    -- This one is worse than the two above: no migration creates it either.
    -- 000010 already speaks of "the existing reference table", so it predates
    -- the migration history entirely. A database built from the migrations
    -- alone gets the table from nowhere and its rows from nowhere, and the
    -- first order written fails on fk_issuance_orders_status.
    SELECT 12, 'iss', 'issuance_order_statuses',
           string_agg(
               format('INSERT INTO iss.issuance_order_statuses (id, code, label, is_final, counts_as_reserved) VALUES (%s, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
                      s.id, s.code, s.label, s.is_final, s.counts_as_reserved),
               E'\n' ORDER BY s.id)
    FROM iss.issuance_order_statuses s

    UNION ALL

    -- Comments, which are not decoration in this repository.
    --
    -- The migrations carry fifteen COMMENT statements, and several hold the
    -- reasoning behind a constraint rather than a description of it: why
    -- issuer_id is mandatory, what counts_as_reserved means and why it cannot
    -- be derived from is_final, how a token name is built and what breaks if
    -- two tokens share one.
    --
    -- A baseline replayed with the counter forced past those migrations drops
    -- every one of them: the rebuilt database keeps the rules and loses the
    -- reasons. Extracting them puts the reasoning back where a developer meets
    -- it, in \d+ on the table he is about to change.
    SELECT 13, ns.nspname, c.relname || '.' || COALESCE(a.attname, ''),
           format('COMMENT ON %s %s IS %L;',
                  CASE WHEN d.objsubid = 0 THEN 'TABLE' ELSE 'COLUMN' END,
                  CASE WHEN d.objsubid = 0
                       THEN format('%I.%I', ns.nspname, c.relname)
                       ELSE format('%I.%I.%I', ns.nspname, c.relname, a.attname)
                  END,
                  d.description)
    FROM pg_description d
    JOIN pg_class c ON c.oid = d.objoid
    JOIN ns ON ns.oid = c.relnamespace
    LEFT JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = d.objsubid
    WHERE d.classoid = 'pg_class'::regclass
      AND c.relkind IN ('r', 'v')
      AND (d.objsubid = 0 OR a.attname IS NOT NULL)

    UNION ALL

    SELECT 14, ns.nspname, con.conname,
           format('COMMENT ON CONSTRAINT %I ON %I.%I IS %L;',
                  con.conname, ns.nspname, c.relname, d.description)
    FROM pg_description d
    JOIN pg_constraint con ON con.oid = d.objoid
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN ns ON ns.oid = c.relnamespace
    WHERE d.classoid = 'pg_constraint'::regclass

)
SELECT string_agg(ddl, E'\n' ORDER BY ord, o2, o3) AS baseline
FROM parts;
